import { Product } from "../types";

export interface ConfectionerySnackItem {
  id: string;
  name: string;
  nameEn: string;
  price: number;
  unit: string;
  unitEn: string;
  subCategory: string;
  subCategoryId: string;
  image: string;
  brand: string;
}

export const CONFECTIONERY_SNACKS_ITEMS: ConfectionerySnackItem[] = [
  // SUB-CATEGORY 1: "চিপস ও পপকর্ন" (chips-popcorn)
  {
    id: "conf_chips_01",
    name: "লেইস চিপস",
    nameEn: "Lays Potato Chips",
    price: 20,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "চিপস ও পপকর্ন",
    subCategoryId: "chips-popcorn",
    image: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80",
    brand: "Lays"
  },
  {
    id: "conf_chips_02",
    name: "মিস্টার টুইস্ট চিপস",
    nameEn: "Mr. Twist Chips",
    price: 10,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "চিপস ও পপকর্ন",
    subCategoryId: "chips-popcorn",
    image: "https://images.unsplash.com/photo-1621447504864-d8686e12698c?w=500&auto=format&fit=crop&q=80",
    brand: "Mr. Twist"
  },
  {
    id: "conf_chips_03",
    name: "বোম্বে সুইটস আলু ক্র্যাকার",
    nameEn: "Bombay Sweets Potato Cracker",
    price: 10,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "চিপস ও পপকর্ন",
    subCategoryId: "chips-popcorn",
    image: "https://images.unsplash.com/photo-1527842891421-42eec6e703ea?w=500&auto=format&fit=crop&q=80",
    brand: "Bombay Sweets"
  },
  {
    id: "conf_chips_04",
    name: "বোম্বে সুইটস আলু ক্র্যাকার (বড়)",
    nameEn: "Bombay Sweets Potato Cracker Large",
    price: 20,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "চিপস ও পপকর্ন",
    subCategoryId: "chips-popcorn",
    image: "https://images.unsplash.com/photo-1527842891421-42eec6e703ea?w=500&auto=format&fit=crop&q=80",
    brand: "Bombay Sweets"
  },
  {
    id: "conf_chips_05",
    name: "রিং চিপস",
    nameEn: "Ring Chips Small",
    price: 5,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "চিপস ও পপকর্ন",
    subCategoryId: "chips-popcorn",
    image: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80",
    brand: "Bombay Sweets"
  },
  {
    id: "conf_chips_06",
    name: "রিং চিপস (মাঝারি)",
    nameEn: "Ring Chips Medium",
    price: 10,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "চিপস ও পপকর্ন",
    subCategoryId: "chips-popcorn",
    image: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80",
    brand: "Bombay Sweets"
  },
  {
    id: "conf_chips_07",
    name: "বোম্বে মির্চা চিপস (৳৩০)",
    nameEn: "Bombay Mircha Chips (৳30)",
    price: 30,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "চিপস ও পপকর্ন",
    subCategoryId: "chips-popcorn",
    image: "https://images.unsplash.com/photo-1621447504864-d8686e12698c?w=500&auto=format&fit=crop&q=80",
    brand: "Bombay Sweets"
  },
  {
    id: "conf_chips_08",
    name: "বোম্বে মির্চা চিপস (৳৫০)",
    nameEn: "Bombay Mircha Chips (৳50)",
    price: 50,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "চিপস ও পপকর্ন",
    subCategoryId: "chips-popcorn",
    image: "https://images.unsplash.com/photo-1621447504864-d8686e12698c?w=500&auto=format&fit=crop&q=80",
    brand: "Bombay Sweets"
  },
  {
    id: "conf_chips_09",
    name: "বোম্বে মির্চা চিপস (৳১০)",
    nameEn: "Bombay Mircha Chips (৳10)",
    price: 10,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "চিপস ও পপকর্ন",
    subCategoryId: "chips-popcorn",
    image: "https://images.unsplash.com/photo-1621447504864-d8686e12698c?w=500&auto=format&fit=crop&q=80",
    brand: "Bombay Sweets"
  },
  {
    id: "conf_chips_10",
    name: "বোম্বে মির্চা চিপস (৳১০০)",
    nameEn: "Bombay Mircha Chips (৳100)",
    price: 100,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "চিপস ও পপকর্ন",
    subCategoryId: "chips-popcorn",
    image: "https://images.unsplash.com/photo-1621447504864-d8686e12698c?w=500&auto=format&fit=crop&q=80",
    brand: "Bombay Sweets"
  },
  {
    id: "conf_chips_11",
    name: "বোম্বে মির্চা চিপস (৳১৫০)",
    nameEn: "Bombay Mircha Chips (৳150)",
    price: 150,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "চিপস ও পপকর্ন",
    subCategoryId: "chips-popcorn",
    image: "https://images.unsplash.com/photo-1621447504864-d8686e12698c?w=500&auto=format&fit=crop&q=80",
    brand: "Bombay Sweets"
  },
  {
    id: "conf_chips_12",
    name: "পপকর্ন চিপস",
    nameEn: "Popcorn Chips Regular",
    price: 10,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "চিপস ও পপকর্ন",
    subCategoryId: "chips-popcorn",
    image: "https://images.unsplash.com/photo-1578849278619-e73505e9610f?w=500&auto=format&fit=crop&q=80",
    brand: "Popcorn Snacks"
  },
  {
    id: "conf_chips_13",
    name: "পপকর্ন চিপস (বড়)",
    nameEn: "Popcorn Chips Large",
    price: 20,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "চিপস ও পপকর্ন",
    subCategoryId: "chips-popcorn",
    image: "https://images.unsplash.com/photo-1578849278619-e73505e9610f?w=500&auto=format&fit=crop&q=80",
    brand: "Popcorn Snacks"
  },
  {
    id: "conf_chips_14",
    name: "সান চিপস",
    nameEn: "Sun Chips Regular",
    price: 20,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "চিপস ও পপকর্ন",
    subCategoryId: "chips-popcorn",
    image: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80",
    brand: "Sun Chips"
  },
  {
    id: "conf_chips_15",
    name: "সান চিপস (বড়)",
    nameEn: "Sun Chips Large",
    price: 50,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "চিপস ও পপকর্ন",
    subCategoryId: "chips-popcorn",
    image: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80",
    brand: "Sun Chips"
  },
  {
    id: "conf_chips_16",
    name: "বোম্বে আলুজ নুডুলস স্ন্যাকস",
    nameEn: "Bombay Alooz Noodles Snacks",
    price: 20,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "চিপস ও পপকর্ন",
    subCategoryId: "chips-popcorn",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&auto=format&fit=crop&q=80",
    brand: "Bombay Sweets"
  },
  {
    id: "conf_chips_17",
    name: "প্রিংগেলস চিপস",
    nameEn: "Pringles Potato Crisps",
    price: 200,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "চিপস ও পপকর্ন",
    subCategoryId: "chips-popcorn",
    image: "https://images.unsplash.com/photo-1527842891421-42eec6e703ea?w=500&auto=format&fit=crop&q=80",
    brand: "Pringles"
  },
  {
    id: "conf_chips_18",
    name: "প্রিংগেলস চিপস স্পেশাল",
    nameEn: "Pringles Crisps Special Imported",
    price: 250,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "চিপস ও পপকর্ন",
    subCategoryId: "chips-popcorn",
    image: "https://images.unsplash.com/photo-1527842891421-42eec6e703ea?w=500&auto=format&fit=crop&q=80",
    brand: "Pringles"
  },
  {
    id: "conf_chips_19",
    name: "পপকর্ন ছোট (১ জার)",
    nameEn: "Popcorn Small Jar",
    price: 40,
    unit: "১ জার",
    unitEn: "1 jar",
    subCategory: "চিপস ও পপকর্ন",
    subCategoryId: "chips-popcorn",
    image: "https://images.unsplash.com/photo-1578849278619-e73505e9610f?w=500&auto=format&fit=crop&q=80",
    brand: "Crisp Pop"
  },
  {
    id: "conf_chips_20",
    name: "পপকর্ন মাঝারি (১ জার)",
    nameEn: "Popcorn Medium Jar",
    price: 80,
    unit: "১ জার",
    unitEn: "1 jar",
    subCategory: "চিপস ও পপকর্ন",
    subCategoryId: "chips-popcorn",
    image: "https://images.unsplash.com/photo-1578849278619-e73505e9610f?w=500&auto=format&fit=crop&q=80",
    brand: "Crisp Pop"
  },
  {
    id: "conf_chips_21",
    name: "পপকর্ন বড় (১ জার)",
    nameEn: "Popcorn Large Jar",
    price: 100,
    unit: "১ জার",
    unitEn: "1 jar",
    subCategory: "চিপস ও পপকর্ন",
    subCategoryId: "chips-popcorn",
    image: "https://images.unsplash.com/photo-1578849278619-e73505e9610f?w=500&auto=format&fit=crop&q=80",
    brand: "Crisp Pop"
  },

  // SUB-CATEGORY 2: "বাদাম, ডাল ও চানাচুর" (nuts-chanachur)
  {
    id: "conf_nuts_22",
    name: "ঝাল চানাচুর",
    nameEn: "Hot & Spicy Chanachur",
    price: 5,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "বাদাম, ডাল ও চানাচুর",
    subCategoryId: "nuts-chanachur",
    image: "https://images.unsplash.com/photo-1621447504864-d8686e12698c?w=500&auto=format&fit=crop&q=80",
    brand: "কাঁচা বাজার"
  },
  {
    id: "conf_nuts_23",
    name: "ডাল ভাজা",
    nameEn: "Crispy Dal Bhaja",
    price: 10,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "বাদাম, ডাল ও চানাচুর",
    subCategoryId: "nuts-chanachur",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=80",
    brand: "কাঁচা বাজার"
  },
  {
    id: "conf_nuts_24",
    name: "মুগ ডাল ভাজা ছোট",
    nameEn: "Fried Moong Dal Small",
    price: 20,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "বাদাম, ডাল ও চানাচুর",
    subCategoryId: "nuts-chanachur",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=80",
    brand: "কাঁচা বাজার"
  },
  {
    id: "conf_nuts_25",
    name: "মুগ ডাল ভাজা বড়",
    nameEn: "Fried Moong Dal Large",
    price: 40,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "বাদাম, ডাল ও চানাচুর",
    subCategoryId: "nuts-chanachur",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=80",
    brand: "কাঁচা বাজার"
  },
  {
    id: "conf_nuts_26",
    name: "মুড়ির চানাচুর",
    nameEn: "Muri Chanachur Mix",
    price: 10,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "বাদাম, ডাল ও চানাচুর",
    subCategoryId: "nuts-chanachur",
    image: "https://images.unsplash.com/photo-1621447504864-d8686e12698c?w=500&auto=format&fit=crop&q=80",
    brand: "কাঁচা বাজার"
  },
  {
    id: "conf_nuts_27",
    name: "ঝাল মুড়ি মিশ্রণ",
    nameEn: "Jhal Muri Seasoning Mix",
    price: 10,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "বাদাম, ডাল ও চানাচুর",
    subCategoryId: "nuts-chanachur",
    image: "https://images.unsplash.com/photo-1621447504864-d8686e12698c?w=500&auto=format&fit=crop&q=80",
    brand: "কাঁচা বাজার"
  },
  {
    id: "conf_nuts_28",
    name: "লবণাক্ত বাদাম",
    nameEn: "Salted Peanuts",
    price: 50,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "বাদাম, ডাল ও চানাচুর",
    subCategoryId: "nuts-chanachur",
    image: "https://images.unsplash.com/photo-1536591375315-1b836814d600?w=500&auto=format&fit=crop&q=80",
    brand: "কাঁচা বাজার"
  },
  {
    id: "conf_nuts_29",
    name: "লবণাক্ত বাদাম (বড় প্যাক)",
    nameEn: "Salted Peanuts Large",
    price: 100,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "বাদাম, ডাল ও চানাচুর",
    subCategoryId: "nuts-chanachur",
    image: "https://images.unsplash.com/photo-1536591375315-1b836814d600?w=500&auto=format&fit=crop&q=80",
    brand: "কাঁচা বাজার"
  },
  {
    id: "conf_nuts_30",
    name: "কাঁচা বাদাম",
    nameEn: "Raw Fresh Peanuts",
    price: 50,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "বাদাম, ডাল ও চানাচুর",
    subCategoryId: "nuts-chanachur",
    image: "https://images.unsplash.com/photo-1536591375315-1b836814d600?w=500&auto=format&fit=crop&q=80",
    brand: "কাঁচা বাজার"
  },
  {
    id: "conf_nuts_31",
    name: "কাঁচা বাদাম (বড় প্যাক)",
    nameEn: "Raw Fresh Peanuts Large",
    price: 100,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "বাদাম, ডাল ও চানাচুর",
    subCategoryId: "nuts-chanachur",
    image: "https://images.unsplash.com/photo-1536591375315-1b836814d600?w=500&auto=format&fit=crop&q=80",
    brand: "কাঁচা বাজার"
  },
  {
    id: "conf_nuts_32",
    name: "স্পেশাল মিক্সড বাদাম (২৫০ গ্রাম বয়াম)",
    nameEn: "Special Mixed Nuts 250g Jar",
    price: 250,
    unit: "২৫০ গ্রাম বয়াম",
    unitEn: "250g jar",
    subCategory: "বাদাম, ডাল ও চানাচুর",
    subCategoryId: "nuts-chanachur",
    image: "https://images.unsplash.com/photo-1536591375315-1b836814d600?w=500&auto=format&fit=crop&q=80",
    brand: "কাঁচা বাজার প্রিমিয়াম"
  },
  {
    id: "conf_nuts_33",
    name: "স্পেশাল মিক্সড বাদাম (৪০০ গ্রাম বয়াম)",
    nameEn: "Special Mixed Nuts 400g Jar",
    price: 300,
    unit: "৪০০ গ্রাম বয়াম",
    unitEn: "400g jar",
    subCategory: "বাদাম, ডাল ও চানাচুর",
    subCategoryId: "nuts-chanachur",
    image: "https://images.unsplash.com/photo-1536591375315-1b836814d600?w=500&auto=format&fit=crop&q=80",
    brand: "কাঁচা বাজার প্রিমিয়াম"
  },
  {
    id: "conf_nuts_34",
    name: "স্পেশাল মিক্সড বাদাম (৫০০ গ্রাম বয়াম)",
    nameEn: "Special Mixed Nuts 500g Jar",
    price: 350,
    unit: "৫০০ গ্রাম বয়াম",
    unitEn: "500g jar",
    subCategory: "বাদাম, ডাল ও চানাচুর",
    subCategoryId: "nuts-chanachur",
    image: "https://images.unsplash.com/photo-1536591375315-1b836814d600?w=500&auto=format&fit=crop&q=80",
    brand: "কাঁচা বাজার প্রিমিয়াম"
  },

  // SUB-CATEGORY 3: "আইসক্রিম ও ডেইরি ডিলাইট" (icecream-dairy)
  {
    id: "conf_ice_35",
    name: "ইগলু ভ্যানিলা কাপ আইসক্রিম",
    nameEn: "Igloo Vanilla Cup Ice Cream",
    price: 30,
    unit: "১টি",
    unitEn: "1 pc",
    subCategory: "আইসক্রিম ও ডেইরি ডিলাইট",
    subCategoryId: "icecream-dairy",
    image: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=500&auto=format&fit=crop&q=80",
    brand: "Igloo"
  },
  {
    id: "conf_ice_36",
    name: "ইগলু চকলেট কাপ আইসক্রিম",
    nameEn: "Igloo Chocolate Cup Ice Cream",
    price: 30,
    unit: "১টি",
    unitEn: "1 pc",
    subCategory: "আইসক্রিম ও ডেইরি ডিলাইট",
    subCategoryId: "icecream-dairy",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=500&auto=format&fit=crop&q=80",
    brand: "Igloo"
  },
  {
    id: "conf_ice_37",
    name: "ইগলু স্ট্রবেরি কাপ আইসক্রিম",
    nameEn: "Igloo Strawberry Cup Ice Cream",
    price: 30,
    unit: "১টি",
    unitEn: "1 pc",
    subCategory: "আইসক্রিম ও ডেইরি ডিলাইট",
    subCategoryId: "icecream-dairy",
    image: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=500&auto=format&fit=crop&q=80",
    brand: "Igloo"
  },
  {
    id: "conf_ice_38",
    name: "ইগলু আম কাপ আইসক্রিম",
    nameEn: "Igloo Mango Cup Ice Cream",
    price: 30,
    unit: "১টি",
    unitEn: "1 pc",
    subCategory: "আইসক্রিম ও ডেইরি ডিলাইট",
    subCategoryId: "icecream-dairy",
    image: "https://images.unsplash.com/photo-1505394033641-40c6ad1178d7?w=500&auto=format&fit=crop&q=80",
    brand: "Igloo"
  },
  {
    id: "conf_ice_39",
    name: "ইগলু ভ্যানিলা বাটি (৫০০ গ্রাম)",
    nameEn: "Igloo Vanilla Tub 500g",
    price: 150,
    unit: "৫০০ গ্রাম",
    unitEn: "500g tub",
    subCategory: "আইসক্রিম ও ডেইরি ডিলাইট",
    subCategoryId: "icecream-dairy",
    image: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=500&auto=format&fit=crop&q=80",
    brand: "Igloo"
  },
  {
    id: "conf_ice_40",
    name: "ইগলু চকলেট বাটি (৫০০ গ্রাম)",
    nameEn: "Igloo Chocolate Tub 500g",
    price: 150,
    unit: "৫০০ গ্রাম",
    unitEn: "500g tub",
    subCategory: "আইসক্রিম ও ডেইরি ডিলাইট",
    subCategoryId: "icecream-dairy",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=500&auto=format&fit=crop&q=80",
    brand: "Igloo"
  },
  {
    id: "conf_ice_41",
    name: "ইগলু স্ট্রবেরি বাটি (৫০০ গ্রাম)",
    nameEn: "Igloo Strawberry Tub 500g",
    price: 150,
    unit: "৫০০ গ্রাম",
    unitEn: "500g tub",
    subCategory: "আইসক্রিম ও ডেইরি ডিলাইট",
    subCategoryId: "icecream-dairy",
    image: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=500&auto=format&fit=crop&q=80",
    brand: "Igloo"
  },
  {
    id: "conf_ice_42",
    name: "ইগলু আম বাটি (৫০০ গ্রাম)",
    nameEn: "Igloo Mango Tub 500g",
    price: 150,
    unit: "৫০০ গ্রাম",
    unitEn: "500g tub",
    subCategory: "আইসক্রিম ও ডেইরি ডিলাইট",
    subCategoryId: "icecream-dairy",
    image: "https://images.unsplash.com/photo-1505394033641-40c6ad1178d7?w=500&auto=format&fit=crop&q=80",
    brand: "Igloo"
  },
  {
    id: "conf_ice_43",
    name: "পোলার ভ্যানিলা কাপ আইসক্রিম",
    nameEn: "Polar Vanilla Cup Ice Cream",
    price: 30,
    unit: "১টি",
    unitEn: "1 pc",
    subCategory: "আইসক্রিম ও ডেইরি ডিলাইট",
    subCategoryId: "icecream-dairy",
    image: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=500&auto=format&fit=crop&q=80",
    brand: "Polar"
  },
  {
    id: "conf_ice_44",
    name: "পোলার চকলেট কাপ আইসক্রিম",
    nameEn: "Polar Chocolate Cup Ice Cream",
    price: 30,
    unit: "১টি",
    unitEn: "1 pc",
    subCategory: "আইসক্রিম ও ডেইরি ডিলাইট",
    subCategoryId: "icecream-dairy",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=500&auto=format&fit=crop&q=80",
    brand: "Polar"
  },
  {
    id: "conf_ice_45",
    name: "পোলার স্ট্রবেরি কাপ আইসক্রিম",
    nameEn: "Polar Strawberry Cup Ice Cream",
    price: 30,
    unit: "১টি",
    unitEn: "1 pc",
    subCategory: "আইসক্রিম ও ডেইরি ডিলাইট",
    subCategoryId: "icecream-dairy",
    image: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=500&auto=format&fit=crop&q=80",
    brand: "Polar"
  },
  {
    id: "conf_ice_46",
    name: "পোলার ভ্যানিলা বাটি (৫০০ গ্রাম)",
    nameEn: "Polar Vanilla Tub 500g",
    price: 150,
    unit: "৫০০ গ্রাম",
    unitEn: "500g tub",
    subCategory: "আইসক্রিম ও ডেইরি ডিলাইট",
    subCategoryId: "icecream-dairy",
    image: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=500&auto=format&fit=crop&q=80",
    brand: "Polar"
  },
  {
    id: "conf_ice_47",
    name: "পোলার চকলেট বাটি (৫০০ গ্রাম)",
    nameEn: "Polar Chocolate Tub 500g",
    price: 150,
    unit: "৫০০ গ্রাম",
    unitEn: "500g tub",
    subCategory: "আইসক্রিম ও ডেইরি ডিলাইট",
    subCategoryId: "icecream-dairy",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=500&auto=format&fit=crop&q=80",
    brand: "Polar"
  },
  {
    id: "conf_ice_48",
    name: "পোলার স্ট্রবেরি বাটি (৫০০ গ্রাম)",
    nameEn: "Polar Strawberry Tub 500g",
    price: 150,
    unit: "৫০০ গ্রাম",
    unitEn: "500g tub",
    subCategory: "আইসক্রিম ও ডেইরি ডিলাইট",
    subCategoryId: "icecream-dairy",
    image: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=500&auto=format&fit=crop&q=80",
    brand: "Polar"
  },
  {
    id: "conf_ice_49",
    name: "স্পেশাল কুলফি আইসক্রিম",
    nameEn: "Special Shahi Kulfi",
    price: 300,
    unit: "১টি",
    unitEn: "1 pc",
    subCategory: "আইসক্রিম ও ডেইরি ডিলাইট",
    subCategoryId: "icecream-dairy",
    image: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=500&auto=format&fit=crop&q=80",
    brand: "কাঁচা বাজার স্পেশাল"
  },
  {
    id: "conf_ice_50",
    name: "স্পেশাল আম কুলফি আইসক্রিম",
    nameEn: "Special Mango Kulfi",
    price: 300,
    unit: "১টি",
    unitEn: "1 pc",
    subCategory: "আইসক্রিম ও ডেইরি ডিলাইট",
    subCategoryId: "icecream-dairy",
    image: "https://images.unsplash.com/photo-1505394033641-40c6ad1178d7?w=500&auto=format&fit=crop&q=80",
    brand: "কাঁচা বাজার স্পেশাল"
  },
  {
    id: "conf_ice_51",
    name: "প্রিমিয়াম ফালুদা আইসক্রিম",
    nameEn: "Premium Royal Faluda Ice Cream",
    price: 400,
    unit: "১টি",
    unitEn: "1 pc",
    subCategory: "আইসক্রিম ও ডেইরি ডিলাইট",
    subCategoryId: "icecream-dairy",
    image: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=500&auto=format&fit=crop&q=80",
    brand: "কাঁচা বাজার স্পেশাল"
  },
  {
    id: "conf_ice_52",
    name: "চকলেট আনন্দ আইসক্রিম",
    nameEn: "Chocolate Delight Ice Cream",
    price: 300,
    unit: "১টি",
    unitEn: "1 pc",
    subCategory: "আইসক্রিম ও ডেইরি ডিলাইট",
    subCategoryId: "icecream-dairy",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=500&auto=format&fit=crop&q=80",
    brand: "কাঁচা বাজার স্পেশাল"
  },
  {
    id: "conf_ice_53",
    name: "ক্যারামেল আনন্দ আইসক্রিম",
    nameEn: "Caramel Delight Ice Cream",
    price: 350,
    unit: "১টি",
    unitEn: "1 pc",
    subCategory: "আইসক্রিম ও ডেইরি ডিলাইট",
    subCategoryId: "icecream-dairy",
    image: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=500&auto=format&fit=crop&q=80",
    brand: "কাঁচা বাজার স্পেশাল"
  },
  {
    id: "conf_ice_54",
    name: "ফ্রুট আনন্দ আইসক্রিম",
    nameEn: "Fruit Delight Ice Cream",
    price: 350,
    unit: "১টি",
    unitEn: "1 pc",
    subCategory: "আইসক্রিম ও ডেইরি ডিলাইট",
    subCategoryId: "icecream-dairy",
    image: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=500&auto=format&fit=crop&q=80",
    brand: "কাঁচা বাজার স্পেশাল"
  },
  {
    id: "conf_ice_55",
    name: "ফ্রোজেন মিষ্টি দই",
    nameEn: "Frozen Sweet Yoghurt",
    price: 30,
    unit: "১টি",
    unitEn: "1 pc",
    subCategory: "আইসক্রিম ও ডেইরি ডিলাইট",
    subCategoryId: "icecream-dairy",
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&auto=format&fit=crop&q=80",
    brand: "কাঁচা বাজার"
  },

  // SUB-CATEGORY 4: "পানীয়, জুস ও বেভারেজ" (beverages-drinks)
  {
    id: "conf_bev_56",
    name: "প্রাণ আম জুস",
    nameEn: "Pran Mango Juice",
    price: 20,
    unit: "১টি",
    unitEn: "1 pc",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1546173159-315724a31696?w=500&auto=format&fit=crop&q=80",
    brand: "Pran"
  },
  {
    id: "conf_bev_57",
    name: "প্রাণ আম জুস (১ লিটার)",
    nameEn: "Pran Mango Juice 1L",
    price: 70,
    unit: "১ লিটার",
    unitEn: "1 liter",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1546173159-315724a31696?w=500&auto=format&fit=crop&q=80",
    brand: "Pran"
  },
  {
    id: "conf_bev_58",
    name: "প্রাণ ফ্রুটো (৫০০ মিলি)",
    nameEn: "Pran Frooto 500ml",
    price: 45,
    unit: "৫০০ মিলি",
    unitEn: "500 ml",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1546173159-315724a31696?w=500&auto=format&fit=crop&q=80",
    brand: "Pran"
  },
  {
    id: "conf_bev_59",
    name: "প্রাণ লাচ্ছি (২৫০ মিলি)",
    nameEn: "Pran Lassi 250ml",
    price: 20,
    unit: "২৫০ মিলি",
    unitEn: "250 ml",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1546173159-315724a31696?w=500&auto=format&fit=crop&q=80",
    brand: "Pran"
  },
  {
    id: "conf_bev_60",
    name: "প্রাণ আপেল জুস ক্যান (২৫০ মিলি)",
    nameEn: "Pran Apple Juice Can 250ml",
    price: 50,
    unit: "২৫০ মিলি",
    unitEn: "250 ml",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80",
    brand: "Pran"
  },
  {
    id: "conf_bev_61",
    name: "কমলা জুস ক্যান (২৫০ মিলি)",
    nameEn: "Orange Juice Can 250ml",
    price: 50,
    unit: "২৫০ মিলি",
    unitEn: "250 ml",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80",
    brand: "Pran"
  },
  {
    id: "conf_bev_62",
    name: "আনারস জুস ক্যান (২৫০ মিলি)",
    nameEn: "Pineapple Juice Can 250ml",
    price: 50,
    unit: "২৫০ মিলি",
    unitEn: "250 ml",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80",
    brand: "Pran"
  },
  {
    id: "conf_bev_63",
    name: "ফ্রুটিকা আম জুস (২৫০ মিলি)",
    nameEn: "Frutika Mango Juice 250ml",
    price: 25,
    unit: "২৫০ মিলি",
    unitEn: "250 ml",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1546173159-315724a31696?w=500&auto=format&fit=crop&q=80",
    brand: "Frutika"
  },
  {
    id: "conf_bev_64",
    name: "ফ্রুটিকা আম জুস (১ লিটার)",
    nameEn: "Frutika Mango Juice 1L",
    price: 90,
    unit: "১ লিটার",
    unitEn: "1 liter",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1546173159-315724a31696?w=500&auto=format&fit=crop&q=80",
    brand: "Frutika"
  },
  {
    id: "conf_bev_65",
    name: "শেজান আম জুস (২০০ মিলি)",
    nameEn: "Shezan Mango Juice 200ml",
    price: 20,
    unit: "২০০ মিলি",
    unitEn: "200 ml",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1546173159-315724a31696?w=500&auto=format&fit=crop&q=80",
    brand: "Shezan"
  },
  {
    id: "conf_bev_66",
    name: "শেজান আম জুস (১ লিটার)",
    nameEn: "Shezan Mango Juice 1L",
    price: 80,
    unit: "১ লিটার",
    unitEn: "1 liter",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1546173159-315724a31696?w=500&auto=format&fit=crop&q=80",
    brand: "Shezan"
  },
  {
    id: "conf_bev_67",
    name: "কোকা-কোলা (২৫০ মিলি)",
    nameEn: "Coca-Cola 250ml",
    price: 25,
    unit: "২৫০ মিলি",
    unitEn: "250 ml",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80",
    brand: "Coca-Cola"
  },
  {
    id: "conf_bev_68",
    name: "কোকা-কোলা (৪০০ মিলি)",
    nameEn: "Coca-Cola 400ml",
    price: 40,
    unit: "৪০০ মিলি",
    unitEn: "400 ml",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80",
    brand: "Coca-Cola"
  },
  {
    id: "conf_bev_69",
    name: "কোকা-কোলা (১ লিটার)",
    nameEn: "Coca-Cola 1L",
    price: 80,
    unit: "১ লিটার",
    unitEn: "1 liter",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80",
    brand: "Coca-Cola"
  },
  {
    id: "conf_bev_70",
    name: "কোকা-কোলা (২ লিটার)",
    nameEn: "Coca-Cola 2L",
    price: 150,
    unit: "২ লিটার",
    unitEn: "2 liter",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80",
    brand: "Coca-Cola"
  },
  {
    id: "conf_bev_71",
    name: "পেপসি (২৫০ মিলি)",
    nameEn: "Pepsi 250ml",
    price: 25,
    unit: "২৫০ মিলি",
    unitEn: "250 ml",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=500&auto=format&fit=crop&q=80",
    brand: "Pepsi"
  },
  {
    id: "conf_bev_72",
    name: "পেপসি (৫০০ মিলি)",
    nameEn: "Pepsi 500ml",
    price: 50,
    unit: "৫০০ মিলি",
    unitEn: "500 ml",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=500&auto=format&fit=crop&q=80",
    brand: "Pepsi"
  },
  {
    id: "conf_bev_73",
    name: "পেপসি (১ লিটার)",
    nameEn: "Pepsi 1L",
    price: 90,
    unit: "১ লিটার",
    unitEn: "1 liter",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=500&auto=format&fit=crop&q=80",
    brand: "Pepsi"
  },
  {
    id: "conf_bev_74",
    name: "৭ আপ (২৫০ মিলি)",
    nameEn: "7UP 250ml",
    price: 25,
    unit: "২৫০ মিলি",
    unitEn: "250 ml",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1581098365948-6a5a912b7a49?w=500&auto=format&fit=crop&q=80",
    brand: "7UP"
  },
  {
    id: "conf_bev_75",
    name: "৭ আপ (৫০০ মিলি)",
    nameEn: "7UP 500ml",
    price: 50,
    unit: "৫০০ মিলি",
    unitEn: "500 ml",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1581098365948-6a5a912b7a49?w=500&auto=format&fit=crop&q=80",
    brand: "7UP"
  },
  {
    id: "conf_bev_76",
    name: "৭ আপ (১ লিটার)",
    nameEn: "7UP 1L",
    price: 90,
    unit: "১ লিটার",
    unitEn: "1 liter",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1581098365948-6a5a912b7a49?w=500&auto=format&fit=crop&q=80",
    brand: "7UP"
  },
  {
    id: "conf_bev_77",
    name: "৭ আপ (২ লিটার)",
    nameEn: "7UP 2L",
    price: 140,
    unit: "২ লিটার",
    unitEn: "2 liter",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1581098365948-6a5a912b7a49?w=500&auto=format&fit=crop&q=80",
    brand: "7UP"
  },
  {
    id: "conf_bev_78",
    name: "মাউন্টেন ডিউ (২৫০ মিলি)",
    nameEn: "Mountain Dew 250ml",
    price: 25,
    unit: "২৫০ মিলি",
    unitEn: "250 ml",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1581098365948-6a5a912b7a49?w=500&auto=format&fit=crop&q=80",
    brand: "Mountain Dew"
  },
  {
    id: "conf_bev_79",
    name: "মাউন্টেন ডিউ (৪০০ মিলি)",
    nameEn: "Mountain Dew 400ml",
    price: 40,
    unit: "৪০০ মিলি",
    unitEn: "400 ml",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1581098365948-6a5a912b7a49?w=500&auto=format&fit=crop&q=80",
    brand: "Mountain Dew"
  },
  {
    id: "conf_bev_80",
    name: "স্প্রাইট (২৫০ মিলি)",
    nameEn: "Sprite 250ml",
    price: 25,
    unit: "২৫০ মিলি",
    unitEn: "250 ml",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=500&auto=format&fit=crop&q=80",
    brand: "Sprite"
  },
  {
    id: "conf_bev_81",
    name: "স্প্রাইট (৫০০ মিলি)",
    nameEn: "Sprite 500ml",
    price: 40,
    unit: "৫০০ মিলি",
    unitEn: "500 ml",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=500&auto=format&fit=crop&q=80",
    brand: "Sprite"
  },
  {
    id: "conf_bev_82",
    name: "স্প্রাইট (১ লিটার)",
    nameEn: "Sprite 1L",
    price: 80,
    unit: "১ লিটার",
    unitEn: "1 liter",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=500&auto=format&fit=crop&q=80",
    brand: "Sprite"
  },
  {
    id: "conf_bev_83",
    name: "স্প্রাইট (২ লিটার)",
    nameEn: "Sprite 2L",
    price: 150,
    unit: "২ লিটার",
    unitEn: "2 liter",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=500&auto=format&fit=crop&q=80",
    brand: "Sprite"
  },
  {
    id: "conf_bev_84",
    name: "মিরিন্ডা কমলা (২৫০ মিলি)",
    nameEn: "Mirinda Orange 250ml",
    price: 25,
    unit: "২৫০ মিলি",
    unitEn: "250 ml",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80",
    brand: "Mirinda"
  },
  {
    id: "conf_bev_85",
    name: "মিরিন্ডা কমলা (৫০০ মিলি)",
    nameEn: "Mirinda Orange 500ml",
    price: 50,
    unit: "৫০০ মিলি",
    unitEn: "500 ml",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80",
    brand: "Mirinda"
  },
  {
    id: "conf_bev_86",
    name: "মিরিন্ডা কমলা (১ লিটার)",
    nameEn: "Mirinda Orange 1L",
    price: 90,
    unit: "১ লিটার",
    unitEn: "1 liter",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80",
    brand: "Mirinda"
  },
  {
    id: "conf_bev_87",
    name: "রেড বুল ক্যান (২৫০ মিলি)",
    nameEn: "Red Bull Energy Drink 250ml",
    price: 250,
    unit: "২৫০ মিলি",
    unitEn: "250 ml can",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80",
    brand: "Red Bull"
  },
  {
    id: "conf_bev_88",
    name: "রেড বুল ক্যান (৩০০ মিলি)",
    nameEn: "Red Bull Energy Drink 300ml",
    price: 300,
    unit: "৩০০ মিলি",
    unitEn: "300 ml can",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80",
    brand: "Red Bull"
  },
  {
    id: "conf_bev_89",
    name: "রেড বুল ক্যান স্পেশাল",
    nameEn: "Red Bull Special Edition Can",
    price: 350,
    unit: "১টি",
    unitEn: "1 can",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80",
    brand: "Red Bull"
  },
  {
    id: "conf_bev_90",
    name: "মোজো (২৫০ মিলি)",
    nameEn: "Mojo Cola 250ml",
    price: 20,
    unit: "২৫০ মিলি",
    unitEn: "250 ml",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80",
    brand: "Akij Mojo"
  },
  {
    id: "conf_bev_91",
    name: "মোজো (৫০০ মিলি)",
    nameEn: "Mojo Cola 500ml",
    price: 40,
    unit: "৫০০ মিলি",
    unitEn: "500 ml",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80",
    brand: "Akij Mojo"
  },
  {
    id: "conf_bev_92",
    name: "মোজো (১ লিটার)",
    nameEn: "Mojo Cola 1L",
    price: 70,
    unit: "১ লিটার",
    unitEn: "1 liter",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80",
    brand: "Akij Mojo"
  },
  {
    id: "conf_bev_93",
    name: "মোজো (২ লিটার)",
    nameEn: "Mojo Cola 2L",
    price: 120,
    unit: "২ লিটার",
    unitEn: "2 liter",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80",
    brand: "Akij Mojo"
  },
  {
    id: "conf_bev_94",
    name: "ফ্রেশ মিনারেল পানি (৫০০ মিলি)",
    nameEn: "Fresh Mineral Water 500ml",
    price: 20,
    unit: "৫০০ মিলি",
    unitEn: "500 ml",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=500&auto=format&fit=crop&q=80",
    brand: "Fresh"
  },
  {
    id: "conf_bev_95",
    name: "ফ্রেশ মিনারেল পানি (১ লিটার)",
    nameEn: "Fresh Mineral Water 1L",
    price: 30,
    unit: "১ লিটার",
    unitEn: "1 liter",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=500&auto=format&fit=crop&q=80",
    brand: "Fresh"
  },
  {
    id: "conf_bev_96",
    name: "ফ্রেশ মিনারেল পানি (২ লিটার)",
    nameEn: "Fresh Mineral Water 2L",
    price: 40,
    unit: "২ লিটার",
    unitEn: "2 liter",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=500&auto=format&fit=crop&q=80",
    brand: "Fresh"
  },
  {
    id: "conf_bev_97",
    name: "ফ্রেশ মিনারেল পানি (৫ লিটার)",
    nameEn: "Fresh Mineral Water 5L",
    price: 100,
    unit: "৫ লিটার",
    unitEn: "5 liter",
    subCategory: "পানীয়, জুস ও বেভারেজ",
    subCategoryId: "beverages-drinks",
    image: "https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=500&auto=format&fit=crop&q=80",
    brand: "Fresh"
  },

  // SUB-CATEGORY 5: "চা, কফি ও হেলথ ড্রিংকস" (tea-coffee-health)
  {
    id: "conf_tea_98",
    name: "ইস্পাহানি মির্জাপুর চা (১০০ গ্রাম বক্স)",
    nameEn: "Ispahani Mirzapore Tea 100g Box",
    price: 50,
    unit: "১০০ গ্রাম বক্স",
    unitEn: "100g box",
    subCategory: "চা, কফি ও হেলথ ড্রিংকস",
    subCategoryId: "tea-coffee-health",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80",
    brand: "Ispahani"
  },
  {
    id: "conf_tea_99",
    name: "ইস্পাহানি মির্জাপুর চা (২০০ গ্রাম বক্স)",
    nameEn: "Ispahani Mirzapore Tea 200g Box",
    price: 120,
    unit: "২০০ গ্রাম বক্স",
    unitEn: "200g box",
    subCategory: "চা, কফি ও হেলথ ড্রিংকস",
    subCategoryId: "tea-coffee-health",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80",
    brand: "Ispahani"
  },
  {
    id: "conf_tea_100",
    name: "ইস্পাহানি মির্জাপুর চা (৪০০ গ্রাম বক্স)",
    nameEn: "Ispahani Mirzapore Tea 400g Box",
    price: 200,
    unit: "৪০০ গ্রাম বক্স",
    unitEn: "400g box",
    subCategory: "চা, কফি ও হেলথ ড্রিংকস",
    subCategoryId: "tea-coffee-health",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80",
    brand: "Ispahani"
  },
  {
    id: "conf_tea_101",
    name: "ফিনলে ব্ল্যাক টি (১০০ গ্রাম)",
    nameEn: "Finlay Black Tea 100g",
    price: 50,
    unit: "১০০ গ্রাম",
    unitEn: "100g pack",
    subCategory: "চা, কফি ও হেলথ ড্রিংকস",
    subCategoryId: "tea-coffee-health",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80",
    brand: "Finlay"
  },
  {
    id: "conf_tea_102",
    name: "ফিনলে ব্ল্যাক টি (২০০ গ্রাম)",
    nameEn: "Finlay Black Tea 200g",
    price: 120,
    unit: "২০০ গ্রাম",
    unitEn: "200g pack",
    subCategory: "চা, কফি ও হেলথ ড্রিংকস",
    subCategoryId: "tea-coffee-health",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80",
    brand: "Finlay"
  },
  {
    id: "conf_tea_103",
    name: "ফিনলে ব্ল্যাক টি (৪০০ গ্রাম)",
    nameEn: "Finlay Black Tea 400g",
    price: 200,
    unit: "৪০০ গ্রাম",
    unitEn: "400g pack",
    subCategory: "চা, কফি ও হেলথ ড্রিংকস",
    subCategoryId: "tea-coffee-health",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80",
    brand: "Finlay"
  },
  {
    id: "conf_tea_104",
    name: "টপলি টি ব্যাগ (৫০ পিস)",
    nameEn: "Tapley Tea Bags 50pcs",
    price: 100,
    unit: "৫০ পিস",
    unitEn: "50 teabags",
    subCategory: "চা, কফি ও হেলথ ড্রিংকস",
    subCategoryId: "tea-coffee-health",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80",
    brand: "Tapley"
  },
  {
    id: "conf_tea_105",
    name: "নেসক্যাফে ক্লাসিক কফি জার",
    nameEn: "Nescafe Classic Coffee Jar",
    price: 195,
    unit: "১ জার",
    unitEn: "1 jar",
    subCategory: "চা, কফি ও হেলথ ড্রিংকস",
    subCategoryId: "tea-coffee-health",
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=80",
    brand: "Nescafe"
  },
  {
    id: "conf_tea_106",
    name: "নেসক্যাফে কফি (৫০ গ্রাম জার)",
    nameEn: "Nescafe Coffee 50g Jar",
    price: 270,
    unit: "৫০ গ্রাম জার",
    unitEn: "50g jar",
    subCategory: "চা, কফি ও হেলথ ড্রিংকস",
    subCategoryId: "tea-coffee-health",
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=80",
    brand: "Nescafe"
  },
  {
    id: "conf_tea_107",
    name: "নেসক্যাফে কফি (১৮০ গ্রাম জার)",
    nameEn: "Nescafe Coffee 180g Jar",
    price: 950,
    unit: "১৮০ গ্রাম জার",
    unitEn: "180g jar",
    subCategory: "চা, কফি ও হেলথ ড্রিংকস",
    subCategoryId: "tea-coffee-health",
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=80",
    brand: "Nescafe"
  },
  {
    id: "conf_tea_108",
    name: "নেসক্যাফে ৩ ইন ১ কফি (২০ স্যাশে প্যাকেট)",
    nameEn: "Nescafe 3 in 1 Coffee (20 Sachets)",
    price: 15,
    unit: "১ স্যাশে",
    unitEn: "1 sachet",
    subCategory: "চা, কফি ও হেলথ ড্রিংকস",
    subCategoryId: "tea-coffee-health",
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=80",
    brand: "Nescafe"
  },
  {
    id: "conf_tea_109",
    name: "নেসলে মাইলো হেলথ ড্রিংক ছোট",
    nameEn: "Nestle Milo Health Drink Small",
    price: 250,
    unit: "১টি",
    unitEn: "1 pack",
    subCategory: "চা, কফি ও হেলথ ড্রিংকস",
    subCategoryId: "tea-coffee-health",
    image: "https://images.unsplash.com/photo-1584278860047-22db9ff82bed?w=500&auto=format&fit=crop&q=80",
    brand: "Nestle Milo"
  },
  {
    id: "conf_tea_110",
    name: "নেসলে মাইলো হেলথ ড্রিংক মাঝারি",
    nameEn: "Nestle Milo Health Drink Medium",
    price: 400,
    unit: "১টি",
    unitEn: "1 pack",
    subCategory: "চা, কফি ও হেলথ ড্রিংকস",
    subCategoryId: "tea-coffee-health",
    image: "https://images.unsplash.com/photo-1584278860047-22db9ff82bed?w=500&auto=format&fit=crop&q=80",
    brand: "Nestle Milo"
  },
  {
    id: "conf_tea_111",
    name: "নেসলে মাইলো হেলথ ড্রিংক বড়",
    nameEn: "Nestle Milo Health Drink Large",
    price: 550,
    unit: "১টি",
    unitEn: "1 pack",
    subCategory: "চা, কফি ও হেলথ ড্রিংকস",
    subCategoryId: "tea-coffee-health",
    image: "https://images.unsplash.com/photo-1584278860047-22db9ff82bed?w=500&auto=format&fit=crop&q=80",
    brand: "Nestle Milo"
  },
  {
    id: "conf_tea_112",
    name: "হরলিক্স রেগুলার (২৫০ গ্রাম)",
    nameEn: "Horlicks Regular Malt 250g",
    price: 250,
    unit: "২৫০ গ্রাম",
    unitEn: "250g pack",
    subCategory: "চা, কফি ও হেলথ ড্রিংকস",
    subCategoryId: "tea-coffee-health",
    image: "https://images.unsplash.com/photo-1584278860047-22db9ff82bed?w=500&auto=format&fit=crop&q=80",
    brand: "Horlicks"
  },
  {
    id: "conf_tea_113",
    name: "হরলিক্স রেগুলার (৫০০ গ্রাম)",
    nameEn: "Horlicks Regular Malt 500g",
    price: 400,
    unit: "৫০০ গ্রাম",
    unitEn: "500g jar",
    subCategory: "চা, কফি ও হেলথ ড্রিংকস",
    subCategoryId: "tea-coffee-health",
    image: "https://images.unsplash.com/photo-1584278860047-22db9ff82bed?w=500&auto=format&fit=crop&q=80",
    brand: "Horlicks"
  },
  {
    id: "conf_tea_114",
    name: "হরলিক্স রেগুলার (১ কেজি / ১০০০ গ্রাম)",
    nameEn: "Horlicks Regular Malt 1kg",
    price: 850,
    unit: "১ কেজি",
    unitEn: "1 kg jar",
    subCategory: "চা, কফি ও হেলথ ড্রিংকস",
    subCategoryId: "tea-coffee-health",
    image: "https://images.unsplash.com/photo-1584278860047-22db9ff82bed?w=500&auto=format&fit=crop&q=80",
    brand: "Horlicks"
  },
  {
    id: "conf_tea_115",
    name: "হরলিক্স চকলেট ফ্লেভার (৫০০ গ্রাম)",
    nameEn: "Horlicks Chocolate Flavor 500g",
    price: 500,
    unit: "৫০০ গ্রাম",
    unitEn: "500g jar",
    subCategory: "চা, কফি ও হেলথ ড্রিংকস",
    subCategoryId: "tea-coffee-health",
    image: "https://images.unsplash.com/photo-1584278860047-22db9ff82bed?w=500&auto=format&fit=crop&q=80",
    brand: "Horlicks"
  },
  {
    id: "conf_tea_116",
    name: "জুনিয়র হরলিক্স স্টেজ ১ (৫০০ গ্রাম)",
    nameEn: "Junior Horlicks Stage 1 500g",
    price: 450,
    unit: "৫০০ গ্রাম",
    unitEn: "500g jar",
    subCategory: "চা, কফি ও হেলথ ড্রিংকস",
    subCategoryId: "tea-coffee-health",
    image: "https://images.unsplash.com/photo-1584278860047-22db9ff82bed?w=500&auto=format&fit=crop&q=80",
    brand: "Horlicks"
  },
  {
    id: "conf_tea_117",
    name: "জুনিয়র হরলিক্স স্টেজ ২ (১ কেজি / ১০০০ গ্রাম)",
    nameEn: "Junior Horlicks Stage 2 1kg",
    price: 1100,
    unit: "১ কেজি",
    unitEn: "1 kg jar",
    subCategory: "চা, কফি ও হেলথ ড্রিংকস",
    subCategoryId: "tea-coffee-health",
    image: "https://images.unsplash.com/photo-1584278860047-22db9ff82bed?w=500&auto=format&fit=crop&q=80",
    brand: "Horlicks"
  },

  // SUB-CATEGORY 6: "কেক, চকলেট ও মিষ্টি কনফেকশনারি" (cakes-sweets)
  {
    id: "conf_cake_118",
    name: "কাপ কেক ভ্যানিলা (১ পিস)",
    nameEn: "Vanilla Cup Cake 1pc",
    price: 10,
    unit: "১টি",
    unitEn: "1 pc",
    subCategory: "কেক, চকলেট ও মিষ্টি কনফেকশনারি",
    subCategoryId: "cakes-sweets",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&auto=format&fit=crop&q=80",
    brand: "কাঁচা বাজার বেকারি"
  },
  {
    id: "conf_cake_119",
    name: "কাপ কেক ফ্যামিলি প্যাক (১ প্যাকেট / ৮ পিস)",
    nameEn: "Cup Cake Family Pack (8 pcs)",
    price: 80,
    unit: "১ প্যাকেট",
    unitEn: "1 pack (8 pcs)",
    subCategory: "কেক, চকলেট ও মিষ্টি কনফেকশনারি",
    subCategoryId: "cakes-sweets",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&auto=format&fit=crop&q=80",
    brand: "কাঁচা বাজার বেকারি"
  },
  {
    id: "conf_cake_120",
    name: "কিন্ডার জয় দেশি ছোট",
    nameEn: "Kinder Joy Local Small",
    price: 40,
    unit: "১টি",
    unitEn: "1 pc",
    subCategory: "কেক, চকলেট ও মিষ্টি কনফেকশনারি",
    subCategoryId: "cakes-sweets",
    image: "https://images.unsplash.com/photo-1582293041079-7814c2f12063?w=500&auto=format&fit=crop&q=80",
    brand: "Kinder"
  },
  {
    id: "conf_cake_121",
    name: "কিন্ডার জয় দেশি বড়",
    nameEn: "Kinder Joy Local Large",
    price: 60,
    unit: "১টি",
    unitEn: "1 pc",
    subCategory: "কেক, চকলেট ও মিষ্টি কনফেকশনারি",
    subCategoryId: "cakes-sweets",
    image: "https://images.unsplash.com/photo-1582293041079-7814c2f12063?w=500&auto=format&fit=crop&q=80",
    brand: "Kinder"
  },
  {
    id: "conf_cake_122",
    name: "কিন্ডার জয় ইন্ডিয়ান স্পেশাল",
    nameEn: "Kinder Joy Indian Special Edition",
    price: 120,
    unit: "১টি",
    unitEn: "1 pc",
    subCategory: "কেক, চকলেট ও মিষ্টি কনফেকশনারি",
    subCategoryId: "cakes-sweets",
    image: "https://images.unsplash.com/photo-1582293041079-7814c2f12063?w=500&auto=format&fit=crop&q=80",
    brand: "Kinder"
  },
  {
    id: "conf_cake_123",
    name: "সুইট মার্শম্যালো মিনি (১ প্যাকেট)",
    nameEn: "Sweet Marshmallow Mini Pack",
    price: 10,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "কেক, চকলেট ও মিষ্টি কনফেকশনারি",
    subCategoryId: "cakes-sweets",
    image: "https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?w=500&auto=format&fit=crop&q=80",
    brand: "Sweet Treats"
  },
  {
    id: "conf_cake_124",
    name: "সুইট মার্শম্যালো স্ট্যান্ডার্ড (১ প্যাকেট)",
    nameEn: "Sweet Marshmallow Standard Pack",
    price: 20,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "কেক, চকলেট ও মিষ্টি কনফেকশনারি",
    subCategoryId: "cakes-sweets",
    image: "https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?w=500&auto=format&fit=crop&q=80",
    brand: "Sweet Treats"
  },
  {
    id: "conf_cake_125",
    name: "সুইট মার্শম্যালো মাঝারি (১ প্যাকেট)",
    nameEn: "Sweet Marshmallow Medium Pack",
    price: 50,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "কেক, চকলেট ও মিষ্টি কনফেকশনারি",
    subCategoryId: "cakes-sweets",
    image: "https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?w=500&auto=format&fit=crop&q=80",
    brand: "Sweet Treats"
  },
  {
    id: "conf_cake_126",
    name: "সুইট মার্শম্যালো জাম্বো (১ প্যাকেট)",
    nameEn: "Sweet Marshmallow Jumbo Pack",
    price: 200,
    unit: "১ প্যাকেট",
    unitEn: "1 pack",
    subCategory: "কেক, চকলেট ও মিষ্টি কনফেকশনারি",
    subCategoryId: "cakes-sweets",
    image: "https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?w=500&auto=format&fit=crop&q=80",
    brand: "Sweet Treats"
  }
];

export const CONFECTIONERY_SNACKS_SUBCATEGORIES = [
  { id: "chips-popcorn", nameBn: "চিপস ও পপকর্ন", nameEn: "Chips & Popcorn", order: 1 },
  { id: "nuts-chanachur", nameBn: "বাদাম, ডাল ও চানাচুর", nameEn: "Nuts, Pulses & Chanachur", order: 2 },
  { id: "icecream-dairy", nameBn: "আইসক্রিম ও ডেইরি ডিলাইট", nameEn: "Ice Cream & Dairy Delight", order: 3 },
  { id: "beverages-drinks", nameBn: "পানীয়, জুস ও বেভারেজ", nameEn: "Beverages, Juice & Drinks", order: 4 },
  { id: "tea-coffee-health", nameBn: "চা, কফি ও হেলথ ড্রিংকস", nameEn: "Tea, Coffee & Health Drinks", order: 5 },
  { id: "cakes-sweets", nameBn: "কেক, চকলেট ও মিষ্টি কনফেকশনারি", nameEn: "Cakes, Chocolates & Sweets", order: 6 }
];

export const CONFECTIONERY_SNACKS_RAW: Product[] = CONFECTIONERY_SNACKS_ITEMS.map((item, idx) => ({
  id: item.id,
  name: item.name,
  nameBn: item.name,
  nameEn: item.nameEn,
  price: item.price,
  originalPrice: item.price,
  unit: item.unit,
  unitBn: item.unit,
  unitEn: item.unitEn,
  category: "কনফেকশনারি",
  categoryId: "snacks-biscuits",
  categoryBn: "কনফেকশনারি",
  categoryEn: "Confectionery",
  subCategory: item.subCategory,
  subcategory: item.subCategory,
  subCategoryId: item.subCategoryId,
  subcategoryId: item.subCategoryId,
  image: item.image,
  imageUrl: item.image,
  inStock: true,
  stock: 100,
  isAvailable: true,
  isDeleted: false,
  deleted: false,
  status: "active",
  rating: 4.8,
  reviewCount: 18,
  brand: item.brand,
  descriptionBn: `${item.name} - তাজা ও সুস্বাদু কোয়ালিটি পণ্য। ডেলিভারি কাঁচা বাজার থেকে। মূল্য: ৳${item.price} (${item.unit})।`,
  descriptionEn: `${item.nameEn} - Fresh, premium quality snack. Price: BDT ${item.price} (${item.unitEn}).`,
  sku: `KB-SNK-${String(idx + 1).padStart(3, "0")}`,
  displayOrder: idx + 1,
  order: idx + 1
}));
