import { Product } from "../types";

export const NEW_GROCERY_PRODUCTS_RAW: Product[] = [
  {
    id: "gr52",
    nameBn: "রূপচাঁদা ফর্টিফাইড সয়াবিন তেল",
    nameEn: "Rupchanda Fortified Soybean Oil (1 Litre Bottle)",
    price: 195,
    originalPrice: 195,
    unitBn: "১ লিটার বোতল",
    unitEn: "1 Litre Bottle",
    unit: "১ লিটার বোতল",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    subCategory: "তেল, চিনি, লবণ ও গুড়",
    image: "https://placehold.co/400x400/png?text=Rupchanda+Oil+1L",
    imageUrl: "https://placehold.co/400x400/png?text=Rupchanda+Oil+1L",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 15,
    brand: "রূপচাঁদা",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি রূপচাঁদা ফর্টিফাইড সয়াবিন তেল (১ লিটার বোতল)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Rupchanda Fortified Soybean Oil (1 Litre Bottle). Fast delivery guaranteed.",
    displayOrder: 52,
    order: 52
  },
  {
    id: "gr53",
    nameBn: "রূপচাঁদা ফর্টিফাইড সয়াবিন তেল",
    nameEn: "Rupchanda Fortified Soybean Oil (2 Litre Bottle)",
    price: 380,
    originalPrice: 380,
    unitBn: "২ লিটার বোতল",
    unitEn: "2 Litre Bottle",
    unit: "২ লিটার বোতল",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    subCategory: "তেল, চিনি, লবণ ও গুড়",
    image: "https://placehold.co/400x400/png?text=Rupchanda+Oil+2L",
    imageUrl: "https://placehold.co/400x400/png?text=Rupchanda+Oil+2L",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 22,
    brand: "রূপচাঁদা",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি রূপচাঁদা ফর্টিফাইড সয়াবিন তেল (২ লিটার বোতল)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Rupchanda Fortified Soybean Oil (2 Litre Bottle). Fast delivery guaranteed.",
    displayOrder: 53,
    order: 53
  },
  {
    id: "gr54",
    nameBn: "রূপচাঁদা ফর্টিফাইড সয়াবিন তেল",
    nameEn: "Rupchanda Fortified Soybean Oil (5 Litre Bottle)",
    price: 980,
    originalPrice: 980,
    unitBn: "৫ লিটার বোতল",
    unitEn: "5 Litre Bottle",
    unit: "৫ লিটার বোতল",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    subCategory: "তেল, চিনি, লবণ ও গুড়",
    image: "https://placehold.co/400x400/png?text=Rupchanda+Oil+5L",
    imageUrl: "https://placehold.co/400x400/png?text=Rupchanda+Oil+5L",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 29,
    brand: "রূপচাঁদা",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি রূপচাঁদা ফর্টিফাইড সয়াবিন তেল (৫ লিটার বোতল)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Rupchanda Fortified Soybean Oil (5 Litre Bottle). Fast delivery guaranteed.",
    displayOrder: 54,
    order: 54
  },
  {
    id: "gr55",
    nameBn: "তীর ফর্টিফাইড সয়াবিন তেল",
    nameEn: "Teer Fortified Soybean Oil (1 Litre Bottle)",
    price: 195,
    originalPrice: 195,
    unitBn: "১ লিটার বোতল",
    unitEn: "1 Litre Bottle",
    unit: "১ লিটার বোতল",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    subCategory: "তেল, চিনি, লবণ ও গুড়",
    image: "https://placehold.co/400x400/png?text=Teer+Oil+1L",
    imageUrl: "https://placehold.co/400x400/png?text=Teer+Oil+1L",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 36,
    brand: "তীর",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি তীর ফর্টিফাইড সয়াবিন তেল (১ লিটার বোতল)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Teer Fortified Soybean Oil (1 Litre Bottle). Fast delivery guaranteed.",
    displayOrder: 55,
    order: 55
  },
  {
    id: "gr56",
    nameBn: "ফ্রেশ ফর্টিফাইড সয়াবিন তেল",
    nameEn: "Fresh Fortified Soybean Oil (5 Litre Bottle)",
    price: 970,
    originalPrice: 970,
    unitBn: "৫ লিটার বোতল",
    unitEn: "5 Litre Bottle",
    unit: "৫ লিটার বোতল",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    subCategory: "তেল, চিনি, লবণ ও গুড়",
    image: "https://placehold.co/400x400/png?text=Fresh+Oil+5L",
    imageUrl: "https://placehold.co/400x400/png?text=Fresh+Oil+5L",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 43,
    brand: "ফ্রেশ",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি ফ্রেশ ফর্টিফাইড সয়াবিন তেল (৫ লিটার বোতল)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Fresh Fortified Soybean Oil (5 Litre Bottle). Fast delivery guaranteed.",
    displayOrder: 56,
    order: 56
  },
  {
    id: "gr57",
    nameBn: "রাঁধুনী খাঁটি সরিষার তেল",
    nameEn: "Radhuni Pure Mustard Oil (250 ml Bottle)",
    price: 95,
    originalPrice: 95,
    unitBn: "২৫০ মিলি বোতল",
    unitEn: "250 ml Bottle",
    unit: "২৫০ মিলি বোতল",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    subCategory: "তেল, চিনি, লবণ ও গুড়",
    image: "https://placehold.co/400x400/png?text=Radhuni+Mustard+250ml",
    imageUrl: "https://placehold.co/400x400/png?text=Radhuni+Mustard+250ml",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 20,
    brand: "রাঁধুনী",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি রাঁধুনী খাঁটি সরিষার তেল (২৫০ মিলি বোতল)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Radhuni Pure Mustard Oil (250 ml Bottle). Fast delivery guaranteed.",
    displayOrder: 57,
    order: 57
  },
  {
    id: "gr58",
    nameBn: "রাঁধুনী খাঁটি সরিষার তেল",
    nameEn: "Radhuni Pure Mustard Oil (500 ml Bottle)",
    price: 180,
    originalPrice: 180,
    unitBn: "৫০০ মিলি বোতল",
    unitEn: "500 ml Bottle",
    unit: "৫০০ মিলি বোতল",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    subCategory: "তেল, চিনি, লবণ ও গুড়",
    image: "https://placehold.co/400x400/png?text=Radhuni+Mustard+500ml",
    imageUrl: "https://placehold.co/400x400/png?text=Radhuni+Mustard+500ml",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 27,
    brand: "রাঁধুনী",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি রাঁধুনী খাঁটি সরিষার তেল (৫০০ মিলি বোতল)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Radhuni Pure Mustard Oil (500 ml Bottle). Fast delivery guaranteed.",
    displayOrder: 58,
    order: 58
  },
  {
    id: "gr59",
    nameBn: "রাঁধুনী খাঁটি সরিষার তেল",
    nameEn: "Radhuni Pure Mustard Oil (1 Litre Bottle)",
    price: 350,
    originalPrice: 350,
    unitBn: "১ লিটার বোতল",
    unitEn: "1 Litre Bottle",
    unit: "১ লিটার বোতল",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    subCategory: "তেল, চিনি, লবণ ও গুড়",
    image: "https://placehold.co/400x400/png?text=Radhuni+Mustard+1L",
    imageUrl: "https://placehold.co/400x400/png?text=Radhuni+Mustard+1L",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 34,
    brand: "রাঁধুনী",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি রাঁধুনী খাঁটি সরিষার তেল (১ লিটার বোতল)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Radhuni Pure Mustard Oil (1 Litre Bottle). Fast delivery guaranteed.",
    displayOrder: 59,
    order: 59
  },
  {
    id: "gr60",
    nameBn: "প্রাণ খাঁটি সরিষার তেল",
    nameEn: "Pran Pure Mustard Oil (1 Litre Bottle)",
    price: 350,
    originalPrice: 350,
    unitBn: "১ লিটার বোতল",
    unitEn: "1 Litre Bottle",
    unit: "১ লিটার বোতল",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    subCategory: "তেল, চিনি, লবণ ও গুড়",
    image: "https://placehold.co/400x400/png?text=Pran+Mustard+1L",
    imageUrl: "https://placehold.co/400x400/png?text=Pran+Mustard+1L",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 41,
    brand: "প্রাণ",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি প্রাণ খাঁটি সরিষার তেল (১ লিটার বোতল)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Pran Pure Mustard Oil (1 Litre Bottle). Fast delivery guaranteed.",
    displayOrder: 60,
    order: 60
  },
  {
    id: "gr61",
    nameBn: "ফরচুন রাইস ব্রান তেল",
    nameEn: "Fortune Rice Bran Oil (5 Litre Bottle)",
    price: 1080,
    originalPrice: 1080,
    unitBn: "৫ লিটার বোতল",
    unitEn: "5 Litre Bottle",
    unit: "৫ লিটার বোতল",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    subCategory: "তেল, চিনি, লবণ ও গুড়",
    image: "https://placehold.co/400x400/png?text=Fortune+Rice+Bran",
    imageUrl: "https://placehold.co/400x400/png?text=Fortune+Rice+Bran",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 18,
    brand: "ফরচুন",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি ফরচুন রাইস ব্রান তেল (৫ লিটার বোতল)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Fortune Rice Bran Oil (5 Litre Bottle). Fast delivery guaranteed.",
    displayOrder: 61,
    order: 61
  },
  {
    id: "gr62",
    nameBn: "সানড্রপ সানফ্লাওয়ার তেল",
    nameEn: "Sundrop Sunflower Oil (1 Litre Bottle)",
    price: 320,
    originalPrice: 320,
    unitBn: "১ লিটার বোতল",
    unitEn: "1 Litre Bottle",
    unit: "১ লিটার বোতল",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    subCategory: "তেল, চিনি, লবণ ও গুড়",
    image: "https://placehold.co/400x400/png?text=Sundrop+Sunflower",
    imageUrl: "https://placehold.co/400x400/png?text=Sundrop+Sunflower",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 25,
    brand: "সানড্রপ",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি সানড্রপ সানফ্লাওয়ার তেল (১ লিটার বোতল)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Sundrop Sunflower Oil (1 Litre Bottle). Fast delivery guaranteed.",
    displayOrder: 62,
    order: 62
  },
  {
    id: "gr63",
    nameBn: "এসিআই পিওর আয়োডিনযুক্ত লবণ",
    nameEn: "ACI Pure Iodized Salt (1 kg Packet)",
    price: 42,
    originalPrice: 42,
    unitBn: "১ কেজি প্যাকেট",
    unitEn: "1 kg Packet",
    unit: "১ কেজি প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    subCategory: "তেল, চিনি, লবণ ও গুড়",
    image: "https://placehold.co/400x400/png?text=ACI+Salt",
    imageUrl: "https://placehold.co/400x400/png?text=ACI+Salt",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 32,
    brand: "এসিআই পিওর",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি এসিআই পিওর আয়োডিনযুক্ত লবণ (১ কেজি প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic ACI Pure Iodized Salt (1 kg Packet). Fast delivery guaranteed.",
    displayOrder: 63,
    order: 63
  },
  {
    id: "gr64",
    nameBn: "ফ্রেশ সুপার প্রিমিয়াম লবণ",
    nameEn: "Fresh Super Premium Salt (1 kg Packet)",
    price: 42,
    originalPrice: 42,
    unitBn: "১ কেজি প্যাকেট",
    unitEn: "1 kg Packet",
    unit: "১ কেজি প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    subCategory: "তেল, চিনি, লবণ ও গুড়",
    image: "https://placehold.co/400x400/png?text=Fresh+Salt",
    imageUrl: "https://placehold.co/400x400/png?text=Fresh+Salt",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 39,
    brand: "ফ্রেশ",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি ফ্রেশ সুপার প্রিমিয়াম লবণ (১ কেজি প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Fresh Super Premium Salt (1 kg Packet). Fast delivery guaranteed.",
    displayOrder: 64,
    order: 64
  },
  {
    id: "gr65",
    nameBn: "মোল্লা সুপার সল্ট",
    nameEn: "Molla Super Salt (1 kg Packet)",
    price: 40,
    originalPrice: 40,
    unitBn: "১ কেজি প্যাকেট",
    unitEn: "1 kg Packet",
    unit: "১ কেজি প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    subCategory: "তেল, চিনি, লবণ ও গুড়",
    image: "https://placehold.co/400x400/png?text=Molla+Salt",
    imageUrl: "https://placehold.co/400x400/png?text=Molla+Salt",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 16,
    brand: "মোল্লা",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি মোল্লা সুপার সল্ট (১ কেজি প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Molla Super Salt (1 kg Packet). Fast delivery guaranteed.",
    displayOrder: 65,
    order: 65
  },
  {
    id: "gr66",
    nameBn: "ফ্রেশ রিফাইন্ড সাদা চিনি",
    nameEn: "Fresh Refined White Sugar (1 kg Packet)",
    price: 145,
    originalPrice: 145,
    unitBn: "১ কেজি প্যাকেট",
    unitEn: "1 kg Packet",
    unit: "১ কেজি প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    subCategory: "তেল, চিনি, লবণ ও গুড়",
    image: "https://placehold.co/400x400/png?text=Fresh+Sugar",
    imageUrl: "https://placehold.co/400x400/png?text=Fresh+Sugar",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 23,
    brand: "ফ্রেশ",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি ফ্রেশ রিফাইন্ড সাদা চিনি (১ কেজি প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Fresh Refined White Sugar (1 kg Packet). Fast delivery guaranteed.",
    displayOrder: 66,
    order: 66
  },
  {
    id: "gr67",
    nameBn: "তীর রিফাইন্ড সাদা চিনি",
    nameEn: "Teer Refined White Sugar (1 kg Packet)",
    price: 145,
    originalPrice: 145,
    unitBn: "১ কেজি প্যাকেট",
    unitEn: "1 kg Packet",
    unit: "১ কেজি প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    subCategory: "তেল, চিনি, লবণ ও গুড়",
    image: "https://placehold.co/400x400/png?text=Teer+Sugar",
    imageUrl: "https://placehold.co/400x400/png?text=Teer+Sugar",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 30,
    brand: "তীর",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি তীর রিফাইন্ড সাদা চিনি (১ কেজি প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Teer Refined White Sugar (1 kg Packet). Fast delivery guaranteed.",
    displayOrder: 67,
    order: 67
  },
  {
    id: "gr68",
    nameBn: "দেশি অর্গানিক লাল চিনি",
    nameEn: "Deshi Organic Red Sugar (1 kg Packet)",
    price: 165,
    originalPrice: 165,
    unitBn: "১ কেজি প্যাকেট",
    unitEn: "1 kg Packet",
    unit: "১ কেজি প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    subCategory: "তেল, চিনি, লবণ ও গুড়",
    image: "https://placehold.co/400x400/png?text=Deshi+Red+Sugar",
    imageUrl: "https://placehold.co/400x400/png?text=Deshi+Red+Sugar",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 37,
    brand: "কাচা বাজার",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি দেশি অর্গানিক লাল চিনি (১ কেজি প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Deshi Organic Red Sugar (1 kg Packet). Fast delivery guaranteed.",
    displayOrder: 68,
    order: 68
  },
  {
    id: "gr69",
    nameBn: "তীর মিনিকেট চাল",
    nameEn: "Teer Miniket Rice (5 kg Bag)",
    price: 390,
    originalPrice: 390,
    unitBn: "৫ কেজি ব্যাগ",
    unitEn: "5 kg Bag",
    unit: "৫ কেজি ব্যাগ",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "চাল ও খাদ্যশস্য",
    subCategory: "চাল ও খাদ্যশস্য",
    image: "https://placehold.co/400x400/png?text=Teer+Miniket",
    imageUrl: "https://placehold.co/400x400/png?text=Teer+Miniket",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 44,
    brand: "তীর",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি তীর মিনিকেট চাল (৫ কেজি ব্যাগ)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Teer Miniket Rice (5 kg Bag). Fast delivery guaranteed.",
    displayOrder: 69,
    order: 69
  },
  {
    id: "gr70",
    nameBn: "এসিআই পিওর মিনিকেট চাল",
    nameEn: "ACI Pure Miniket Rice (5 kg Bag)",
    price: 400,
    originalPrice: 400,
    unitBn: "৫ কেজি ব্যাগ",
    unitEn: "5 kg Bag",
    unit: "৫ কেজি ব্যাগ",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "চাল ও খাদ্যশস্য",
    subCategory: "চাল ও খাদ্যশস্য",
    image: "https://placehold.co/400x400/png?text=ACI+Miniket",
    imageUrl: "https://placehold.co/400x400/png?text=ACI+Miniket",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 21,
    brand: "এসিআই পিওর",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি এসিআই পিওর মিনিকেট চাল (৫ কেজি ব্যাগ)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic ACI Pure Miniket Rice (5 kg Bag). Fast delivery guaranteed.",
    displayOrder: 70,
    order: 70
  },
  {
    id: "gr71",
    nameBn: "প্রাণ নাজিরশাইল চাল",
    nameEn: "Pran Nazirshail Rice (5 kg Bag)",
    price: 435,
    originalPrice: 435,
    unitBn: "৫ কেজি ব্যাগ",
    unitEn: "5 kg Bag",
    unit: "৫ কেজি ব্যাগ",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "চাল ও খাদ্যশস্য",
    subCategory: "চাল ও খাদ্যশস্য",
    image: "https://placehold.co/400x400/png?text=Pran+Nazirshail",
    imageUrl: "https://placehold.co/400x400/png?text=Pran+Nazirshail",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 28,
    brand: "প্রাণ",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি প্রাণ নাজিরশাইল চাল (৫ কেজি ব্যাগ)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Pran Nazirshail Rice (5 kg Bag). Fast delivery guaranteed.",
    displayOrder: 71,
    order: 71
  },
  {
    id: "gr72",
    nameBn: "ফ্রেশ প্রিমিয়াম নাজিরশাইল চাল",
    nameEn: "Fresh Premium Nazirshail Rice (5 kg Bag)",
    price: 420,
    originalPrice: 420,
    unitBn: "৫ কেজি ব্যাগ",
    unitEn: "5 kg Bag",
    unit: "৫ কেজি ব্যাগ",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "চাল ও খাদ্যশস্য",
    subCategory: "চাল ও খাদ্যশস্য",
    image: "https://placehold.co/400x400/png?text=Fresh+Nazirshail",
    imageUrl: "https://placehold.co/400x400/png?text=Fresh+Nazirshail",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 35,
    brand: "ফ্রেশ",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি ফ্রেশ প্রিমিয়াম নাজিরশাইল চাল (৫ কেজি ব্যাগ)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Fresh Premium Nazirshail Rice (5 kg Bag). Fast delivery guaranteed.",
    displayOrder: 72,
    order: 72
  },
  {
    id: "gr73",
    nameBn: "ফরচুন বাসমতী চাল",
    nameEn: "Fortune Basmati Rice (1 kg Packet)",
    price: 350,
    originalPrice: 350,
    unitBn: "১ কেজি প্যাকেট",
    unitEn: "1 kg Packet",
    unit: "১ কেজি প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "চাল ও খাদ্যশস্য",
    subCategory: "চাল ও খাদ্যশস্য",
    image: "https://placehold.co/400x400/png?text=Fortune+Basmati",
    imageUrl: "https://placehold.co/400x400/png?text=Fortune+Basmati",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 42,
    brand: "ফরচুন",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি ফরচুন বাসমতী চাল (১ কেজি প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Fortune Basmati Rice (1 kg Packet). Fast delivery guaranteed.",
    displayOrder: 73,
    order: 73
  },
  {
    id: "gr74",
    nameBn: "দাউয়াত বাসমতী চাল",
    nameEn: "Daawat Basmati Rice (1 kg Packet)",
    price: 360,
    originalPrice: 360,
    unitBn: "১ কেজি প্যাকেট",
    unitEn: "1 kg Packet",
    unit: "১ কেজি প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "চাল ও খাদ্যশস্য",
    subCategory: "চাল ও খাদ্যশস্য",
    image: "https://placehold.co/400x400/png?text=Daawat+Basmati",
    imageUrl: "https://placehold.co/400x400/png?text=Daawat+Basmati",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 19,
    brand: "দাউয়াত",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি দাউয়াত বাসমতী চাল (১ কেজি প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Daawat Basmati Rice (1 kg Packet). Fast delivery guaranteed.",
    displayOrder: 74,
    order: 74
  },
  {
    id: "gr75",
    nameBn: "প্রাণ চিনিগুঁড়া পোলাওয়ের চাল",
    nameEn: "Pran Chinigura Aromatic Rice (1 kg Packet)",
    price: 150,
    originalPrice: 150,
    unitBn: "১ কেজি প্যাকেট",
    unitEn: "1 kg Packet",
    unit: "১ কেজি প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "চাল ও খাদ্যশস্য",
    subCategory: "চাল ও খাদ্যশস্য",
    image: "https://placehold.co/400x400/png?text=Pran+Chinigura",
    imageUrl: "https://placehold.co/400x400/png?text=Pran+Chinigura",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 26,
    brand: "প্রাণ",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি প্রাণ চিনিগুঁড়া পোলাওয়ের চাল (১ কেজি প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Pran Chinigura Aromatic Rice (1 kg Packet). Fast delivery guaranteed.",
    displayOrder: 75,
    order: 75
  },
  {
    id: "gr76",
    nameBn: "এসিআই এরোমা চিনিগুঁড়া চাল",
    nameEn: "ACI Aroma Chinigura Rice (1 kg Packet)",
    price: 155,
    originalPrice: 155,
    unitBn: "১ কেজি প্যাকেট",
    unitEn: "1 kg Packet",
    unit: "১ কেজি প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "চাল ও খাদ্যশস্য",
    subCategory: "চাল ও খাদ্যশস্য",
    image: "https://placehold.co/400x400/png?text=ACI+Aroma",
    imageUrl: "https://placehold.co/400x400/png?text=ACI+Aroma",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 33,
    brand: "এসিআই এরোমা",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি এসিআই এরোমা চিনিগুঁড়া চাল (১ কেজি প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic ACI Aroma Chinigura Rice (1 kg Packet). Fast delivery guaranteed.",
    displayOrder: 76,
    order: 76
  },
  {
    id: "gr77",
    nameBn: "চাষী সুগন্ধি চিনিগুঁড়া চাল",
    nameEn: "Chashi Aromatic Chinigura Rice (1 kg Packet)",
    price: 155,
    originalPrice: 155,
    unitBn: "১ কেজি প্যাকেট",
    unitEn: "1 kg Packet",
    unit: "১ কেজি প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "চাল ও খাদ্যশস্য",
    subCategory: "চাল ও খাদ্যশস্য",
    image: "https://placehold.co/400x400/png?text=Chashi+Chinigura",
    imageUrl: "https://placehold.co/400x400/png?text=Chashi+Chinigura",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 40,
    brand: "চাষী",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি চাষী সুগন্ধি চিনিগুঁড়া চাল (১ কেজি প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Chashi Aromatic Chinigura Rice (1 kg Packet). Fast delivery guaranteed.",
    displayOrder: 77,
    order: 77
  },
  {
    id: "gr78",
    nameBn: "তীর দেশি মসুর ডাল",
    nameEn: "Teer Deshi Red Lentil (1 kg Packet)",
    price: 145,
    originalPrice: 145,
    unitBn: "১ কেজি প্যাকেট",
    unitEn: "1 kg Packet",
    unit: "১ কেজি প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    subCategory: "ডাল ও ছোলা",
    image: "https://placehold.co/400x400/png?text=Teer+Mosur+Dal",
    imageUrl: "https://placehold.co/400x400/png?text=Teer+Mosur+Dal",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 17,
    brand: "তীর",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি তীর দেশি মসুর ডাল (১ কেজি প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Teer Deshi Red Lentil (1 kg Packet). Fast delivery guaranteed.",
    displayOrder: 78,
    order: 78
  },
  {
    id: "gr79",
    nameBn: "ফ্রেশ মসুর ডাল (মোটা)",
    nameEn: "Fresh Red Lentil (Coarse) (1 kg Packet)",
    price: 120,
    originalPrice: 120,
    unitBn: "১ কেজি প্যাকেট",
    unitEn: "1 kg Packet",
    unit: "১ কেজি প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    subCategory: "ডাল ও ছোলা",
    image: "https://placehold.co/400x400/png?text=Fresh+Mosur+Dal",
    imageUrl: "https://placehold.co/400x400/png?text=Fresh+Mosur+Dal",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 24,
    brand: "ফ্রেশ",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি ফ্রেশ মসুর ডাল (মোটা) (১ কেজি প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Fresh Red Lentil (Coarse) (1 kg Packet). Fast delivery guaranteed.",
    displayOrder: 79,
    order: 79
  },
  {
    id: "gr80",
    nameBn: "এসিআই পিওর মুগ ডাল (ভাজা)",
    nameEn: "ACI Pure Roasted Moong Dal (500 gm Packet)",
    price: 90,
    originalPrice: 90,
    unitBn: "৫০০ গ্রাম প্যাকেট",
    unitEn: "500 gm Packet",
    unit: "৫০০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    subCategory: "ডাল ও ছোলা",
    image: "https://placehold.co/400x400/png?text=ACI+Moog+Dal+500g",
    imageUrl: "https://placehold.co/400x400/png?text=ACI+Moog+Dal+500g",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 31,
    brand: "এসিআই পিওর",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি এসিআই পিওর মুগ ডাল (ভাজা) (৫০০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic ACI Pure Roasted Moong Dal (500 gm Packet). Fast delivery guaranteed.",
    displayOrder: 80,
    order: 80
  },
  {
    id: "gr81",
    nameBn: "এসিআই পিওর মুগ ডাল (ভাজা)",
    nameEn: "ACI Pure Roasted Moong Dal (1 kg Packet)",
    price: 165,
    originalPrice: 165,
    unitBn: "১ কেজি প্যাকেট",
    unitEn: "1 kg Packet",
    unit: "১ কেজি প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    subCategory: "ডাল ও ছোলা",
    image: "https://placehold.co/400x400/png?text=ACI+Moog+Dal+1kg",
    imageUrl: "https://placehold.co/400x400/png?text=ACI+Moog+Dal+1kg",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 38,
    brand: "এসিআই পিওর",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি এসিআই পিওর মুগ ডাল (ভাজা) (১ কেজি প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic ACI Pure Roasted Moong Dal (1 kg Packet). Fast delivery guaranteed.",
    displayOrder: 81,
    order: 81
  },
  {
    id: "gr82",
    nameBn: "প্রাণ খেসারি ডাল",
    nameEn: "Pran Khesari Dal (500 gm Packet)",
    price: 60,
    originalPrice: 60,
    unitBn: "৫০০ গ্রাম প্যাকেট",
    unitEn: "500 gm Packet",
    unit: "৫০০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    subCategory: "ডাল ও ছোলা",
    image: "https://placehold.co/400x400/png?text=Pran+Khesari+Dal",
    imageUrl: "https://placehold.co/400x400/png?text=Pran+Khesari+Dal",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 15,
    brand: "প্রাণ",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি প্রাণ খেসারি ডাল (৫০০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Pran Khesari Dal (500 gm Packet). Fast delivery guaranteed.",
    displayOrder: 82,
    order: 82
  },
  {
    id: "gr83",
    nameBn: "এসিআই পিওর ছোলার ডাল",
    nameEn: "ACI Pure Chana Dal (1 kg Packet)",
    price: 140,
    originalPrice: 140,
    unitBn: "১ কেজি প্যাকেট",
    unitEn: "1 kg Packet",
    unit: "১ কেজি প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    subCategory: "ডাল ও ছোলা",
    image: "https://placehold.co/400x400/png?text=ACI+Cholar+Dal",
    imageUrl: "https://placehold.co/400x400/png?text=ACI+Cholar+Dal",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 22,
    brand: "এসিআই পিওর",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি এসিআই পিওর ছোলার ডাল (১ কেজি প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic ACI Pure Chana Dal (1 kg Packet). Fast delivery guaranteed.",
    displayOrder: 83,
    order: 83
  },
  {
    id: "gr84",
    nameBn: "ফ্রেশ কাবলি ছোলা",
    nameEn: "Fresh Kabuli Chickpeas (1 kg Packet)",
    price: 230,
    originalPrice: 230,
    unitBn: "১ কেজি প্যাকেট",
    unitEn: "1 kg Packet",
    unit: "১ কেজি প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    subCategory: "ডাল ও ছোলা",
    image: "https://placehold.co/400x400/png?text=Fresh+Kabuli+Chola",
    imageUrl: "https://placehold.co/400x400/png?text=Fresh+Kabuli+Chola",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 29,
    brand: "ফ্রেশ",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি ফ্রেশ কাবলি ছোলা (১ কেজি প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Fresh Kabuli Chickpeas (1 kg Packet). Fast delivery guaranteed.",
    displayOrder: 84,
    order: 84
  },
  {
    id: "gr85",
    nameBn: "এসিআই পিওর দেশি ছোলা",
    nameEn: "ACI Pure Deshi Chickpeas (1 kg Packet)",
    price: 115,
    originalPrice: 115,
    unitBn: "১ কেজি প্যাকেট",
    unitEn: "1 kg Packet",
    unit: "১ কেজি প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    subCategory: "ডাল ও ছোলা",
    image: "https://placehold.co/400x400/png?text=ACI+Deshi+Chola",
    imageUrl: "https://placehold.co/400x400/png?text=ACI+Deshi+Chola",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 36,
    brand: "এসিআই পিওর",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি এসিআই পিওর দেশি ছোলা (১ কেজি প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic ACI Pure Deshi Chickpeas (1 kg Packet). Fast delivery guaranteed.",
    displayOrder: 85,
    order: 85
  },
  {
    id: "gr86",
    nameBn: "প্যাকেট মটর দানা",
    nameEn: "Green Peas Packet (500 gm Packet)",
    price: 55,
    originalPrice: 55,
    unitBn: "৫০০ গ্রাম প্যাকেট",
    unitEn: "500 gm Packet",
    unit: "৫০০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    subCategory: "ডাল ও ছোলা",
    image: "https://placehold.co/400x400/png?text=Motor+Dana",
    imageUrl: "https://placehold.co/400x400/png?text=Motor+Dana",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 43,
    brand: "কাচা বাজার",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি প্যাকেট মটর দানা (৫০০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Green Peas Packet (500 gm Packet). Fast delivery guaranteed.",
    displayOrder: 86,
    order: 86
  },
  {
    id: "gr87",
    nameBn: "তীর সাদা আটা",
    nameEn: "Teer White Atta (Flour) (2 kg Packet)",
    price: 130,
    originalPrice: 130,
    unitBn: "২ কেজি প্যাকেট",
    unitEn: "2 kg Packet",
    unit: "২ কেজি প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "আটা, ময়দা ও সুজি",
    subCategory: "আটা, ময়দা ও সুজি",
    image: "https://placehold.co/400x400/png?text=Teer+Atta",
    imageUrl: "https://placehold.co/400x400/png?text=Teer+Atta",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 20,
    brand: "তীর",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি তীর সাদা আটা (২ কেজি প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Teer White Atta (Flour) (2 kg Packet). Fast delivery guaranteed.",
    displayOrder: 87,
    order: 87
  },
  {
    id: "gr88",
    nameBn: "ফ্রেশ সাদা আটা",
    nameEn: "Fresh White Atta (Flour) (2 kg Packet)",
    price: 130,
    originalPrice: 130,
    unitBn: "২ কেজি প্যাকেট",
    unitEn: "2 kg Packet",
    unit: "২ কেজি প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "আটা, ময়দা ও সুজি",
    subCategory: "আটা, ময়দা ও সুজি",
    image: "https://placehold.co/400x400/png?text=Fresh+Atta",
    imageUrl: "https://placehold.co/400x400/png?text=Fresh+Atta",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 27,
    brand: "ফ্রেশ",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি ফ্রেশ সাদা আটা (২ কেজি প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Fresh White Atta (Flour) (2 kg Packet). Fast delivery guaranteed.",
    displayOrder: 88,
    order: 88
  },
  {
    id: "gr89",
    nameBn: "এসিআই পিওর লাল আটা",
    nameEn: "ACI Pure Whole Wheat Brown Atta (1 kg Packet)",
    price: 72,
    originalPrice: 72,
    unitBn: "১ কেজি প্যাকেট",
    unitEn: "1 kg Packet",
    unit: "১ কেজি প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "আটা, ময়দা ও সুজি",
    subCategory: "আটা, ময়দা ও সুজি",
    image: "https://placehold.co/400x400/png?text=ACI+Brown+Atta+1kg",
    imageUrl: "https://placehold.co/400x400/png?text=ACI+Brown+Atta+1kg",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 34,
    brand: "এসিআই পিওর",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি এসিআই পিওর লাল আটা (১ কেজি প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic ACI Pure Whole Wheat Brown Atta (1 kg Packet). Fast delivery guaranteed.",
    displayOrder: 89,
    order: 89
  },
  {
    id: "gr90",
    nameBn: "এসিআই পিওর লাল আটা",
    nameEn: "ACI Pure Whole Wheat Brown Atta (2 kg Packet)",
    price: 140,
    originalPrice: 140,
    unitBn: "২ কেজি প্যাকেট",
    unitEn: "2 kg Packet",
    unit: "২ কেজি প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "আটা, ময়দা ও সুজি",
    subCategory: "আটা, ময়দা ও সুজি",
    image: "https://placehold.co/400x400/png?text=ACI+Brown+Atta+2kg",
    imageUrl: "https://placehold.co/400x400/png?text=ACI+Brown+Atta+2kg",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 41,
    brand: "এসিআই পিওর",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি এসিআই পিওর লাল আটা (২ কেজি প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic ACI Pure Whole Wheat Brown Atta (2 kg Packet). Fast delivery guaranteed.",
    displayOrder: 90,
    order: 90
  },
  {
    id: "gr91",
    nameBn: "তীর ময়দা",
    nameEn: "Teer Maida (Refined Flour) (2 kg Packet)",
    price: 140,
    originalPrice: 140,
    unitBn: "২ কেজি প্যাকেট",
    unitEn: "2 kg Packet",
    unit: "২ কেজি প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "আটা, ময়দা ও সুজি",
    subCategory: "আটা, ময়দা ও সুজি",
    image: "https://placehold.co/400x400/png?text=Teer+Maida",
    imageUrl: "https://placehold.co/400x400/png?text=Teer+Maida",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 18,
    brand: "তীর",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি তীর ময়দা (২ কেজি প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Teer Maida (Refined Flour) (2 kg Packet). Fast delivery guaranteed.",
    displayOrder: 91,
    order: 91
  },
  {
    id: "gr92",
    nameBn: "ফ্রেশ ময়দা",
    nameEn: "Fresh Maida (Refined Flour) (2 kg Packet)",
    price: 140,
    originalPrice: 140,
    unitBn: "২ কেজি প্যাকেট",
    unitEn: "2 kg Packet",
    unit: "২ কেজি প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "আটা, ময়দা ও সুজি",
    subCategory: "আটা, ময়দা ও সুজি",
    image: "https://placehold.co/400x400/png?text=Fresh+Maida",
    imageUrl: "https://placehold.co/400x400/png?text=Fresh+Maida",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 25,
    brand: "ফ্রেশ",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি ফ্রেশ ময়দা (২ কেজি প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Fresh Maida (Refined Flour) (2 kg Packet). Fast delivery guaranteed.",
    displayOrder: 92,
    order: 92
  },
  {
    id: "gr93",
    nameBn: "তীর সুজি",
    nameEn: "Teer Semolina (Suji) (500 gm Packet)",
    price: 48,
    originalPrice: 48,
    unitBn: "৫০০ গ্রাম প্যাকেট",
    unitEn: "500 gm Packet",
    unit: "৫০০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "আটা, ময়দা ও সুজি",
    subCategory: "আটা, ময়দা ও সুজি",
    image: "https://placehold.co/400x400/png?text=Teer+Suji",
    imageUrl: "https://placehold.co/400x400/png?text=Teer+Suji",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 32,
    brand: "তীর",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি তীর সুজি (৫০০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Teer Semolina (Suji) (500 gm Packet). Fast delivery guaranteed.",
    displayOrder: 93,
    order: 93
  },
  {
    id: "gr94",
    nameBn: "এসিআই পিওর সুজি",
    nameEn: "ACI Pure Semolina (Suji) (500 gm Packet)",
    price: 48,
    originalPrice: 48,
    unitBn: "৫০০ গ্রাম প্যাকেট",
    unitEn: "500 gm Packet",
    unit: "৫০০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "আটা, ময়দা ও সুজি",
    subCategory: "আটা, ময়দা ও সুজি",
    image: "https://placehold.co/400x400/png?text=ACI+Suji",
    imageUrl: "https://placehold.co/400x400/png?text=ACI+Suji",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 39,
    brand: "এসিআই পিওর",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি এসিআই পিওর সুজি (৫০০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic ACI Pure Semolina (Suji) (500 gm Packet). Fast delivery guaranteed.",
    displayOrder: 94,
    order: 94
  },
  {
    id: "gr95",
    nameBn: "এসিআই পিওর চালের গুঁড়া",
    nameEn: "ACI Pure Rice Flour (500 gm Packet)",
    price: 60,
    originalPrice: 60,
    unitBn: "৫০০ গ্রাম প্যাকেট",
    unitEn: "500 gm Packet",
    unit: "৫০০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "আটা, ময়দা ও সুজি",
    subCategory: "আটা, ময়দা ও সুজি",
    image: "https://placehold.co/400x400/png?text=Rice+Flour",
    imageUrl: "https://placehold.co/400x400/png?text=Rice+Flour",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 16,
    brand: "এসিআই পিওর",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি এসিআই পিওর চালের গুঁড়া (৫০০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic ACI Pure Rice Flour (500 gm Packet). Fast delivery guaranteed.",
    displayOrder: 95,
    order: 95
  },
  {
    id: "gr96",
    nameBn: "প্রাণ বেসন",
    nameEn: "Pran Besan (Gram Flour) (500 gm Packet)",
    price: 65,
    originalPrice: 65,
    unitBn: "৫০০ গ্রাম প্যাকেট",
    unitEn: "500 gm Packet",
    unit: "৫০০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "আটা, ময়দা ও সুজি",
    subCategory: "আটা, ময়দা ও সুজি",
    image: "https://placehold.co/400x400/png?text=Pran+Besan",
    imageUrl: "https://placehold.co/400x400/png?text=Pran+Besan",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 23,
    brand: "প্রাণ",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি প্রাণ বেসন (৫০০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Pran Besan (Gram Flour) (500 gm Packet). Fast delivery guaranteed.",
    displayOrder: 96,
    order: 96
  },
  {
    id: "gr97",
    nameBn: "রাঁধুনী হলুদ গুঁড়া",
    nameEn: "Radhuni Turmeric Powder (100 gm Packet)",
    price: 80,
    originalPrice: 80,
    unitBn: "১০০ গ্রাম প্যাকেট",
    unitEn: "100 gm Packet",
    unit: "১০০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subCategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://placehold.co/400x400/png?text=Radhuni+Turmeric+100g",
    imageUrl: "https://placehold.co/400x400/png?text=Radhuni+Turmeric+100g",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 30,
    brand: "রাঁধুনী",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি রাঁধুনী হলুদ গুঁড়া (১০০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Radhuni Turmeric Powder (100 gm Packet). Fast delivery guaranteed.",
    displayOrder: 97,
    order: 97
  },
  {
    id: "gr98",
    nameBn: "রাঁধুনী হলুদ গুঁড়া",
    nameEn: "Radhuni Turmeric Powder (200 gm Packet)",
    price: 150,
    originalPrice: 150,
    unitBn: "২০০ গ্রাম প্যাকেট",
    unitEn: "200 gm Packet",
    unit: "২০০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subCategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://placehold.co/400x400/png?text=Radhuni+Turmeric+200g",
    imageUrl: "https://placehold.co/400x400/png?text=Radhuni+Turmeric+200g",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 37,
    brand: "রাঁধুনী",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি রাঁধুনী হলুদ গুঁড়া (২০০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Radhuni Turmeric Powder (200 gm Packet). Fast delivery guaranteed.",
    displayOrder: 98,
    order: 98
  },
  {
    id: "gr99",
    nameBn: "ফ্রেশ প্রিমিয়াম হলুদ গুঁড়া",
    nameEn: "Fresh Premium Turmeric Powder (200 gm Packet)",
    price: 145,
    originalPrice: 145,
    unitBn: "২০০ গ্রাম প্যাকেট",
    unitEn: "200 gm Packet",
    unit: "২০০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subCategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://placehold.co/400x400/png?text=Fresh+Turmeric+200g",
    imageUrl: "https://placehold.co/400x400/png?text=Fresh+Turmeric+200g",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 44,
    brand: "ফ্রেশ",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি ফ্রেশ প্রিমিয়াম হলুদ গুঁড়া (২০০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Fresh Premium Turmeric Powder (200 gm Packet). Fast delivery guaranteed.",
    displayOrder: 99,
    order: 99
  },
  {
    id: "gr100",
    nameBn: "রাঁধুনী মরিচ গুঁড়া",
    nameEn: "Radhuni Chili Powder (100 gm Packet)",
    price: 95,
    originalPrice: 95,
    unitBn: "১০০ গ্রাম প্যাকেট",
    unitEn: "100 gm Packet",
    unit: "১০০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subCategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://placehold.co/400x400/png?text=Radhuni+Chili+100g",
    imageUrl: "https://placehold.co/400x400/png?text=Radhuni+Chili+100g",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 21,
    brand: "রাঁধুনী",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি রাঁধুনী মরিচ গুঁড়া (১০০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Radhuni Chili Powder (100 gm Packet). Fast delivery guaranteed.",
    displayOrder: 100,
    order: 100
  },
  {
    id: "gr101",
    nameBn: "রাঁধুনী মরিচ গুঁড়া",
    nameEn: "Radhuni Chili Powder (200 gm Packet)",
    price: 185,
    originalPrice: 185,
    unitBn: "২০০ গ্রাম প্যাকেট",
    unitEn: "200 gm Packet",
    unit: "২০০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subCategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://placehold.co/400x400/png?text=Radhuni+Chili+200g",
    imageUrl: "https://placehold.co/400x400/png?text=Radhuni+Chili+200g",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 28,
    brand: "রাঁধুনী",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি রাঁধুনী মরিচ গুঁড়া (২০০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Radhuni Chili Powder (200 gm Packet). Fast delivery guaranteed.",
    displayOrder: 101,
    order: 101
  },
  {
    id: "gr102",
    nameBn: "এসিআই পিওর মরিচ গুঁড়া",
    nameEn: "ACI Pure Chili Powder (200 gm Packet)",
    price: 185,
    originalPrice: 185,
    unitBn: "২০০ গ্রাম প্যাকেট",
    unitEn: "200 gm Packet",
    unit: "২০০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subCategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://placehold.co/400x400/png?text=ACI+Chili+200g",
    imageUrl: "https://placehold.co/400x400/png?text=ACI+Chili+200g",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 35,
    brand: "এসিআই পিওর",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি এসিআই পিওর মরিচ গুঁড়া (২০০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic ACI Pure Chili Powder (200 gm Packet). Fast delivery guaranteed.",
    displayOrder: 102,
    order: 102
  },
  {
    id: "gr103",
    nameBn: "রাঁধুনী ধনিয়া গুঁড়া",
    nameEn: "Radhuni Coriander Powder (100 gm Packet)",
    price: 60,
    originalPrice: 60,
    unitBn: "১০০ গ্রাম প্যাকেট",
    unitEn: "100 gm Packet",
    unit: "১০০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subCategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://placehold.co/400x400/png?text=Radhuni+Coriander+100g",
    imageUrl: "https://placehold.co/400x400/png?text=Radhuni+Coriander+100g",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 42,
    brand: "রাঁধুনী",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি রাঁধুনী ধনিয়া গুঁড়া (১০০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Radhuni Coriander Powder (100 gm Packet). Fast delivery guaranteed.",
    displayOrder: 103,
    order: 103
  },
  {
    id: "gr104",
    nameBn: "রাঁধুনী ধনিয়া গুঁড়া",
    nameEn: "Radhuni Coriander Powder (200 gm Packet)",
    price: 115,
    originalPrice: 115,
    unitBn: "২০০ গ্রাম প্যাকেট",
    unitEn: "200 gm Packet",
    unit: "২০০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subCategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://placehold.co/400x400/png?text=Radhuni+Coriander+200g",
    imageUrl: "https://placehold.co/400x400/png?text=Radhuni+Coriander+200g",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 19,
    brand: "রাঁধুনী",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি রাঁধুনী ধনিয়া গুঁড়া (২০০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Radhuni Coriander Powder (200 gm Packet). Fast delivery guaranteed.",
    displayOrder: 104,
    order: 104
  },
  {
    id: "gr105",
    nameBn: "রাঁধুনী জিরা গুঁড়া",
    nameEn: "Radhuni Cumin Powder (100 gm Packet)",
    price: 165,
    originalPrice: 165,
    unitBn: "১০০ গ্রাম প্যাকেট",
    unitEn: "100 gm Packet",
    unit: "১০০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subCategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://placehold.co/400x400/png?text=Radhuni+Cumin+100g",
    imageUrl: "https://placehold.co/400x400/png?text=Radhuni+Cumin+100g",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 26,
    brand: "রাঁধুনী",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি রাঁধুনী জিরা গুঁড়া (১০০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Radhuni Cumin Powder (100 gm Packet). Fast delivery guaranteed.",
    displayOrder: 105,
    order: 105
  },
  {
    id: "gr106",
    nameBn: "এসিআই পিওর জিরা গুঁড়া",
    nameEn: "ACI Pure Cumin Powder (100 gm Packet)",
    price: 155,
    originalPrice: 155,
    unitBn: "১০০ গ্রাম প্যাকেট",
    unitEn: "100 gm Packet",
    unit: "১০০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subCategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://placehold.co/400x400/png?text=ACI+Cumin+100g",
    imageUrl: "https://placehold.co/400x400/png?text=ACI+Cumin+100g",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 33,
    brand: "এসিআই পিওর",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি এসিআই পিওর জিরা গুঁড়া (১০০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic ACI Pure Cumin Powder (100 gm Packet). Fast delivery guaranteed.",
    displayOrder: 106,
    order: 106
  },
  {
    id: "gr107",
    nameBn: "রাঁধুনী গরম মসলা গুঁড়া",
    nameEn: "Radhuni Garam Masala Powder (50 gm Packet)",
    price: 115,
    originalPrice: 115,
    unitBn: "৫০ গ্রাম প্যাকেট",
    unitEn: "50 gm Packet",
    unit: "৫০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subCategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://placehold.co/400x400/png?text=Garam+Masala+50g",
    imageUrl: "https://placehold.co/400x400/png?text=Garam+Masala+50g",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 40,
    brand: "রাঁধুনী",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি রাঁধুনী গরম মসলা গুঁড়া (৫০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Radhuni Garam Masala Powder (50 gm Packet). Fast delivery guaranteed.",
    displayOrder: 107,
    order: 107
  },
  {
    id: "gr108",
    nameBn: "রাঁধুনী গোলমরিচ গুঁড়া",
    nameEn: "Radhuni Black Pepper Powder (50 gm Packet)",
    price: 115,
    originalPrice: 115,
    unitBn: "৫০ গ্রাম প্যাকেট",
    unitEn: "50 gm Packet",
    unit: "৫০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subCategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://placehold.co/400x400/png?text=Black+Pepper+50g",
    imageUrl: "https://placehold.co/400x400/png?text=Black+Pepper+50g",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 17,
    brand: "রাঁধুনী",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি রাঁধুনী গোলমরিচ গুঁড়া (৫০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Radhuni Black Pepper Powder (50 gm Packet). Fast delivery guaranteed.",
    displayOrder: 108,
    order: 108
  },
  {
    id: "gr109",
    nameBn: "রাঁধুনী বিরিয়ানি মসলা",
    nameEn: "Radhuni Biryani Masala (40 gm Packet)",
    price: 60,
    originalPrice: 60,
    unitBn: "৪০ গ্রাম প্যাকেট",
    unitEn: "40 gm Packet",
    unit: "৪০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং উপাদান",
    subCategory: "রেডি মসলা ও বেকিং উপাদান",
    image: "https://placehold.co/400x400/png?text=Radhuni+Biryani",
    imageUrl: "https://placehold.co/400x400/png?text=Radhuni+Biryani",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 24,
    brand: "রাঁধুনী",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি রাঁধুনী বিরিয়ানি মসলা (৪০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Radhuni Biryani Masala (40 gm Packet). Fast delivery guaranteed.",
    displayOrder: 109,
    order: 109
  },
  {
    id: "gr110",
    nameBn: "শান বিরিয়ানি মসলা",
    nameEn: "Shan Biryani Masala (50 gm Packet)",
    price: 125,
    originalPrice: 125,
    unitBn: "৫০ গ্রাম প্যাকেট",
    unitEn: "50 gm Packet",
    unit: "৫০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং উপাদান",
    subCategory: "রেডি মসলা ও বেকিং উপাদান",
    image: "https://placehold.co/400x400/png?text=Shan+Biryani",
    imageUrl: "https://placehold.co/400x400/png?text=Shan+Biryani",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 31,
    brand: "শান",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি শান বিরিয়ানি মসলা (৫০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Shan Biryani Masala (50 gm Packet). Fast delivery guaranteed.",
    displayOrder: 110,
    order: 110
  },
  {
    id: "gr111",
    nameBn: "রাঁধুনী চিকেন রোস্ট মসলা",
    nameEn: "Radhuni Chicken Roast Masala (35 gm Packet)",
    price: 52,
    originalPrice: 52,
    unitBn: "৩৫ গ্রাম প্যাকেট",
    unitEn: "35 gm Packet",
    unit: "৩৫ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং উপাদান",
    subCategory: "রেডি মসলা ও বেকিং উপাদান",
    image: "https://placehold.co/400x400/png?text=Radhuni+Roast",
    imageUrl: "https://placehold.co/400x400/png?text=Radhuni+Roast",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 38,
    brand: "রাঁধুনী",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি রাঁধুনী চিকেন রোস্ট মসলা (৩৫ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Radhuni Chicken Roast Masala (35 gm Packet). Fast delivery guaranteed.",
    displayOrder: 111,
    order: 111
  },
  {
    id: "gr112",
    nameBn: "রাঁধুনী চটপটি মসলা",
    nameEn: "Radhuni Chotpoti Masala (50 gm Packet)",
    price: 42,
    originalPrice: 42,
    unitBn: "৫০ গ্রাম প্যাকেট",
    unitEn: "50 gm Packet",
    unit: "৫০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং উপাদান",
    subCategory: "রেডি মসলা ও বেকিং উপাদান",
    image: "https://placehold.co/400x400/png?text=Radhuni+Chotpoti",
    imageUrl: "https://placehold.co/400x400/png?text=Radhuni+Chotpoti",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 15,
    brand: "রাঁধুনী",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি রাঁধুনী চটপটি মসলা (৫০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Radhuni Chotpoti Masala (50 gm Packet). Fast delivery guaranteed.",
    displayOrder: 112,
    order: 112
  },
  {
    id: "gr113",
    nameBn: "রাঁধুনী চাট মসলা",
    nameEn: "Radhuni Chaat Masala (50 gm Packet)",
    price: 42,
    originalPrice: 42,
    unitBn: "৫০ গ্রাম প্যাকেট",
    unitEn: "50 gm Packet",
    unit: "৫০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং উপাদান",
    subCategory: "রেডি মসলা ও বেকিং উপাদান",
    image: "https://placehold.co/400x400/png?text=Radhuni+Chaat",
    imageUrl: "https://placehold.co/400x400/png?text=Radhuni+Chaat",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 22,
    brand: "রাঁধুনী",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি রাঁধুনী চাট মসলা (৫০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Radhuni Chaat Masala (50 gm Packet). Fast delivery guaranteed.",
    displayOrder: 113,
    order: 113
  },
  {
    id: "gr114",
    nameBn: "বাঘাবাড়ী স্পেশাল গাওয়া ঘি",
    nameEn: "Baghabari Special Pure Ghee (200 gm Glass Jar)",
    price: 340,
    originalPrice: 340,
    unitBn: "২০০ গ্রাম কাঁচের জার",
    unitEn: "200 gm Glass Jar",
    unit: "২০০ গ্রাম কাঁচের জার",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং উপাদান",
    subCategory: "রেডি মসলা ও বেকিং উপাদান",
    image: "https://placehold.co/400x400/png?text=Baghabari+Ghee+200g",
    imageUrl: "https://placehold.co/400x400/png?text=Baghabari+Ghee+200g",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 29,
    brand: "বাঘাবাড়ী",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি বাঘাবাড়ী স্পেশাল গাওয়া ঘি (২০০ গ্রাম কাঁচের জার)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Baghabari Special Pure Ghee (200 gm Glass Jar). Fast delivery guaranteed.",
    displayOrder: 114,
    order: 114
  },
  {
    id: "gr115",
    nameBn: "বাঘাবাড়ী স্পেশাল গাওয়া ঘি",
    nameEn: "Baghabari Special Pure Ghee (400 gm Glass Jar)",
    price: 660,
    originalPrice: 660,
    unitBn: "৪০০ গ্রাম কাঁচের জার",
    unitEn: "400 gm Glass Jar",
    unit: "৪০০ গ্রাম কাঁচের জার",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং উপাদান",
    subCategory: "রেডি মসলা ও বেকিং উপাদান",
    image: "https://placehold.co/400x400/png?text=Baghabari+Ghee+400g",
    imageUrl: "https://placehold.co/400x400/png?text=Baghabari+Ghee+400g",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 36,
    brand: "বাঘাবাড়ী",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি বাঘাবাড়ী স্পেশাল গাওয়া ঘি (৪০০ গ্রাম কাঁচের জার)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Baghabari Special Pure Ghee (400 gm Glass Jar). Fast delivery guaranteed.",
    displayOrder: 115,
    order: 115
  },
  {
    id: "gr116",
    nameBn: "প্রাণ প্রিমিয়াম গাওয়া ঘি",
    nameEn: "Pran Premium Pure Ghee (400 gm Jar)",
    price: 640,
    originalPrice: 640,
    unitBn: "৪০০ গ্রাম জার",
    unitEn: "400 gm Jar",
    unit: "৪০০ গ্রাম জার",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং উপাদান",
    subCategory: "রেডি মসলা ও বেকিং উপাদান",
    image: "https://placehold.co/400x400/png?text=Pran+Ghee+400g",
    imageUrl: "https://placehold.co/400x400/png?text=Pran+Ghee+400g",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 43,
    brand: "প্রাণ",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি প্রাণ প্রিমিয়াম গাওয়া ঘি (৪০০ গ্রাম জার)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Pran Premium Pure Ghee (400 gm Jar). Fast delivery guaranteed.",
    displayOrder: 116,
    order: 116
  },
  {
    id: "gr117",
    nameBn: "মিল্ক ভিটা গাওয়া ঘি",
    nameEn: "Milkvita Pure Ghee (400 gm Jar)",
    price: 660,
    originalPrice: 660,
    unitBn: "৪০০ গ্রাম জার",
    unitEn: "400 gm Jar",
    unit: "৪০০ গ্রাম জার",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং উপাদান",
    subCategory: "রেডি মসলা ও বেকিং উপাদান",
    image: "https://placehold.co/400x400/png?text=Milkvita+Ghee",
    imageUrl: "https://placehold.co/400x400/png?text=Milkvita+Ghee",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 20,
    brand: "মিল্ক ভিটা",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি মিল্ক ভিটা গাওয়া ঘি (৪০০ গ্রাম জার)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Milkvita Pure Ghee (400 gm Jar). Fast delivery guaranteed.",
    displayOrder: 117,
    order: 117
  },
  {
    id: "gr118",
    nameBn: "আড়ং ডেইরি বাটার",
    nameEn: "Aarong Dairy Butter (100 gm Pack)",
    price: 115,
    originalPrice: 115,
    unitBn: "১০০ গ্রাম প্যাক",
    unitEn: "100 gm Pack",
    unit: "১০০ গ্রাম প্যাক",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং উপাদান",
    subCategory: "রেডি মসলা ও বেকিং উপাদান",
    image: "https://placehold.co/400x400/png?text=Aarong+Butter+100g",
    imageUrl: "https://placehold.co/400x400/png?text=Aarong+Butter+100g",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 27,
    brand: "আড়ং ডেইরি",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি আড়ং ডেইরি বাটার (১০০ গ্রাম প্যাক)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Aarong Dairy Butter (100 gm Pack). Fast delivery guaranteed.",
    displayOrder: 118,
    order: 118
  },
  {
    id: "gr119",
    nameBn: "আড়ং ডেইরি বাটার",
    nameEn: "Aarong Dairy Butter (200 gm Pack)",
    price: 220,
    originalPrice: 220,
    unitBn: "২০০ গ্রাম প্যাক",
    unitEn: "200 gm Pack",
    unit: "২০০ গ্রাম প্যাক",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং উপাদান",
    subCategory: "রেডি মসলা ও বেকিং উপাদান",
    image: "https://placehold.co/400x400/png?text=Aarong+Butter+200g",
    imageUrl: "https://placehold.co/400x400/png?text=Aarong+Butter+200g",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 34,
    brand: "আড়ং ডেইরি",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি আড়ং ডেইরি বাটার (২০০ গ্রাম প্যাক)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Aarong Dairy Butter (200 gm Pack). Fast delivery guaranteed.",
    displayOrder: 119,
    order: 119
  },
  {
    id: "gr120",
    nameBn: "তীর ভেজিটেবল ডালডা",
    nameEn: "Teer Vegetable Dalda (500 gm Packet)",
    price: 125,
    originalPrice: 125,
    unitBn: "৫০০ গ্রাম প্যাকেট",
    unitEn: "500 gm Packet",
    unit: "৫০০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং উপাদান",
    subCategory: "রেডি মসলা ও বেকিং উপাদান",
    image: "https://placehold.co/400x400/png?text=Teer+Dalda",
    imageUrl: "https://placehold.co/400x400/png?text=Teer+Dalda",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 41,
    brand: "তীর",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি তীর ভেজিটেবল ডালডা (৫০০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Teer Vegetable Dalda (500 gm Packet). Fast delivery guaranteed.",
    displayOrder: 120,
    order: 120
  },
  {
    id: "gr121",
    nameBn: "ফস্টার ক্লার্কস বেকিং পাউডার",
    nameEn: "Foster Clarks Baking Powder (100 gm Can)",
    price: 125,
    originalPrice: 125,
    unitBn: "১০০ গ্রাম কৌটো",
    unitEn: "100 gm Can",
    unit: "১০০ গ্রাম কৌটো",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং উপাদান",
    subCategory: "রেডি মসলা ও বেকিং উপাদান",
    image: "https://placehold.co/400x400/png?text=Foster+Clarks+Baking",
    imageUrl: "https://placehold.co/400x400/png?text=Foster+Clarks+Baking",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 18,
    brand: "ফস্টার ক্লার্কস",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি ফস্টার ক্লার্কস বেকিং পাউডার (১০০ গ্রাম কৌটো)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Foster Clarks Baking Powder (100 gm Can). Fast delivery guaranteed.",
    displayOrder: 121,
    order: 121
  },
  {
    id: "gr122",
    nameBn: "আহমেদ বেকিং সোডা",
    nameEn: "Ahmed Baking Soda (100 gm Packet)",
    price: 35,
    originalPrice: 35,
    unitBn: "১০০ গ্রাম প্যাকেট",
    unitEn: "100 gm Packet",
    unit: "১০০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং উপাদান",
    subCategory: "রেডি মসলা ও বেকিং উপাদান",
    image: "https://placehold.co/400x400/png?text=Ahmed+Baking+Soda",
    imageUrl: "https://placehold.co/400x400/png?text=Ahmed+Baking+Soda",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 25,
    brand: "আহমেদ",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি আহমেদ বেকিং সোডা (১০০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Ahmed Baking Soda (100 gm Packet). Fast delivery guaranteed.",
    displayOrder: 122,
    order: 122
  },
  {
    id: "gr123",
    nameBn: "আহমেদ সাদা ভিনেগার",
    nameEn: "Ahmed White Vinegar (650 ml Bottle)",
    price: 65,
    originalPrice: 65,
    unitBn: "৬৫০ মিলি বোতল",
    unitEn: "650 ml Bottle",
    unit: "৬৫০ মিলি বোতল",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং উপাদান",
    subCategory: "রেডি মসলা ও বেকিং উপাদান",
    image: "https://placehold.co/400x400/png?text=White+Vinegar",
    imageUrl: "https://placehold.co/400x400/png?text=White+Vinegar",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 32,
    brand: "আহমেদ",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি আহমেদ সাদা ভিনেগার (৬৫০ মিলি বোতল)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Ahmed White Vinegar (650 ml Bottle). Fast delivery guaranteed.",
    displayOrder: 123,
    order: 123
  },
  {
    id: "gr124",
    nameBn: "ডাঙ্গো ইস্ট পাউডার",
    nameEn: "Dango Yeast Powder (50 gm Packet)",
    price: 55,
    originalPrice: 55,
    unitBn: "৫০ গ্রাম প্যাকেট",
    unitEn: "50 gm Packet",
    unit: "৫০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং উপাদান",
    subCategory: "রেডি মসলা ও বেকিং উপাদান",
    image: "https://placehold.co/400x400/png?text=Dango+Yeast",
    imageUrl: "https://placehold.co/400x400/png?text=Dango+Yeast",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 39,
    brand: "ডাঙ্গো",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি ডাঙ্গো ইস্ট পাউডার (৫০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Dango Yeast Powder (50 gm Packet). Fast delivery guaranteed.",
    displayOrder: 124,
    order: 124
  },
  {
    id: "gr125",
    nameBn: "ব্লু বার্ড কর্নফ্লাওয়ার",
    nameEn: "Blue Bird Corn Flour (100 gm Packet)",
    price: 52,
    originalPrice: 52,
    unitBn: "১০০ গ্রাম প্যাকেট",
    unitEn: "100 gm Packet",
    unit: "১০০ গ্রাম প্যাকেট",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং উপাদান",
    subCategory: "রেডি মসলা ও বেকিং উপাদান",
    image: "https://placehold.co/400x400/png?text=Corn+Flour",
    imageUrl: "https://placehold.co/400x400/png?text=Corn+Flour",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 16,
    brand: "ব্লু বার্ড",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি ব্লু বার্ড কর্নফ্লাওয়ার (১০০ গ্রাম প্যাকেট)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Blue Bird Corn Flour (100 gm Packet). Fast delivery guaranteed.",
    displayOrder: 125,
    order: 125
  },
  {
    id: "gr126",
    nameBn: "ফস্টার ক্লার্কস কাস্টার্ড পাউডার",
    nameEn: "Foster Clarks Custard Powder (300 gm Can)",
    price: 180,
    originalPrice: 180,
    unitBn: "৩০০ গ্রাম কৌটো",
    unitEn: "300 gm Can",
    unit: "৩০০ গ্রাম কৌটো",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং উপাদান",
    subCategory: "রেডি মসলা ও বেকিং উপাদান",
    image: "https://placehold.co/400x400/png?text=Custard+Powder",
    imageUrl: "https://placehold.co/400x400/png?text=Custard+Powder",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 23,
    brand: "ফস্টার ক্লার্কস",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি ও ১০০% খাঁটি ফস্টার ক্লার্কস কাস্টার্ড পাউডার (৩০০ গ্রাম কৌটো)। কাঁচা বাজার থেকে দ্রুত ডেলিভারি।",
    descriptionEn: "Premium quality 100% authentic Foster Clarks Custard Powder (300 gm Can). Fast delivery guaranteed.",
    displayOrder: 126,
    order: 126
  }
];
