import { Product } from "../types";

// Raw pharmacy medicine catalog based strictly on official Medicine Price Sheet (132 items)
// No prices specified per user request
const RAW_MEDICINE_ITEMS = [
  // Page 1 - Healthcare (1-21)
  { id: "ph1", name: "Alcet Tablet 5mg", brand: "Healthcare", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph2", name: "Candiril Capsule 150mg", brand: "Healthcare", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph3", name: "Clonatril Tablet 1mg", brand: "Healthcare", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph4", name: "Furotil Tablet 500mg", brand: "Healthcare", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph5", name: "Halonate Ointment 20g", brand: "Healthcare", unitBn: "১ টিউব", unitEn: "1 tube" },
  { id: "ph6", name: "Lyric Capsule 25mg", brand: "Healthcare", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph7", name: "Lyric Capsule 50mg", brand: "Healthcare", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph8", name: "Moxivin Eye drop 5ml (0.5% w/v)", brand: "Healthcare", unitBn: "১ বোতল", unitEn: "1 bottle" },
  { id: "ph9", name: "NFT Capsule 100 mg", brand: "Healthcare", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph10", name: "Novea Tablet 20 mg", brand: "Healthcare", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph11", name: "Reef-DX Tablet", brand: "Healthcare", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph12", name: "Renovit Tablet", brand: "Healthcare", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph13", name: "Replet Plus Tablet", brand: "Healthcare", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph14", name: "Rocal-M Vita Effervescent Tablet", brand: "Healthcare", unitBn: "১ টিউব", unitEn: "1 tube" },
  { id: "ph15", name: "Rozith Tablet 500mg", brand: "Healthcare", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph16", name: "Santogen Tablet", brand: "Healthcare", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph17", name: "SERGEL CAPSULE 20MG", brand: "Healthcare", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph18", name: "SERGEL CAPSULE 40MG", brand: "Healthcare", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph19", name: "Sizonil Tablet 1mg", brand: "Healthcare", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph20", name: "Solivo Tablet 375mg", brand: "Healthcare", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph21", name: "Teana AM Tablet 80/5mg", brand: "Healthcare", unitBn: "১ পিস", unitEn: "1 pc" },

  // Page 1 - Square Pharma (22-44)
  { id: "ph22", name: "Afun Crm 10g", brand: "Square Pharma", unitBn: "১ টিউব", unitEn: "1 tube" },
  { id: "ph23", name: "Alifane Cap 30's", brand: "Square Pharma", unitBn: "৩০ টি ক্যাপসুল", unitEn: "30 capsules" },
  { id: "ph24", name: "Almex 400 Tab 48's", brand: "Square Pharma", unitBn: "৪৮ টি ট্যাবলেট", unitEn: "48 tablets" },
  { id: "ph25", name: "Bactrocin 2% Oint 10g", brand: "Square Pharma", unitBn: "১ টিউব", unitEn: "1 tube" },
  { id: "ph26", name: "Betameson Crm 20g", brand: "Square Pharma", unitBn: "১ টিউব", unitEn: "1 tube" },
  { id: "ph27", name: "Betameson-N Crm 15g", brand: "Square Pharma", unitBn: "১ টিউব", unitEn: "1 tube" },
  { id: "ph28", name: "Butocort 200 Cozycap 30's", brand: "Square Pharma", unitBn: "৩০ টি কোজিক্যাপ", unitEn: "30 cozycaps" },
  { id: "ph29", name: "Camlosart 5/20 Tab 30's", brand: "Square Pharma", unitBn: "৩০ টি ট্যাবলেট", unitEn: "30 tablets" },
  { id: "ph30", name: "Cefotil 500 Tab 12's", brand: "Square Pharma", unitBn: "১২ টি ট্যাবলেট", unitEn: "12 tablets" },
  { id: "ph31", name: "Cefotil Plus 250 Tab 12's", brand: "Square Pharma", unitBn: "১২ টি ট্যাবলেট", unitEn: "12 tablets" },
  { id: "ph32", name: "Ceftron 1g IV Inj", brand: "Square Pharma", unitBn: "১ ভায়াল", unitEn: "1 vial" },
  { id: "ph33", name: "Clotenac Gel 20g", brand: "Square Pharma", unitBn: "১ টিউব", unitEn: "1 tube" },
  { id: "ph34", name: "Comet 500 Tab 100's", brand: "Square Pharma", unitBn: "১০০ টি ট্যাবলেট", unitEn: "100 tablets" },
  { id: "ph35", name: "Comet XR 500 Tab 50's", brand: "Square Pharma", unitBn: "৫০ টি ট্যাবলেট", unitEn: "50 tablets" },
  { id: "ph36", name: "Comprid 80 Tab 60's", brand: "Square Pharma", unitBn: "৬০ টি ট্যাবলেট", unitEn: "60 tablets" },
  { id: "ph37", name: "Contilex TS Tab 20's", brand: "Square Pharma", unitBn: "২০ টি ট্যাবলেট", unitEn: "20 tablets" },
  { id: "ph38", name: "Cozycol 800 Tab 30's", brand: "Square Pharma", unitBn: "৩০ টি ট্যাবলেট", unitEn: "30 tablets" },
  { id: "ph39", name: "D-Balance 40000 Licap 10's", brand: "Square Pharma", unitBn: "১০ টি লিক্যাপ", unitEn: "10 licaps" },
  { id: "ph40", name: "Epitra 0.5 Tab 50's", brand: "Square Pharma", unitBn: "৫০ টি ট্যাবলেট", unitEn: "50 tablets" },
  { id: "ph41", name: "Famotack 20 Tab 180's", brand: "Square Pharma", unitBn: "১৮০ টি ট্যাবলেট", unitEn: "180 tablets" },
  { id: "ph42", name: "Feoza 45 Tab 20's", brand: "Square Pharma", unitBn: "২০ টি ট্যাবলেট", unitEn: "20 tablets" },
  { id: "ph43", name: "Fexo 120 Tab 50's", brand: "Square Pharma", unitBn: "৫০ টি ট্যাবলেট", unitEn: "50 tablets" },
  { id: "ph44", name: "Flexi 200 SR-Tab 30's", brand: "Square Pharma", unitBn: "৩০ টি ট্যাবলেট", unitEn: "30 tablets" },

  // Page 2 - Square Pharma (45-83)
  { id: "ph45", name: "Fungidal Crm 15g", brand: "Square Pharma", unitBn: "১ টিউব", unitEn: "1 tube" },
  { id: "ph46", name: "Fungidal-HC Crm 15g T", brand: "Square Pharma", unitBn: "১ টিউব", unitEn: "1 tube" },
  { id: "ph47", name: "Glysup 1.15 Supp 30's", brand: "Square Pharma", unitBn: "৩০ টি সাপোজিটরি", unitEn: "30 suppositories" },
  { id: "ph48", name: "Ispergud Sachet 15's", brand: "Square Pharma", unitBn: "১৫ টি স্যাচেট", unitEn: "15 sachets" },
  { id: "ph49", name: "Iventi Tab 12's", brand: "Square Pharma", unitBn: "১২ টি ট্যাবলেট", unitEn: "12 tablets" },
  { id: "ph50", name: "K-One MM Inj 6's", brand: "Square Pharma", unitBn: "৬ টি ইনজেকশন", unitEn: "6 injections" },
  { id: "ph51", name: "Lanso D 30 Cap 60's", brand: "Square Pharma", unitBn: "৬০ টি ক্যাপসুল", unitEn: "60 capsules" },
  { id: "ph52", name: "Lubgel 1% E-Drop 10ml", brand: "Square Pharma", unitBn: "১ বোতল (১০ মিলি)", unitEn: "1 bottle (10ml)" },
  { id: "ph53", name: "Maxrin 0.4 Cap 30's", brand: "Square Pharma", unitBn: "৩০ টি ক্যাপসুল", unitEn: "30 capsules" },
  { id: "ph54", name: "Metaspray N-Spray 120sprays", brand: "Square Pharma", unitBn: "১ স্প্রে", unitEn: "1 spray" },
  { id: "ph55", name: "Methigic 8 Tab 30's", brand: "Square Pharma", unitBn: "৩০ টি ট্যাবলেট", unitEn: "30 tablets" },
  { id: "ph56", name: "Migranil 1.5 Tab 30's", brand: "Square Pharma", unitBn: "৩০ টি ট্যাবলেট", unitEn: "30 tablets" },
  { id: "ph57", name: "Mirapro 15 Tab 30's", brand: "Square Pharma", unitBn: "৩০ টি ট্যাবলেট", unitEn: "30 tablets" },
  { id: "ph58", name: "Montene 10 Tab 30's", brand: "Square Pharma", unitBn: "৩০ টি ট্যাবলেট", unitEn: "30 tablets" },
  { id: "ph59", name: "Motigut Tab 100's", brand: "Square Pharma", unitBn: "১০০ টি ট্যাবলেট", unitEn: "100 tablets" },
  { id: "ph60", name: "Moxaclav 1g Tab 12's", brand: "Square Pharma", unitBn: "১২ টি ট্যাবলেট", unitEn: "12 tablets" },
  { id: "ph61", name: "Moxaclav 625 Tab 30's", brand: "Square Pharma", unitBn: "৩০ টি ট্যাবলেট", unitEn: "30 tablets" },
  { id: "ph62", name: "Neumig 2.5 Tab 20's", brand: "Square Pharma", unitBn: "২০ টি ট্যাবলেট", unitEn: "20 tablets" },
  { id: "ph63", name: "Neurolin 25 Cap 30's", brand: "Square Pharma", unitBn: "৩০ টি ক্যাপসুল", unitEn: "30 capsules" },
  { id: "ph64", name: "Nexum 40 Cap 30's", brand: "Square Pharma", unitBn: "৩০ টি ক্যাপসুল", unitEn: "30 capsules" },
  { id: "ph65", name: "Nexum MUPS 20 Tab 100's", brand: "Square Pharma", unitBn: "১০০ টি ট্যাবলেট", unitEn: "100 tablets" },
  { id: "ph66", name: "Oxifun Crm 10g", brand: "Square Pharma", unitBn: "১ টিউব", unitEn: "1 tube" },
  { id: "ph67", name: "Oxifun Lotion 30ml", brand: "Square Pharma", unitBn: "১ বোতল", unitEn: "1 bottle" },
  { id: "ph68", name: "Pevitin Crm 15g", brand: "Square Pharma", unitBn: "১ টিউব", unitEn: "1 tube" },
  { id: "ph69", name: "Phylopen DS Cap 42's", brand: "Square Pharma", unitBn: "৪২ টি ক্যাপসুল", unitEn: "42 capsules" },
  { id: "ph70", name: "QTP 100 Tab 30's", brand: "Square Pharma", unitBn: "৩০ টি ট্যাবলেট", unitEn: "30 tablets" },
  { id: "ph71", name: "QTP 25 Tab 30's", brand: "Square Pharma", unitBn: "৩০ টি ট্যাবলেট", unitEn: "30 tablets" },
  { id: "ph72", name: "QTP 50 XR Tab 30's", brand: "Square Pharma", unitBn: "৩০ টি ট্যাবলেট", unitEn: "30 tablets" },
  { id: "ph73", name: "Ranolin 500 XR Tab 20's", brand: "Square Pharma", unitBn: "২০ টি ট্যাবলেট", unitEn: "20 tablets" },
  { id: "ph74", name: "Rapimix Inj 3ml 1's", brand: "Square Pharma", unitBn: "১ টি ইনজেকশন", unitEn: "1 injection" },
  { id: "ph75", name: "Rivatig 1.5 Cap 20's", brand: "Square Pharma", unitBn: "২০ টি ক্যাপসুল", unitEn: "20 capsules" },
  { id: "ph76", name: "Seclo 20 Cap 120's", brand: "Square Pharma", unitBn: "১২০ টি ক্যাপসুল", unitEn: "120 capsules" },
  { id: "ph77", name: "Secrin 4 Tab 30's", brand: "Square Pharma", unitBn: "৩০ টি ট্যাবলেট", unitEn: "30 tablets" },
  { id: "ph78", name: "Sitamax 50 Tab 10's", brand: "Square Pharma", unitBn: "১০ টি ট্যাবলেট", unitEn: "10 tablets" },
  { id: "ph79", name: "Sulprex HFA Refill 200puff", brand: "Square Pharma", unitBn: "১ রিফিল ক্যান", unitEn: "1 refill can" },
  { id: "ph80", name: "Sulprex Nebu Soln 3ml 10's", brand: "Square Pharma", unitBn: "১০ টি রেসপ্যুল", unitEn: "10 respules" },
  { id: "ph81", name: "Telmilock AM 5/80 Tab 30's", brand: "Square Pharma", unitBn: "৩০ টি ট্যাবলেট", unitEn: "30 tablets" },
  { id: "ph82", name: "Ticamet 250 HFA MDI 120puff", brand: "Square Pharma", unitBn: "১ ইনহেলার", unitEn: "1 inhaler" },
  { id: "ph83", name: "Ticamet 250 HFA Refill 120puff", brand: "Square Pharma", unitBn: "১ রিফিল ক্যান", unitEn: "1 refill can" },

  // Page 2 & 3 - Beximco Pharma (84-108)
  { id: "ph84", name: "Bextram Gold Tablet", brand: "Beximco Pharma", unitBn: "১ বোতল / প্যাক", unitEn: "1 pack" },
  { id: "ph85", name: "Bextram Silver Tablet", brand: "Beximco Pharma", unitBn: "১ বোতল / প্যাক", unitEn: "1 pack" },
  { id: "ph86", name: "Bizoran Tablet", brand: "Beximco Pharma", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph87", name: "D-Rise 2000 IU Oral Sol.", brand: "Beximco Pharma", unitBn: "১ বোতল", unitEn: "1 bottle" },
  { id: "ph88", name: "Digecid Suspension", brand: "Beximco Pharma", unitBn: "১ বোতল", unitEn: "1 bottle" },
  { id: "ph89", name: "Evo 500 Tablet-30's", brand: "Beximco Pharma", unitBn: "৩০ টি ট্যাবলেট", unitEn: "30 tablets" },
  { id: "ph90", name: "Empalina 25/5 Tablet", brand: "Beximco Pharma", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph91", name: "Fixolin 200 Tablet", brand: "Beximco Pharma", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph92", name: "Iprasol HFA Inhaler Refill", brand: "Beximco Pharma", unitBn: "১ রিফিল ক্যান", unitEn: "1 refill can" },
  { id: "ph93", name: "Informet XR 500 Tablet", brand: "Beximco Pharma", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph94", name: "Napa One Tablet", brand: "Beximco Pharma", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph95", name: "Napa Syp", brand: "Beximco Pharma", unitBn: "১ বোতল", unitEn: "1 bottle" },
  { id: "ph96", name: "Napa Tablet (510's)", brand: "Beximco Pharma", unitBn: "৫১০ টি ট্যাবলেট (বক্স)", unitEn: "510 tablets" },
  { id: "ph97", name: "Neurocare", brand: "Beximco Pharma", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph98", name: "Napa Extra Tablet", brand: "Beximco Pharma", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph99", name: "Nervalin 25 Cap", brand: "Beximco Pharma", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph100", name: "Napa Extend Tablet-192's", brand: "Beximco Pharma", unitBn: "১৯২ টি ট্যাবলেট (বক্স)", unitEn: "192 tablets" },
  { id: "ph101", name: "Olmesan-20 Tablet", brand: "Beximco Pharma", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph102", name: "Remmo 20 Tablet", brand: "Beximco Pharma", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph103", name: "Rostil SR Cap", brand: "Beximco Pharma", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph104", name: "Terbex Cream (5G)", brand: "Beximco Pharma", unitBn: "১ টিউব", unitEn: "1 tube" },
  { id: "ph105", name: "Tyclav 625 mg Tablet", brand: "Beximco Pharma", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph106", name: "Tearon Eye Drops", brand: "Beximco Pharma", unitBn: "১ বোতল", unitEn: "1 bottle" },
  { id: "ph107", name: "Vonocab 20 Tablet", brand: "Beximco Pharma", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph108", name: "Zolax 0.25 Tablet", brand: "Beximco Pharma", unitBn: "১ পিস", unitEn: "1 pc" },

  // Page 3 - Renata PLC (109-121)
  { id: "ph109", name: "ALGIN 50MG TABS 10X10'S", brand: "Renata PLC", unitBn: "১০০ টি ট্যাবলেট (বক্স)", unitEn: "100 tablets" },
  { id: "ph110", name: "ALPHAPRESS XR 2.5MG 3X10'S", brand: "Renata PLC", unitBn: "৩০ টি ট্যাবলেট (বক্স)", unitEn: "30 tablets" },
  { id: "ph111", name: "ESCILEX FC 5MG TAB 4X10'S", brand: "Renata PLC", unitBn: "৪০ টি ট্যাবলেট (বক্স)", unitEn: "40 tablets" },
  { id: "ph112", name: "FUROCEF 250MG TAB (2X8'S)", brand: "Renata PLC", unitBn: "১৬ টি ট্যাবলেট (বক্স)", unitEn: "16 tablets" },
  { id: "ph113", name: "GLINTA PLUS FC 10/5MG TABS", brand: "Renata PLC", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph114", name: "NORMENS 5MG TAB 10X10'S", brand: "Renata PLC", unitBn: "১০০ টি ট্যাবলেট (বক্স)", unitEn: "100 tablets" },
  { id: "ph115", name: "SERONEX 100MG TAB 3X10'S", brand: "Renata PLC", unitBn: "৩০ টি ট্যাবলেট (বক্স)", unitEn: "30 tablets" },
  { id: "ph116", name: "SERONEX 25MG TAB 5X10'S", brand: "Renata PLC", unitBn: "৫০ টি ট্যাবলেট (বক্স)", unitEn: "50 tablets" },
  { id: "ph117", name: "THYROX 100MCG TAB 60X1'S", brand: "Renata PLC", unitBn: "৬০ টি ট্যাবলেট (বক্স)", unitEn: "60 tablets" },
  { id: "ph118", name: "THYROX 25MCG TAB 3X30'S", brand: "Renata PLC", unitBn: "৯০ টি ট্যাবলেট (বক্স)", unitEn: "90 tablets" },
  { id: "ph119", name: "ULFIX 200ML SUSP 1X1'S", brand: "Renata PLC", unitBn: "১ বোতল (২০০ মিলি)", unitEn: "1 bottle (200ml)" },
  { id: "ph120", name: "XAMIC IM/IV INJ 500MG (1X5'S)", brand: "Renata PLC", unitBn: "৫ টি ইনজেকশন (বক্স)", unitEn: "5 injections" },
  { id: "ph121", name: "ZITHRIN FC 500MG TAB 3X5'S", brand: "Renata PLC", unitBn: "১৫ টি ট্যাবলেট (বক্স)", unitEn: "15 tablets" },

  // Page 3 - Radiant (122-132)
  { id: "ph122", name: "Naprosyn Tab 500mg (50s)", brand: "Radiant", unitBn: "৫০ টি ট্যাবলেট", unitEn: "50 tablets" },
  { id: "ph123", name: "Neucos-B FC Tab (50s)", brand: "Radiant", unitBn: "৫০ টি ট্যাবলেট", unitEn: "50 tablets" },
  { id: "ph124", name: "Rivotril Tab 0.5mg (80s)", brand: "Radiant", unitBn: "৮০ টি ট্যাবলেট", unitEn: "80 tablets" },
  { id: "ph125", name: "Xelcom FC Tab 50mg (50s)", brand: "Radiant", unitBn: "৫০ টি ট্যাবলেট", unitEn: "50 tablets" },
  { id: "ph126", name: "Coralcal-DX FC Tab 600mg", brand: "Radiant", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph127", name: "Prelica Cap 50mg (50s)", brand: "Radiant", unitBn: "৫০ টি ক্যাপসুল", unitEn: "50 capsules" },
  { id: "ph128", name: "Naprosyn-Plus Tab 375mg/20mg", brand: "Radiant", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph129", name: "Exium MUPS FC Tab 20mg (80s)", brand: "Radiant", unitBn: "৮০ টি ট্যাবলেট", unitEn: "80 tablets" },
  { id: "ph130", name: "Naprosyn-Plus Tab 500mg/20mg", brand: "Radiant", unitBn: "১ পিস", unitEn: "1 pc" },
  { id: "ph131", name: "Cranbiotic Cap 400mg (30s)", brand: "Radiant", unitBn: "৩০ টি ক্যাপসুল", unitEn: "30 capsules" },
  { id: "ph132", name: "Ubi-Q Cap 100mg (30s)", brand: "Radiant", unitBn: "৩০ টি ক্যাপসুল", unitEn: "30 capsules" },

  // Page 4 - Popular Pharma & Others (133-200)
  { id: "ph133", name: "Acupain Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 360 },
  { id: "ph134", name: "Bukof Syrup", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 80.24 },
  { id: "ph135", name: "Bukof Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 330 },
  { id: "ph136", name: "Barinez Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 375 },
  { id: "ph137", name: "Becobion Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 300 },
  { id: "ph138", name: "Clenpic Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 300 },
  { id: "ph139", name: "Dorakid Syrup (100 ml)", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 100 },
  { id: "ph140", name: "Doxoven Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 300 },
  { id: "ph141", name: "Doxoven 200 Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 650 },
  { id: "ph142", name: "Doxoven Syrup", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 110 },
  { id: "ph143", name: "Doxoven Syrup 60 ml", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 60 },
  { id: "ph144", name: "Duratocin Injection", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 150.45 },
  { id: "ph145", name: "Flexibac 5 Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 412.5 },
  { id: "ph146", name: "Flexibac 10 Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 750 },
  { id: "ph147", name: "Flexibac Syrup", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 100 },
  { id: "ph148", name: "Hexinor 1 Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 180 },
  { id: "ph149", name: "Hexinor 2 Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 330 },
  { id: "ph150", name: "Hexinor 5 Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 720 },
  { id: "ph151", name: "Hexinor Syrup", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 100 },
  { id: "ph152", name: "Itrazen Capsule", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 360 },
  { id: "ph153", name: "Itrazen 200 Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 560 },
  { id: "ph154", name: "Lipofit IV Infusion", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 1100 },
  { id: "ph155", name: "Lipofit 250 IV Infusion", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 600 },
  { id: "ph156", name: "Lubilax 24 Capsule", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 802.4 },
  { id: "ph157", name: "Lucza 50 Capsule", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 241.5 },
  { id: "ph158", name: "Montinex 10 Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 510 },
  { id: "ph159", name: "Montinex 4 ODT", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 210 },
  { id: "ph160", name: "Montinex 5 ODT", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 270 },
  { id: "ph161", name: "Mirogab 2.5", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 360 },
  { id: "ph162", name: "Mirogab 5", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 600 },
  { id: "ph163", name: "Mirogab 10", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 700 },
  { id: "ph164", name: "Mirogab 15", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 900 },
  { id: "ph165", name: "Ovacal-D", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 360 },
  { id: "ph166", name: "Ovacal-DX", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 510 },
  { id: "ph167", name: "Paloxi 0.25 Injection", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 100.3 },
  { id: "ph168", name: "Paloxi Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 601.8 },
  { id: "ph169", name: "Pradox Injection", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 501.5 },
  { id: "ph170", name: "Prokind Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 105 },
  { id: "ph171", name: "Rabepes MUPS 20", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 500 },
  { id: "ph172", name: "Resva 10 mg Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 500 },
  { id: "ph173", name: "Resva 20 mg Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 420 },
  { id: "ph174", name: "Teslar 20 mg Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 196 },
  { id: "ph175", name: "Teslar 40 mg Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 364 },
  { id: "ph176", name: "Teslar 80 mg Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 588 },
  { id: "ph177", name: "Rupadin Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 600 },
  { id: "ph178", name: "Rupadin Syrup", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 75 },
  { id: "ph179", name: "Simpli-3 PFS (20ml)", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 100 },
  { id: "ph180", name: "Simpli-3 PFS (35ml)", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 150 },
  { id: "ph181", name: "Simpli-3 PFS (50ml)", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 200 },
  { id: "ph182", name: "Simpli-3 Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 480 },
  { id: "ph183", name: "Sixvit Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 130 },
  { id: "ph184", name: "Spasverin Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 251 },
  { id: "ph185", name: "Starcef 200 Capsule", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 630 },
  { id: "ph186", name: "Starcef 400 Capsule", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 840 },
  { id: "ph187", name: "Starcef DS PFS (50 ml)", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 320 },
  { id: "ph188", name: "Traxef 1 gm IV Inj.", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 320 },
  { id: "ph189", name: "Traxef 2 gm IV Inj.", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 490 },
  { id: "ph190", name: "Vonopa 10 mg Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 210 },
  { id: "ph191", name: "Vonopa 20 mg Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 300 },
  { id: "ph192", name: "Xalcort 6 mg Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 570 },
  { id: "ph193", name: "Xalcort 18 mg Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 600 },
  { id: "ph194", name: "Xalcort 24 mg Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 900 },
  { id: "ph195", name: "Xalcort Suspension", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 200 },
  { id: "ph196", name: "Zerotil Plus 250 mg+62.5 mg Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 490 },
  { id: "ph197", name: "Zerotil Plus 500 mg+125 mg Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 840 },
  { id: "ph198", name: "Zerotil Plus PFS (70 ml)", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 285 },
  { id: "ph199", name: "Xerova 10 mg Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 336 },
  { id: "ph200", name: "Xelmet 500 mg Tablet", brand: "Popular Pharma", unitBn: "১ পিস", unitEn: "1 pc", price: 672 },
];

// Clean medical photography images matching various pharmaceutical categories
const MEDICINE_IMAGES = [
  "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=500&q=80",
  "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=500&q=80",
  "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=500&q=80",
  "https://images.unsplash.com/photo-1576073719676-aa955fc1bda9?auto=format&fit=crop&w=500&q=80",
  "https://images.unsplash.com/photo-1550572017-edd951aa8f72?auto=format&fit=crop&w=500&q=80",
  "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=500&q=80"
];

function getAppropriateMedicineImage(name: string, idx: number): string {
  const lower = name.toLowerCase();
  if (lower.includes("crm") || lower.includes("cream") || lower.includes("oint") || lower.includes("gel")) {
    return "https://images.unsplash.com/photo-1550572017-edd951aa8f72?auto=format&fit=crop&w=500&q=80";
  }
  if (lower.includes("drop") || lower.includes("spray") || lower.includes("syp") || lower.includes("syrup") || lower.includes("susp") || lower.includes("soln") || lower.includes("oral sol") || lower.includes("pfs")) {
    return "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=500&q=80";
  }
  if (lower.includes("inj") || lower.includes("iv/im") || lower.includes("infusion")) {
    return "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=500&q=80";
  }
  if (lower.includes("cap") || lower.includes("licap") || lower.includes("cozycap")) {
    return "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=500&q=80";
  }
  return MEDICINE_IMAGES[idx % MEDICINE_IMAGES.length];
}

export const PHARMACY_PRODUCTS_RAW: Product[] = RAW_MEDICINE_ITEMS.map((item, idx) => ({
  id: item.id,
  name: item.name,
  nameBn: item.name,
  nameEn: item.name,
  price: (item as any).price ?? 0,
  originalPrice: (item as any).price ?? 0,
  unitBn: item.unitBn,
  unitEn: item.unitEn,
  unit: item.unitBn,
  category: "pharmacy",
  categoryId: "pharmacy",
  subcategory: "ঔষধ ও প্রেসক্রিপশন আইটেম",
  image: getAppropriateMedicineImage(item.name, idx),
  inStock: true,
  stock: 100,
  isAvailable: true,
  rating: 4.8,
  reviewCount: 15,
  brand: item.brand,
  descriptionBn: `${item.brand} ফার্মাসিউটিক্যালসের অফিসিয়াল অনুমোদিত ঔষধ।`,
  descriptionEn: `Official approved medicine formulation by ${item.brand}.`,
  displayOrder: idx + 1
}));
