import { Product } from "./types";

export const COSMETIC_PRODUCTS_REPLACEMENT: Product[] = [
  {
    id: "cos_001",
    nameBn: "৭ অয়েল ৩০০ মিলি",
    nameEn: "7 Oil 300ml",
    unitBn: "১ বোতল (৩০০ মিলি)",
    unitEn: "1 Bottle (300ml)",
    price: 370,
    originalPrice: 390,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "হেয়ার কেয়ার ও তেল",
    subcategoryId: "sub_cos_hair_oil",
    image: "https://images.unsplash.com/photo-1608248597359-216694e9f506?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1608248597359-216694e9f506?auto=format&fit=crop&w=600&q=80",
    brand: "7 Oils in One",
    descriptionBn: "প্রাকৃতিক ৭টি পুষ্টিকর উপাদানে সমৃদ্ধ হারবাল হেয়ার অয়েল। চুলের গোড়া মজবুত ও উজ্জ্বল করে।",
    descriptionEn: "Complete hair nourishment enriched with 7 essential oils for strong and shiny hair.",
    stock: 50,
    rating: 4.8,
    reviewCount: 15,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 1,
    order: 1
  },
  {
    id: "cos_002",
    nameBn: "৭ অয়েল ২০০ মিলি",
    nameEn: "7 Oil 200ml",
    unitBn: "১ বোতল (২০০ মিলি)",
    unitEn: "1 Bottle (200ml)",
    price: 270,
    originalPrice: 290,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "হেয়ার কেয়ার ও তেল",
    subcategoryId: "sub_cos_hair_oil",
    image: "https://images.unsplash.com/photo-1608248597359-216694e9f506?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1608248597359-216694e9f506?auto=format&fit=crop&w=600&q=80",
    brand: "7 Oils in One",
    descriptionBn: "৭টি প্রাকৃতিক তেলের চমৎকার মিশ্রণ। চুল পড়া রোধে অত্যন্ত কার্যকরী।",
    descriptionEn: "Enriched formula of 7 natural oils to control hair fall and nourish the scalp.",
    stock: 50,
    rating: 4.7,
    reviewCount: 12,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 2,
    order: 2
  },
  {
    id: "cos_003",
    nameBn: "ক্লিন অ্যান্ড ক্লিয়ার",
    nameEn: "Clean & Clear Face Wash",
    unitBn: "১ পিস (১০০ মিলি)",
    unitEn: "1 Piece (100ml)",
    price: 350,
    originalPrice: 380,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "ফেসওয়াশ ও ক্লিনজার",
    subcategoryId: "sub_cos_facewash",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    brand: "Clean & Clear",
    descriptionBn: "অয়েল-ফ্রি ডিপ ক্লিনজিং ফেসওয়াশ, ত্বককে রাখে সারাদিন সতেজ ও তেলমুক্ত।",
    descriptionEn: "Oil-free deep cleansing facewash that keeps skin fresh, clean and oil-free all day.",
    stock: 45,
    rating: 4.9,
    reviewCount: 28,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 3,
    order: 3
  },
  {
    id: "cos_004",
    nameBn: "গোল্ড ব্লিস",
    nameEn: "Gold Bliss",
    unitBn: "১ পিস",
    unitEn: "1 Piece",
    price: 270,
    originalPrice: 300,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "ফেসওয়াশ ও ক্লিনজার",
    subcategoryId: "sub_cos_facewash",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=600&q=80",
    brand: "Bliss",
    descriptionBn: "ত্বকের উজ্জ্বলতা বৃদ্ধিকারী প্রিমিয়াম গোল্ড ফেসওয়াশ ও ক্লিনজার।",
    descriptionEn: "Skin brightening gold radiance cleansing formula for instant glowing skin.",
    stock: 40,
    rating: 4.6,
    reviewCount: 14,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 4,
    order: 4
  },
  {
    id: "cos_005",
    nameBn: "ম্যাঙ্গো ব্লিস",
    nameEn: "Mango Bliss",
    unitBn: "১ পিস",
    unitEn: "1 Piece",
    price: 270,
    originalPrice: 300,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "ফেসওয়াশ ও ক্লিনজার",
    subcategoryId: "sub_cos_facewash",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    brand: "Bliss",
    descriptionBn: "আমের মিষ্টি নির্যাস সমৃদ্ধ রিফ্রেশিং ফেস ক্লিনজার। ত্বকে আনে কোমলতা।",
    descriptionEn: "Sweet mango extract infused skin-rejuvenating gentle cleanser.",
    stock: 35,
    rating: 4.6,
    reviewCount: 9,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 5,
    order: 5
  },
  {
    id: "cos_006",
    nameBn: "ডেনভার",
    nameEn: "Denver Deodorant Body Spray",
    unitBn: "১ পিস (১৬৫ মিলি)",
    unitEn: "1 Piece (165ml)",
    price: 590,
    originalPrice: 620,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "পারফিউম ও বডি স্প্রে",
    subcategoryId: "sub_cos_perfume",
    image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=600&q=80",
    brand: "Denver",
    descriptionBn: "পুরুষদের জন্য দীর্ঘস্থায়ী ও সুগন্ধযুক্ত প্রিমিয়াম বডি স্প্রে।",
    descriptionEn: "Long-lasting magnetic fragrance deodorant body spray for real men.",
    stock: 60,
    rating: 4.9,
    reviewCount: 32,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 6,
    order: 6
  },
  {
    id: "cos_007",
    nameBn: "ওয়াইল্ড স্টোন",
    nameEn: "Wild Stone Deodorant",
    unitBn: "১ পিস (১৫০ মিলি)",
    unitEn: "1 Piece (150ml)",
    price: 580,
    originalPrice: 610,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "পারফিউম ও বডি স্প্রে",
    subcategoryId: "sub_cos_perfume",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=600&q=80",
    brand: "Wild Stone",
    descriptionBn: "তীব্র ও আকর্ষক ঘ্রাণের ওয়াইল্ড স্টোন ডিওডোরেন্ট।",
    descriptionEn: "Irresistible masculine fragrance deodorant for ultra confidence.",
    stock: 55,
    rating: 4.8,
    reviewCount: 22,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 7,
    order: 7
  },
  {
    id: "cos_008",
    nameBn: "মিনি অয়েল বডি",
    nameEn: "Mini Oil Body",
    unitBn: "১ পিস",
    unitEn: "1 Piece",
    price: 140,
    originalPrice: 160,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "স্কিন কেয়ার ও ক্রিম",
    subcategoryId: "sub_cos_skincare",
    image: "https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=600&q=80",
    brand: "Mini Care",
    descriptionBn: "ত্বকের আর্দ্রতা ধরে রাখার বিশেষ মিনি বডি অয়েল।",
    descriptionEn: "Hydrating and smoothing daily mini body nourishment oil.",
    stock: 40,
    rating: 4.5,
    reviewCount: 8,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 8,
    order: 8
  },
  {
    id: "cos_009",
    nameBn: "নিভিয়া রোল",
    nameEn: "Nivea Roll-On",
    unitBn: "১ পিস (৫০ মিলি)",
    unitEn: "1 Piece (50ml)",
    price: 220,
    originalPrice: 240,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "পারফিউম ও বডি স্প্রে",
    subcategoryId: "sub_cos_perfume",
    image: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80",
    brand: "Nivea",
    descriptionBn: "৪৮ ঘণ্টার ঘাম ও দুর্গন্ধ সুরক্ষা প্রদানকারী নিভিয়া রোল-অন ডিওডোরেন্ট।",
    descriptionEn: "48-hour gentle antiperspirant protection roll-on by Nivea.",
    stock: 50,
    rating: 4.8,
    reviewCount: 30,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 9,
    order: 9
  },
  {
    id: "cos_010",
    nameBn: "রেক্সোনা",
    nameEn: "Rexona Roll-On",
    unitBn: "১ পিস (৫০ মিলি)",
    unitEn: "1 Piece (50ml)",
    price: 190,
    originalPrice: 210,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "পারফিউম ও বডি স্প্রে",
    subcategoryId: "sub_cos_perfume",
    image: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80",
    brand: "Rexona",
    descriptionBn: "রেক্সোনা মোশন সেন্স রোল-অন, সারাদিনের সতেজতা ও সুরক্ষার নিশ্চয়তা।",
    descriptionEn: "Rexona motion sense anti-perspirant roll-on for all-day freshness.",
    stock: 45,
    rating: 4.7,
    reviewCount: 19,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 10,
    order: 10
  },
  {
    id: "cos_011",
    nameBn: "নিম ফেসওয়াশ",
    nameEn: "Neem Face Wash",
    unitBn: "১ পিস (১০০ মিলি)",
    unitEn: "1 Piece (100ml)",
    price: 120,
    originalPrice: 140,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "ফেসওয়াশ ও ক্লিনজার",
    subcategoryId: "sub_cos_facewash",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    brand: "Himalaya / Herbal",
    descriptionBn: "প্রাকৃতিক নিমের অ্যান্টি-ব্যাকটেরিয়াল গুণের ফেসওয়াশ। ব্রণ দূর করতে সহায়ক।",
    descriptionEn: "Purifying neem face wash with anti-bacterial protection to prevent pimples.",
    stock: 60,
    rating: 4.8,
    reviewCount: 35,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 11,
    order: 11
  },
  {
    id: "cos_012",
    nameBn: "কালোজিরা তেল",
    nameEn: "Kalojira Oil (Black Seed Oil)",
    unitBn: "১ বোতল (১০০ মিলি)",
    unitEn: "1 Bottle (100ml)",
    price: 190,
    originalPrice: 220,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "হেয়ার কেয়ার ও তেল",
    subcategoryId: "sub_cos_hair_oil",
    image: "https://images.unsplash.com/photo-1608248597359-216694e9f506?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1608248597359-216694e9f506?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার হারবাল",
    descriptionBn: "১০০% খাঁটি কোল্ড-প্রেসড কালোজিরা তেল। চুল ও ত্বকের মহৌষধ।",
    descriptionEn: "100% pure cold-pressed black seed oil for skin and hair health.",
    stock: 40,
    rating: 4.9,
    reviewCount: 26,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 12,
    order: 12
  },
  {
    id: "cos_013",
    nameBn: "হেন্না প্যাক",
    nameEn: "Henna Pack",
    unitBn: "১ প্যাকেট",
    unitEn: "1 Pack",
    price: 30,
    originalPrice: 40,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "হেয়ার কেয়ার ও তেল",
    subcategoryId: "sub_cos_hair_oil",
    image: "https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=600&q=80",
    brand: "Herbal Henna",
    descriptionBn: "প্রাকৃতিক মেহেদি গুঁড়ো প্যাক। চুলে আনে চমৎকার প্রাকৃতিক রঙ ও উজ্জ্বলতা।",
    descriptionEn: "Natural herbal henna powder pack for rich color and hair conditioning.",
    stock: 80,
    rating: 4.6,
    reviewCount: 16,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 13,
    order: 13
  },
  {
    id: "cos_014",
    nameBn: "পন্ডস ক্রিম",
    nameEn: "Ponds Cream (Regular)",
    unitBn: "১ পিস (৫০ গ্রাম)",
    unitEn: "1 Piece (50g)",
    price: 180,
    originalPrice: 200,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "স্কিন কেয়ার ও ক্রিম",
    subcategoryId: "sub_cos_skincare",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    brand: "Pond's",
    descriptionBn: "ত্বকের শুষ্কতা রোধে পন্ডস ময়েশ্চারাইজিং ক্রিম।",
    descriptionEn: "Moisturizing and hydrating nourishing daily skin cream by Pond's.",
    stock: 50,
    rating: 4.7,
    reviewCount: 20,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 14,
    order: 14
  },
  {
    id: "cos_015",
    nameBn: "পন্ডস ক্রিম",
    nameEn: "Ponds Cream (Large)",
    unitBn: "১ পিস (১০০ গ্রাম)",
    unitEn: "1 Piece (100g)",
    price: 310,
    originalPrice: 340,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "স্কিন কেয়ার ও ক্রিম",
    subcategoryId: "sub_cos_skincare",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    brand: "Pond's",
    descriptionBn: "ত্বকের কোমলতা ও সুরক্ষায় পন্ডস বড় প্যাক নারিশিং ক্রিম।",
    descriptionEn: "Large pack nourishing skin soft cream by Pond's for long-term care.",
    stock: 40,
    rating: 4.8,
    reviewCount: 18,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 15,
    order: 15
  },
  {
    id: "cos_016",
    nameBn: "লাক্স সাবান",
    nameEn: "Lux Soap",
    unitBn: "১ পিস (১০০ গ্রাম)",
    unitEn: "1 Piece (100g)",
    price: 60,
    originalPrice: 65,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "সাবান ও বডি ওয়াশ",
    subcategoryId: "sub_cos_soap",
    image: "https://images.unsplash.com/photo-1607006314392-805d762ca138?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1607006314392-805d762ca138?auto=format&fit=crop&w=600&q=80",
    brand: "Lux",
    descriptionBn: "সুগন্ধি ও চমত্কার ফেনা সমৃদ্ধ লাক্স বিউটি সাবান।",
    descriptionEn: "Lux fragrance beauty bar for soft glowing fragrant skin.",
    stock: 120,
    rating: 4.8,
    reviewCount: 50,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 16,
    order: 16
  },
  {
    id: "cos_017",
    nameBn: "লাইফবয় হ্যান্ড ওয়াশ",
    nameEn: "Lifebuoy Hand Wash",
    unitBn: "১ বোতল (২০০ মিলি)",
    unitEn: "1 Bottle (200ml)",
    price: 125,
    originalPrice: 140,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "সাবান ও বডি ওয়াশ",
    subcategoryId: "sub_cos_soap",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    brand: "Lifebuoy",
    descriptionBn: "জীবাণু থেকে ১০০% নিশ্চিত সুরক্ষা দিতে লাইফবয় লিকুইড হ্যান্ড ওয়াশ।",
    descriptionEn: "Total germ protection liquid hand wash with pump dispenser by Lifebuoy.",
    stock: 65,
    rating: 4.9,
    reviewCount: 42,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 17,
    order: 17
  },
  {
    id: "cos_018",
    nameBn: "লাইফবয় সাবান",
    nameEn: "Lifebuoy Soap (Large)",
    unitBn: "১ পিস (১৫০ গ্রাম)",
    unitEn: "1 Piece (150g)",
    price: 80,
    originalPrice: 85,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "সাবান ও বডি ওয়াশ",
    subcategoryId: "sub_cos_soap",
    image: "https://images.unsplash.com/photo-1607006314392-805d762ca138?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1607006314392-805d762ca138?auto=format&fit=crop&w=600&q=80",
    brand: "Lifebuoy",
    descriptionBn: "পরিবারের স্বাস্থ্য সুরক্ষায় শক্তিশালী জীবাণুনাশক সাবান (বড়)।",
    descriptionEn: "Lifebuoy total germ protection bar soap for family health.",
    stock: 90,
    rating: 4.8,
    reviewCount: 38,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 18,
    order: 18
  },
  {
    id: "cos_019",
    nameBn: "লাইফবয় সাবান",
    nameEn: "Lifebuoy Soap (Medium)",
    unitBn: "১ পিস (১০০ গ্রাম)",
    unitEn: "1 Piece (100g)",
    price: 55,
    originalPrice: 60,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "সাবান ও বডি ওয়াশ",
    subcategoryId: "sub_cos_soap",
    image: "https://images.unsplash.com/photo-1607006314392-805d762ca138?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1607006314392-805d762ca138?auto=format&fit=crop&w=600&q=80",
    brand: "Lifebuoy",
    descriptionBn: "নিয়মিত গোসল ও হাত ধোয়ার জন্য নির্ভরযোগ্য জীবাণুনাশক সাবান।",
    descriptionEn: "Everyday germ protection bathing bar soap by Lifebuoy.",
    stock: 100,
    rating: 4.7,
    reviewCount: 30,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 19,
    order: 19
  },
  {
    id: "cos_020",
    nameBn: "ফেয়ার অ্যান্ড লাভলি",
    nameEn: "Fair & Lovely (Glow & Lovely Large)",
    unitBn: "১ পিস (৮০ গ্রাম)",
    unitEn: "1 Piece (80g)",
    price: 270,
    originalPrice: 290,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "স্কিন কেয়ার ও ক্রিম",
    subcategoryId: "sub_cos_skincare",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    brand: "Glow & Lovely",
    descriptionBn: "উন্নত মাল্টি-ভিটামিন ফর্মুলা সমৃদ্ধ ফেয়ার অ্যান্ড লাভলি ক্রিম।",
    descriptionEn: "Advanced multi-vitamin fairness daily facial cream.",
    stock: 50,
    rating: 4.8,
    reviewCount: 40,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 20,
    order: 20
  },
  {
    id: "cos_021",
    nameBn: "ফেয়ার অ্যান্ড লাভলি",
    nameEn: "Fair & Lovely (Glow & Lovely Medium)",
    unitBn: "১ পিস (৫০ গ্রাম)",
    unitEn: "1 Piece (50g)",
    price: 160,
    originalPrice: 180,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "স্কিন কেয়ার ও ক্রিম",
    subcategoryId: "sub_cos_skincare",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    brand: "Glow & Lovely",
    descriptionBn: "ত্বকে দেয় তাৎক্ষণিক সতেজ ও উজ্জ্বল আভা।",
    descriptionEn: "Instant glowing radiant fairness cream by Glow & Lovely.",
    stock: 60,
    rating: 4.7,
    reviewCount: 25,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 21,
    order: 21
  },
  {
    id: "cos_022",
    nameBn: "ইনসিয়াই",
    nameEn: "Innsaei",
    unitBn: "১ পিস",
    unitEn: "1 Piece",
    price: 320,
    originalPrice: 350,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "কসমেটিকস ও রূপচর্চা",
    subcategoryId: "sub_cos_makeup",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80",
    brand: "Innsaei",
    descriptionBn: "প্রিমিয়াম স্কিনকেয়ার ও কসমেটিক পণ্য।",
    descriptionEn: "Special care beauty cosmetic product by Innsaei.",
    stock: 35,
    rating: 4.6,
    reviewCount: 11,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 22,
    order: 22
  },
  {
    id: "cos_023",
    nameBn: "স্কিনো শাওয়ার জেল",
    nameEn: "Skino Shower Gel",
    unitBn: "১ বোতল (২৫০ মিলি)",
    unitEn: "1 Bottle (250ml)",
    price: 220,
    originalPrice: 250,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "সাবান ও বডি ওয়াশ",
    subcategoryId: "sub_cos_soap",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    brand: "Skino",
    descriptionBn: "ত্বককে সতেজ ও মোলায়েম রাখতে স্কিনো রিফ্রেশিং শাওয়ার জেল।",
    descriptionEn: "Refreshing and hydrating cleansing shower body gel by Skino.",
    stock: 45,
    rating: 4.7,
    reviewCount: 14,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 23,
    order: 23
  },
  {
    id: "cos_024",
    nameBn: "স্কিনো ময়েশ্চার/সানস্ক্রিন",
    nameEn: "Skino Moisture / Sunscreen",
    unitBn: "১ পিস",
    unitEn: "1 Piece",
    price: 350,
    originalPrice: 390,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "স্কিন কেয়ার ও ক্রিম",
    subcategoryId: "sub_cos_skincare",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    brand: "Skino",
    descriptionBn: "সূর্যের ক্ষতিকর রশ্মি থেকে কার্যকর সুরক্ষা ও গভীর আর্দ্রতা।",
    descriptionEn: "Dual action moisture plus UV protection sunscreen cream by Skino.",
    stock: 40,
    rating: 4.8,
    reviewCount: 22,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 24,
    order: 24
  },
  {
    id: "cos_025",
    nameBn: "নুও পারফিউম",
    nameEn: "Nwo Perfume",
    unitBn: "১ বোতল (১০০ মিলি)",
    unitEn: "1 Bottle (100ml)",
    price: 590,
    originalPrice: 650,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "পারফিউম ও বডি স্প্রে",
    subcategoryId: "sub_cos_perfume",
    image: "https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=600&q=80",
    brand: "Nwo",
    descriptionBn: "অভিজাত ও দীর্ঘস্থায়ী সুবাসিত নুও লাক্সারি পারফিউম।",
    descriptionEn: "Sophisticated long-lasting signature scent luxury perfume by Nwo.",
    stock: 30,
    rating: 4.9,
    reviewCount: 17,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 25,
    order: 25
  },
  {
    id: "cos_026",
    nameBn: "ফেয়ারনেস ক্রিম মেন",
    nameEn: "Fairness Cream Men",
    unitBn: "১ পিস (৫০ গ্রাম)",
    unitEn: "1 Piece (50g)",
    price: 125,
    originalPrice: 145,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "স্কিন কেয়ার ও ক্রিম",
    subcategoryId: "sub_cos_skincare",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    brand: "Men's Care",
    descriptionBn: "পুরুষদের শক্ত ত্বকের বিশেষ উপযোগী ফেয়ারনেস ও সান-প্রোটেকশন ক্রিম।",
    descriptionEn: "Specially formulated fairness cream for men with UV shield.",
    stock: 55,
    rating: 4.7,
    reviewCount: 23,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 26,
    order: 26
  },
  {
    id: "cos_027",
    nameBn: "ফ্রেশ উডি",
    nameEn: "Fresh Woody Perfume / Spray",
    unitBn: "১ পিস",
    unitEn: "1 Piece",
    price: 650,
    originalPrice: 700,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "পারফিউম ও বডি স্প্রে",
    subcategoryId: "sub_cos_perfume",
    image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=600&q=80",
    brand: "Woody Aromatic",
    descriptionBn: "প্রাকৃতিক উডি ও রিফ্রেশিং সুবাসের এক্সক্লুসিভ পারফিউম।",
    descriptionEn: "Exclusive fresh woody notes fragrance for executive personality.",
    stock: 25,
    rating: 4.9,
    reviewCount: 19,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 27,
    order: 27
  },
  {
    id: "cos_028",
    nameBn: "ফগ ফাইন",
    nameEn: "Fogg Fine Body Spray",
    unitBn: "১ পিস (১২০ মিলি)",
    unitEn: "1 Piece (120ml)",
    price: 390,
    originalPrice: 420,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "পারফিউম ও বডি স্প্রে",
    subcategoryId: "sub_cos_perfume",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=600&q=80",
    brand: "Fogg",
    descriptionBn: "১০০০ স্প্রে নিশ্চয়তা ও আকর্ষণীয় সুবাস সমৃদ্ধ ফগ ফাইন।",
    descriptionEn: "No gas long-lasting fine deodorant body spray by Fogg.",
    stock: 50,
    rating: 4.8,
    reviewCount: 33,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 28,
    order: 28
  },
  {
    id: "cos_029",
    nameBn: "ফগ বডি স্প্রে",
    nameEn: "Fogg Body Spray",
    unitBn: "১ পিস (১২০ মিলি)",
    unitEn: "1 Piece (120ml)",
    price: 350,
    originalPrice: 380,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "পারফিউম ও বডি স্প্রে",
    subcategoryId: "sub_cos_perfume",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=600&q=80",
    brand: "Fogg",
    descriptionBn: "দীর্ঘস্থায়ী মন মাতানো সুবাসযুক্ত জনপ্রিয় ফগ বডি স্প্রে।",
    descriptionEn: "Popular intense aroma daily deodorant body spray by Fogg.",
    stock: 60,
    rating: 4.8,
    reviewCount: 45,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 29,
    order: 29
  },
  {
    id: "cos_030",
    nameBn: "বেলাভিটা পারফিউম",
    nameEn: "Bellavita Perfume",
    unitBn: "১ বোতল (১০০ মিলি)",
    unitEn: "1 Bottle (100ml)",
    price: 1200,
    originalPrice: 1350,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "পারফিউম ও বডি স্প্রে",
    subcategoryId: "sub_cos_perfume",
    image: "https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=600&q=80",
    brand: "Bella Vita Organic",
    descriptionBn: "লাক্সারি ইন্টারন্যাশনাল ব্র্যান্ডের প্রিমিয়াম বেলাভিটা সুগন্ধি।",
    descriptionEn: "Luxury long-lasting organic eau de parfum by Bella Vita.",
    stock: 20,
    rating: 4.9,
    reviewCount: 16,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 30,
    order: 30
  },
  {
    id: "cos_031",
    nameBn: "মামাআর্থ ফেসওয়াশ",
    nameEn: "Mamaearth Facewash",
    unitBn: "১ পিস (১০০ মিলি)",
    unitEn: "1 Piece (100ml)",
    price: 350,
    originalPrice: 380,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "ফেসওয়াশ ও ক্লিনজার",
    subcategoryId: "sub_cos_facewash",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    brand: "Mamaearth",
    descriptionBn: "টক্সিন-মুক্ত প্রাকৃতিক উপাদান সমৃদ্ধ অর্গানিক ফেসওয়াশ।",
    descriptionEn: "Toxin-free natural glow brightening facewash by Mamaearth.",
    stock: 40,
    rating: 4.8,
    reviewCount: 29,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 31,
    order: 31
  },
  {
    id: "cos_032",
    nameBn: "ওয়াইসি মিল্ক ফেসওয়াশ",
    nameEn: "YC Milk Facewash",
    unitBn: "১ পিস (১০০ মিলি)",
    unitEn: "1 Piece (100ml)",
    price: 350,
    originalPrice: 380,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "ফেসওয়াশ ও ক্লিনজার",
    subcategoryId: "sub_cos_facewash",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    brand: "YC",
    descriptionBn: "খাঁটি দুধের প্রোটিন সমৃদ্ধ কোমল ও উজ্জ্বলতাদানকারী ফেসওয়াশ।",
    descriptionEn: "Gentle milk protein facial cleansing foam by YC for soft skin.",
    stock: 45,
    rating: 4.7,
    reviewCount: 21,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 32,
    order: 32
  },
  {
    id: "cos_033",
    nameBn: "মুলতানি মাটি",
    nameEn: "Multani Mati",
    unitBn: "১ প্যাকেট (২০০ গ্রাম)",
    unitEn: "1 Pack (200g)",
    price: 120,
    originalPrice: 140,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "কসমেটিকস ও রূপচর্চা",
    subcategoryId: "sub_cos_makeup",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=600&q=80",
    brand: "Herbal Clay",
    descriptionBn: "তৈলাক্ত ত্বক ও ব্রণের দাগ দূরীকরণে শতভাগ খাঁটি মুলতানি মাটির ফেসপ্যাক।",
    descriptionEn: "100% natural Fuller's Earth clay pack for oil control and acne-free glowing skin.",
    stock: 50,
    rating: 4.8,
    reviewCount: 18,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 33,
    order: 33
  },
  {
    id: "cos_034",
    nameBn: "গ্লো বুস্টার",
    nameEn: "Glow Booster Serum",
    unitBn: "১ পিস (৩০ মিলি)",
    unitEn: "1 Piece (30ml)",
    price: 190,
    originalPrice: 220,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "স্কিন কেয়ার ও ক্রিম",
    subcategoryId: "sub_cos_skincare",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=600&q=80",
    brand: "Glow Lab",
    descriptionBn: "ত্বকের ভেতর থেকে উজ্জ্বলতা বাড়ানোর সক্রিয় গ্লো বুস্টার সেরাম।",
    descriptionEn: "Active vitamin glow radiance facial serum for spotless bright tone.",
    stock: 35,
    rating: 4.7,
    reviewCount: 15,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 34,
    order: 34
  },
  {
    id: "cos_035",
    nameBn: "লিলি নিম এফ/ডব্লিউ",
    nameEn: "Lily Neem Face Wash",
    unitBn: "১ পিস (১০০ মিলি)",
    unitEn: "1 Piece (100ml)",
    price: 150,
    originalPrice: 170,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "ফেসওয়াশ ও ক্লিনজার",
    subcategoryId: "sub_cos_facewash",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    brand: "Lily",
    descriptionBn: "নিমের প্রাকৃতিক নির্যাসে তৈরি জীবাণুনাশক লিলি ফেসওয়াশ।",
    descriptionEn: "Natural purifying neem face wash by Lily for fresh clear skin.",
    stock: 45,
    rating: 4.6,
    reviewCount: 11,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 35,
    order: 35
  },
  {
    id: "cos_036",
    nameBn: "লিলি গোটমিল্ক এফ/ডব্লিউ",
    nameEn: "Lily Goatmilk Face Wash",
    unitBn: "১ পিস (১০০ মিলি)",
    unitEn: "1 Piece (100ml)",
    price: 150,
    originalPrice: 170,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "ফেসওয়াশ ও ক্লিনজার",
    subcategoryId: "sub_cos_facewash",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    brand: "Lily",
    descriptionBn: "ছাগলের দুধের পুষ্টিতে সমৃদ্ধ ত্বক মসৃণকারী লিলি ফেসওয়াশ।",
    descriptionEn: "Nourishing goat milk facial cleanser by Lily for soft velvety skin.",
    stock: 40,
    rating: 4.7,
    reviewCount: 13,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 36,
    order: 36
  },
  {
    id: "cos_037",
    nameBn: "লিলি ফেসওয়াশ",
    nameEn: "Lily Face Wash",
    unitBn: "১ পিস (৭০ মিলি)",
    unitEn: "1 Piece (70ml)",
    price: 120,
    originalPrice: 135,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "ফেসওয়াশ ও ক্লিনজার",
    subcategoryId: "sub_cos_facewash",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    brand: "Lily",
    descriptionBn: "প্রতিদিনের পরিচ্ছন্নতার জন্য সাশ্রয়ী ও কার্যকর লিলি ফেসওয়াশ।",
    descriptionEn: "Daily refreshing deep cleansing face wash by Lily.",
    stock: 50,
    rating: 4.5,
    reviewCount: 10,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 37,
    order: 37
  },
  {
    id: "cos_038",
    nameBn: "স্যান্ডিলিনা সাবান ১০০ গ্রাম",
    nameEn: "Sandalina Soap 100gm",
    unitBn: "১ পিস (১০০ গ্রাম)",
    unitEn: "1 Piece (100g)",
    price: 60,
    originalPrice: 65,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "সাবান ও বডি ওয়াশ",
    subcategoryId: "sub_cos_soap",
    image: "https://images.unsplash.com/photo-1607006314392-805d762ca138?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1607006314392-805d762ca138?auto=format&fit=crop&w=600&q=80",
    brand: "Sandalina",
    descriptionBn: "চন্দনের নির্যাসযুক্ত সুবাসিত ত্বক ফর্সাকারী স্যান্ডিলিনা সোপ।",
    descriptionEn: "Pure sandalwood oil infused luxury aromatic beauty bar.",
    stock: 80,
    rating: 4.8,
    reviewCount: 26,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 38,
    order: 38
  },
  {
    id: "cos_039",
    nameBn: "স্যান্ডিলিনা সাবান ৭৫ গ্রাম",
    nameEn: "Sandalina Soap 75gm",
    unitBn: "১ পিস (৭৫ গ্রাম)",
    unitEn: "1 Piece (75g)",
    price: 50,
    originalPrice: 55,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "সাবান ও বডি ওয়াশ",
    subcategoryId: "sub_cos_soap",
    image: "https://images.unsplash.com/photo-1607006314392-805d762ca138?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1607006314392-805d762ca138?auto=format&fit=crop&w=600&q=80",
    brand: "Sandalina",
    descriptionBn: "খাঁটি চন্দনের স্নিগ্ধতায় ভরপুর ঐতিহ্যবাহী স্যান্ডিলিনা সাবান।",
    descriptionEn: "Sandalwood aroma everyday compact beauty soap by Sandalina.",
    stock: 90,
    rating: 4.7,
    reviewCount: 20,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 39,
    order: 39
  },
  {
    id: "cos_040",
    nameBn: "টোন আপ সানস্ক্রিন",
    nameEn: "Tone Up Sunscreen",
    unitBn: "১ পিস (৫০ মিলি)",
    unitEn: "1 Piece (50ml)",
    price: 650,
    originalPrice: 720,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "স্কিন কেয়ার ও ক্রিম",
    subcategoryId: "sub_cos_skincare",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    brand: "Tone Up Pro",
    descriptionBn: "ত্বকের উজ্জ্বলতা বৃদ্ধি ও ক্ষতিকর অতিবেগুনী রশ্মি থেকে পূর্ণ সান-সুরক্ষা।",
    descriptionEn: "UV SPF50+ Tone-up instant brightening daily protective sunscreen.",
    stock: 35,
    rating: 4.9,
    reviewCount: 22,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 40,
    order: 40
  },
  {
    id: "cos_041",
    nameBn: "ভিট সি ময়েশ্চারাইজার",
    nameEn: "Vitamin C Moisturizer",
    unitBn: "১ পিস (৫০ গ্রাম)",
    unitEn: "1 Piece (50g)",
    price: 1550,
    originalPrice: 1700,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "স্কিন কেয়ার ও ক্রিম",
    subcategoryId: "sub_cos_skincare",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=600&q=80",
    brand: "Derma Vitamin C",
    descriptionBn: "প্রিমিয়াম ভিটামিন সি সমৃদ্ধ অ্যান্টি-এজিং ও হাইড্রেটিং ময়েশ্চারাইজার।",
    descriptionEn: "High potency Vitamin C brightening and anti-aging daily facial moisturizer.",
    stock: 25,
    rating: 4.9,
    reviewCount: 19,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 41,
    order: 41
  },
  {
    id: "cos_042",
    nameBn: "মাটাদোর কার্টিজ",
    nameEn: "Matador Cartridge",
    unitBn: "১ পিস",
    unitEn: "1 Piece",
    price: 25,
    originalPrice: 30,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "কসমেটিকস ও রূপচর্চা",
    subcategoryId: "sub_cos_makeup",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80",
    brand: "Matador",
    descriptionBn: "মসৃণ ও আরামদায়ক শেভিংয়ের জন্য ধারালো ব্লেড কার্টিজ।",
    descriptionEn: "Precision sharp safety shaving razor cartridge by Matador.",
    stock: 150,
    rating: 4.6,
    reviewCount: 27,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 42,
    order: 42
  },
  {
    id: "cos_043",
    nameBn: "স্পোর্টস এফ/ডব্লিউ",
    nameEn: "Sports Face Wash",
    unitBn: "১ পিস (১০০ মিলি)",
    unitEn: "1 Piece (100ml)",
    price: 450,
    originalPrice: 490,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "ফেসওয়াশ ও ক্লিনজার",
    subcategoryId: "sub_cos_facewash",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    brand: "Sports Care",
    descriptionBn: "অতিরিক্ত ঘাম ও ময়লা দূর করে ত্বককে সতেজ রাখে এমন স্পোর্টস ফেসওয়াশ।",
    descriptionEn: "Active cooling sports face wash that clears sweat and pollution dirt.",
    stock: 35,
    rating: 4.8,
    reviewCount: 16,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 43,
    order: 43
  },
  {
    id: "cos_044",
    nameBn: "জয় স্কিন",
    nameEn: "Joy Skin Cream / Lotion",
    unitBn: "১ পিস (১০০ মিলি)",
    unitEn: "1 Piece (100ml)",
    price: 450,
    originalPrice: 490,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "স্কিন কেয়ার ও ক্রিম",
    subcategoryId: "sub_cos_skincare",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=600&q=80",
    brand: "Joy",
    descriptionBn: "ত্বকের মসৃণতা বজায় রাখতে ভেষজ নির্যাসযুক্ত জয় স্কিন ক্রিম।",
    descriptionEn: "Herbal nourishing skin moisturization and glow cream by Joy.",
    stock: 40,
    rating: 4.7,
    reviewCount: 17,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 44,
    order: 44
  },
  {
    id: "cos_045",
    nameBn: "কোদোমো ব্রাশ ও ইয়ার",
    nameEn: "Kodomo Brush & Ear Buds",
    unitBn: "১ সেট",
    unitEn: "1 Set",
    price: 209,
    originalPrice: 230,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "বেবি কেয়ার",
    subcategoryId: "sub_cos_baby",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    brand: "Kodomo",
    descriptionBn: "শিশুদের জন্য তৈরি নরম ব্রিস্টলের টুথব্রাশ ও নিরাপদ তুলার ইয়ার বাডস সেট।",
    descriptionEn: "Gentle baby toothbrush and 100% pure cotton ear buds set by Kodomo.",
    stock: 45,
    rating: 4.9,
    reviewCount: 24,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 45,
    order: 45
  },
  {
    id: "cos_046",
    nameBn: "নিভিয়া সফট ক্রিম",
    nameEn: "Nivea Soft Cream",
    unitBn: "১ পিস (১০০ মিলি)",
    unitEn: "1 Piece (100ml)",
    price: 450,
    originalPrice: 490,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "স্কিন কেয়ার ও ক্রিম",
    subcategoryId: "sub_cos_skincare",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    brand: "Nivea",
    descriptionBn: "ভিটামিন ই এবং জোজোবা অয়েল সমৃদ্ধ হালকা ও দ্রুত শোষিত নিভিয়া সফট ক্রিম।",
    descriptionEn: "Light moisturizing cream with Vitamin E and Jojoba Oil by Nivea.",
    stock: 50,
    rating: 4.9,
    reviewCount: 36,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 46,
    order: 46
  },
  {
    id: "cos_047",
    nameBn: "নিভিয়া রোল",
    nameEn: "Nivea Roll (Whitening)",
    unitBn: "১ পিস (৫০ মিলি)",
    unitEn: "1 Piece (50ml)",
    price: 220,
    originalPrice: 240,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "পারফিউম ও বডি স্প্রে",
    subcategoryId: "sub_cos_perfume",
    image: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80",
    brand: "Nivea",
    descriptionBn: "ত্বকের কালো দাগ দূর ও দীর্ঘমেয়াদী সতেজতা দিতে নিভিয়া রোল-অন।",
    descriptionEn: "Nivea pearl & beauty whitening roll-on deodorant.",
    stock: 45,
    rating: 4.8,
    reviewCount: 22,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 47,
    order: 47
  },
  {
    id: "cos_048",
    nameBn: "নিভিয়া এক্সট্রা ব্রাইট",
    nameEn: "Nivea Extra Bright Lotion",
    unitBn: "১ বোতল (২০০ মিলি)",
    unitEn: "1 Bottle (200ml)",
    price: 450,
    originalPrice: 490,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "স্কিন কেয়ার ও ক্রিম",
    subcategoryId: "sub_cos_skincare",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=600&q=80",
    brand: "Nivea",
    descriptionBn: "৫০ গুণ ভিটামিন সি সমৃদ্ধ ত্বক উজ্জ্বলকারী বডি লোশন।",
    descriptionEn: "Nivea Extra Bright 50x Vitamin C radiant body lotion.",
    stock: 40,
    rating: 4.8,
    reviewCount: 31,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 48,
    order: 48
  },
  {
    id: "cos_049",
    nameBn: "পাউডার ক্যাস",
    nameEn: "Powder Case",
    unitBn: "১ পিস",
    unitEn: "1 Piece",
    price: 100,
    originalPrice: 120,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "কসমেটিকস ও রূপচর্চা",
    subcategoryId: "sub_cos_makeup",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80",
    brand: "Beauty Accessories",
    descriptionBn: "পাফ সহ সুবিধাজনক কসমেটিক ও বেবি পাউডার কেস।",
    descriptionEn: "Portable beauty powder puff case container.",
    stock: 50,
    rating: 4.6,
    reviewCount: 14,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 49,
    order: 49
  },
  {
    id: "cos_050",
    nameBn: "সোপ ক্যাস",
    nameEn: "Soap Case",
    unitBn: "১ পিস",
    unitEn: "1 Piece",
    price: 90,
    originalPrice: 110,
    category: "personal-care",
    categoryId: "personal-care",
    subcategory: "সাবান ও বডি ওয়াশ",
    subcategoryId: "sub_cos_soap",
    image: "https://images.unsplash.com/photo-1607006314392-805d762ca138?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1607006314392-805d762ca138?auto=format&fit=crop&w=600&q=80",
    brand: "Household Essentials",
    descriptionBn: "টেকসই প্লাস্টিকের পানি নিষ্কাশন সুবিধাযুক্ত আকর্ষণীয় সোপ কেস।",
    descriptionEn: "Durable drainage travel-friendly soap case holder.",
    stock: 60,
    rating: 4.7,
    reviewCount: 16,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 50,
    order: 50
  }
];
