import { Category, Product, PromoBanner, Recipe, Review } from "./types";

export const CATEGORIES: Category[] = [
  { id: "all", nameBn: "সকল পণ্য", nameEn: "All Products", iconName: "LayoutGrid", colorClass: "from-emerald-500 to-teal-600", borderColor: "border-emerald-200", displayOrder: 0 },
  { id: "vegetables", nameBn: "শাকসবজি ও ফল", nameEn: "Vegetables & Fruits", iconName: "Salad", colorClass: "bg-emerald-50 text-emerald-800", borderColor: "border-emerald-100", displayOrder: 1 },
  { id: "groceries", nameBn: "মুদি পণ্য", nameEn: "Groceries", iconName: "ShoppingBag", colorClass: "bg-amber-50 text-amber-800", borderColor: "border-amber-100", displayOrder: 2 },
  { id: "bakery-sweets", nameBn: "রেস্টুরেন্ট", nameEn: "Restaurant", iconName: "Utensils", colorClass: "bg-orange-50 text-orange-800", borderColor: "border-orange-100", displayOrder: 3 },
  { id: "fish", nameBn: "তাজা মাছ", nameEn: "Fresh Fish", iconName: "Fish", colorClass: "bg-cyan-50 text-cyan-800", borderColor: "border-cyan-100", displayOrder: 4 },
  { id: "meat", nameBn: "মাংস ও ডিম", nameEn: "Meat & Eggs", iconName: "Beef", colorClass: "bg-rose-50 text-rose-800", borderColor: "border-rose-100", displayOrder: 6 },
  { id: "fruits", nameBn: "তাজা ফলমূল", nameEn: "Fresh Fruits", iconName: "Apple", colorClass: "bg-red-50 text-red-800", borderColor: "border-red-100", displayOrder: 7 },
  { id: "dairy-eggs", nameBn: "দুধ ও দুগ্ধজাত", nameEn: "Dairy & Eggs", iconName: "Milk", colorClass: "bg-blue-50 text-blue-800", borderColor: "border-blue-100", displayOrder: 8 },
  { id: "pharmacy", nameBn: "ফার্মেসি", nameEn: "Pharmacy", iconName: "Pill", colorClass: "bg-teal-50 text-teal-800", borderColor: "border-teal-100", displayOrder: 12 },
  { id: "offers", nameBn: "অফার ও ডিল", nameEn: "Offers & Deals", iconName: "Tag", colorClass: "bg-purple-50 text-purple-800", borderColor: "border-purple-100", displayOrder: 13 }
];

export const GROCERY_PRODUCTS_REPLACEMENT: Product[] = [
  {
    id: "gro_01",
    nameBn: "সয়াবিন তেল",
    nameEn: "Soybean Oil",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 210,
    originalPrice: 220,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    subcategoryId: "sub_groceries_3_oil__sugar__sal",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "বিশুদ্ধ ও প্রিমিয়াম গ্রেড পরিশোধিত সয়াবিন তেল। রান্নায় আনে সুষম স্বাদ ও স্বাস্থ্যকর পুষ্টি।",
    descriptionEn: "Pure refined edible soybean cooking oil, naturally enriched with essential nutrients.",
    stock: 100,
    rating: 4.8,
    reviewCount: 24,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 1,
    order: 1
  },
  {
    id: "gro_02",
    nameBn: "সরিষার তেল",
    nameEn: "Mustard Oil",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 200,
    originalPrice: 215,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    subcategoryId: "sub_groceries_3_oil__sugar__sal",
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "১০০% খাঁটি দেশি ঘানিভাঙা সরিষার তেল। ঝাঁজালো সুবাস ও খাঁটি বাঙালি স্বাদের নিশ্চয়তা।",
    descriptionEn: "100% pure cold-pressed natural mustard oil with strong authentic aroma and flavor.",
    stock: 100,
    rating: 4.9,
    reviewCount: 30,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 2,
    order: 2
  },
  {
    id: "gro_03",
    nameBn: "পাম তেল",
    nameEn: "Palm Oil",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 190,
    originalPrice: 200,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    subcategoryId: "sub_groceries_3_oil__sugar__sal",
    image: "https://images.unsplash.com/photo-1543168256-418811576931?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1543168256-418811576931?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "উচ্চমানের পরিশোধিত সুপার পাম অলিন তেল। সব ধরণের ভাজা ও দৈনন্দিন রান্নার জন্য সাশ্রয়ী।",
    descriptionEn: "Premium refined super olein palm cooking oil ideal for all types of frying and cooking.",
    stock: 100,
    rating: 4.7,
    reviewCount: 18,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 3,
    order: 3
  },
  {
    id: "gro_04",
    nameBn: "গরম মসলা",
    nameEn: "Garam Masala (Whole Mixed)",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 1200,
    originalPrice: 1300,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subcategoryId: "sub_groceries_5_spices___herbs",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "এলাচ, দারুচিনি, লবঙ্গ, গোলমরিচ ও জয়ত্রী সহ বাছাইকৃত সেরা আস্ত সুগন্ধি গরম মসলার মিক্স প্যাক।",
    descriptionEn: "Premium blend of authentic whole aromatic spices including cardamom, cinnamon, cloves and mace.",
    stock: 100,
    rating: 4.9,
    reviewCount: 22,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 4,
    order: 4
  },
  {
    id: "gro_05",
    nameBn: "লবণ",
    nameEn: "Salt",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 22,
    originalPrice: 25,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    subcategoryId: "sub_groceries_3_oil__sugar__sal",
    image: "https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "বিশুদ্ধ আয়োডিনযুক্ত দানাদার খাবার লবণ। দৈনন্দিন রান্নার অপরিহার্য উপাদান।",
    descriptionEn: "Pure iodized cooking salt essential for balanced everyday cooking.",
    stock: 100,
    rating: 4.8,
    reviewCount: 35,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 5,
    order: 5
  },
  {
    id: "gro_06",
    nameBn: "চিনি",
    nameEn: "Sugar",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 110,
    originalPrice: 120,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    subcategoryId: "sub_groceries_3_oil__sugar__sal",
    image: "https://images.unsplash.com/photo-1581441363689-1f3c3c414635?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1581441363689-1f3c3c414635?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "দানাদার স্ফটিক সাদা খাঁটি চিনি। মিষ্টি, চা ও শরবতে আনে চমৎকার মিষ্টতা।",
    descriptionEn: "Pure sparkling refined white crystal sugar, quick-dissolving and naturally sweet.",
    stock: 100,
    rating: 4.8,
    reviewCount: 28,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 6,
    order: 6
  },
  {
    id: "gro_07",
    nameBn: "লাচ্ছা সেমাই",
    nameEn: "Lachha Semai",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 160,
    originalPrice: 175,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "আটা, ময়দা ও সুজি",
    subcategoryId: "sub_groceries_4_flour__maida___",
    image: "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "ঘিয়ে ভাজা মুচমুচে সুস্বাদু প্রিমিয়াম লাচ্ছা সেমাই। উৎসব ও পরিবারের মিষ্টি ডেজার্টের সেরা পছন্দ।",
    descriptionEn: "Crisp and flavorful golden lachha semai, perfect for rich milk and dessert preparations.",
    stock: 100,
    rating: 4.9,
    reviewCount: 21,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 7,
    order: 7
  },
  {
    id: "gro_08",
    nameBn: "মোটা সুজি",
    nameEn: "Semolina (Coarse / Mota Suji)",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 90,
    originalPrice: 100,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "আটা, ময়দা ও সুজি",
    subcategoryId: "sub_groceries_4_flour__maida___",
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "দানাদার খাঁটি মোটা সুজি। সুজির হালুয়া ও সুস্বাদু নাস্তা তৈরির জন্য আদর্শ।",
    descriptionEn: "Premium coarse wheat semolina, great for traditional halwa, desserts and savory snacks.",
    stock: 100,
    rating: 4.7,
    reviewCount: 16,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 8,
    order: 8
  },
  {
    id: "gro_09",
    nameBn: "চিকন সুজি",
    nameEn: "Semolina (Fine / Chikon Suji)",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 90,
    originalPrice: 100,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "আটা, ময়দা ও সুজি",
    subcategoryId: "sub_groceries_4_flour__maida___",
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "মিহি চিকন দানার প্রিমিয়াম সুজি। মিষ্টি ডেজার্ট, বরফি ও পিঠা তৈরিতে অসাধারণ।",
    descriptionEn: "Finely milled pure wheat semolina for silky smooth puddings, burfi and sweets.",
    stock: 100,
    rating: 4.8,
    reviewCount: 15,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 9,
    order: 9
  },
  {
    id: "gro_10",
    nameBn: "সাদা ফল",
    nameEn: "White Cardamom (Shada Fol / Elaichi)",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 5200,
    originalPrice: 5500,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subcategoryId: "sub_groceries_5_spices___herbs",
    image: "https://res.cloudinary.com/upvkzb3p/image/upload/v1789571126/%E0%A6%AE%E0%A6%B6%E0%A6%B2%E0%A6%BE-%E0%A6%B9%E0%A6%BF%E0%A6%B8%E0%A7%87%E0%A6%AC%E0%A7%87-%E0%A6%8F%E0%A6%B2%E0%A6%BE%E0%A6%9A-3_6-1024x576_xyw0pd.jpg",
    imageUrl: "https://res.cloudinary.com/upvkzb3p/image/upload/v1789571126/%E0%A6%AE%E0%A6%B6%E0%A6%B2%E0%A6%BE-%E0%A6%B9%E0%A6%BF%E0%A6%B8%E0%A7%87%E0%A6%AC%E0%A7%87-%E0%A6%8F%E0%A6%B2%E0%A6%BE%E0%A6%9A-3_6-1024x576_xyw0pd.jpg",
    brand: "কাচা বাজার",
    descriptionBn: "সেরা মানের রাজকীয় সুগন্ধি আস্ত ছোট সাদা ফল (এলাচ)। বিরিয়ানি ও রাজকীয় রান্নায় অতুলনীয় সুবাস।",
    descriptionEn: "Top-grade royal aromatic white cardamom pods with intense sweet fragrance.",
    stock: 100,
    rating: 5.0,
    reviewCount: 42,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 10,
    order: 10
  },
  {
    id: "gro_11",
    nameBn: "আস্ত দেশি মেথি",
    nameEn: "Whole Deshi Fenugreek Seeds (Methi)",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 200,
    originalPrice: 220,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subcategoryId: "sub_groceries_5_spices___herbs",
    image: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "পরিষ্কার করা খাঁটি দেশি আস্ত মেথি দানা। আচার, তরকারি ও স্বাস্থ্য সুরক্ষায় বিশেষ গুণসমৃদ্ধ।",
    descriptionEn: "Whole pure natural deshi fenugreek seeds, packed with medicinal and culinary benefits.",
    stock: 100,
    rating: 4.8,
    reviewCount: 19,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 11,
    order: 11
  },
  {
    id: "gro_12",
    nameBn: "গুঁড়ো মেথি",
    nameEn: "Fenugreek Powder (Guro Methi)",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 300,
    originalPrice: 330,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subcategoryId: "sub_groceries_5_spices___herbs",
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "বিশুদ্ধ মিহি গুঁড়ো মেথি। রান্নার স্বাদ বৃদ্ধি ও ভেষজ উপকারিতায় অত্যন্ত কার্যকর।",
    descriptionEn: "Fine ground natural fenugreek powder, highly beneficial for dietary health and rich seasoning.",
    stock: 100,
    rating: 4.7,
    reviewCount: 14,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 12,
    order: 12
  },
  {
    id: "gro_13",
    nameBn: "তেজপাতা",
    nameEn: "Bay Leaves (Tej Pata)",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 200,
    originalPrice: 220,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subcategoryId: "sub_groceries_5_spices___herbs",
    image: "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "তাজা রোদে শুকানো সুবাসযুক্ত খাঁটি তেজপাতা। পোলাও, বিরিয়ানি ও মাংসের রান্নায় সুবাস বাড়ায়।",
    descriptionEn: "Aromatic dried bay leaves, adds rich flavor to curries, stews, and biryani.",
    stock: 100,
    rating: 4.8,
    reviewCount: 20,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 13,
    order: 13
  },
  {
    id: "gro_14",
    nameBn: "পাঁচফোড়ন মসলা",
    nameEn: "Panch Phoron Spices Mix",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 300,
    originalPrice: 330,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subcategoryId: "sub_groceries_5_spices___herbs",
    image: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "জিরা, কালোজিরা, মৌরি, মেথি ও সরিষার সমন্বয়ে তৈরি খাঁটি ঐতিহ্যবাহী পাঁচফোড়ন। ডাল ও সবজির ফোড়নে অতুলনীয়।",
    descriptionEn: "Traditional Bengali five-spice whole blend for tempering dals, vegetables, and pickles.",
    stock: 100,
    rating: 4.9,
    reviewCount: 26,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 14,
    order: 14
  },
  {
    id: "gro_15",
    nameBn: "আস্ত তারক মৌরি",
    nameEn: "Whole Star Anise (Tarak Mouri)",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 300,
    originalPrice: 340,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subcategoryId: "sub_groceries_5_spices___herbs",
    image: "https://images.unsplash.com/photo-1514733670139-4d87a1941d55?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1514733670139-4d87a1941d55?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "সুদৃশ্য তারার ন্যায় সুগন্ধি আস্ত তারক মৌরি (স্টার অ্যানিস)। বিরিয়ানি ও স্যুপে রাজকীয় সুবাস যুক্ত করে।",
    descriptionEn: "Exquisite whole star anise spice, delivering a sweet licorice-like aroma for rich culinary dishes.",
    stock: 100,
    rating: 4.8,
    reviewCount: 17,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 15,
    order: 15
  },
  {
    id: "gro_16",
    nameBn: "জয়ফল",
    nameEn: "Nutmeg (Jaiphal)",
    unitBn: "১ পিস",
    unitEn: "1 pc",
    price: 10,
    originalPrice: 12,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subcategoryId: "sub_groceries_5_spices___herbs",
    image: "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "বাছাইকৃত আস্ত শক্ত জয়ফল। পোলাও, বিরিয়ানি ও রেজালায় অনন্য সুবাস ও গভীর স্বাদ এনে দেয়।",
    descriptionEn: "Whole premium nutmeg kernel, providing warm sweetness and deep aroma when freshly grated.",
    stock: 100,
    rating: 4.8,
    reviewCount: 31,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 16,
    order: 16
  },
  {
    id: "gro_17",
    nameBn: "আস্ত জয়ত্রী",
    nameEn: "Whole Mace (Jatri)",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 3600,
    originalPrice: 3800,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subcategoryId: "sub_groceries_5_spices___herbs",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "প্রিমিয়াম গ্রেড সোনালী রঙের আস্ত জয়ত্রী ফুল। রাজকীয় কোরমা, বিরিয়ানি ও মসলার আভিজাত্য।",
    descriptionEn: "Golden whole mace blades offering an intensely fragrant, delicate warmth for royal recipes.",
    stock: 100,
    rating: 4.9,
    reviewCount: 23,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 17,
    order: 17
  },
  {
    id: "gro_18",
    nameBn: "বড় এলাচ",
    nameEn: "Black Cardamom (Boro Elach)",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 2800,
    originalPrice: 3000,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subcategoryId: "sub_groceries_5_spices___herbs",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "আস্ত বড় কালো এলাচ। স্মোকি ফ্লেভারযুক্ত মাংস ও বিরিয়ানির অন্যতম প্রধান সুগন্ধি মশলা।",
    descriptionEn: "Distinctive whole black cardamom pods with robust smoky and camphoraceous undertones.",
    stock: 100,
    rating: 4.8,
    reviewCount: 25,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 18,
    order: 18
  },
  {
    id: "gro_19",
    nameBn: "দারচিনি",
    nameEn: "Cinnamon Sticks (Darchini)",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 600,
    originalPrice: 650,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subcategoryId: "sub_groceries_5_spices___herbs",
    image: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "খাঁটি সুমিষ্ট প্রাকৃতিক আস্ত দারুচিনি বাকল। রান্নায় আনে অপূর্ব মিষ্টি সুবাস ও স্বাদ।",
    descriptionEn: "Natural premium sweet cinnamon bark rolls, essential for aromatic curries and desserts.",
    stock: 100,
    rating: 4.9,
    reviewCount: 29,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 19,
    order: 19
  },
  {
    id: "gro_20",
    nameBn: "লবঙ্গ",
    nameEn: "Cloves (Lobongo)",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 1600,
    originalPrice: 1750,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subcategoryId: "sub_groceries_5_spices___herbs",
    image: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "ফুলযুক্ত তেলসমৃদ্ধ বাছাইকৃত সেরা আস্ত লবঙ্গ। রান্নার স্বাদ বৃদ্ধি ও ভেষজ গুণে সমৃদ্ধ।",
    descriptionEn: "Selected whole head-intact aromatic cloves, rich in natural essential oils.",
    stock: 100,
    rating: 4.8,
    reviewCount: 27,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 20,
    order: 20
  },
  {
    id: "gro_21",
    nameBn: "গোল মরিচ",
    nameEn: "Black Pepper (Gol Morich)",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 1400,
    originalPrice: 1550,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subcategoryId: "sub_groceries_5_spices___herbs",
    image: "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "খাঁটি দেশি আস্ত কালো গোলমরিচ। প্রখর ঝাঁজালো স্বাদ ও বিশ্বখ্যাত রান্নার স্বাদবর্ধক মশলা।",
    descriptionEn: "Whole pungent black peppercorns, providing classic sharp heat and unmatched flavor.",
    stock: 100,
    rating: 4.9,
    reviewCount: 33,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 21,
    order: 21
  },
  {
    id: "gro_22",
    nameBn: "চিনিগুঁড়া বিরিয়ানির চাউল",
    nameEn: "Chinigura Biryani Rice",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 150,
    originalPrice: 165,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "চাল ও খাদ্যশস্য",
    subcategoryId: "sub_groceries_1_rice___grains",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "সুগন্ধি দিনাজপুরের খাঁটি চিনিগুঁড়া চাল। বিরিয়ানি, পোলাও ও পায়েসের সেরা সুবাসিত চাউল।",
    descriptionEn: "Pure aromatic Dinajpur Chinigura rice, renowned for biryani, polao and special feasts.",
    stock: 100,
    rating: 4.9,
    reviewCount: 45,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 22,
    order: 22
  },
  {
    id: "gro_23",
    nameBn: "কাটারি ভোগ চাউল",
    nameEn: "Kataribhog Rice",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 110,
    originalPrice: 120,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "চাল ও খাদ্যশস্য",
    subcategoryId: "sub_groceries_1_rice___grains",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "চিকন দানার প্রিমিয়াম কাটারি ভোগ চাল। ঝরঝরে ভাত ও সুস্বাদু স্বাদের জন্য জনপ্রিয়।",
    descriptionEn: "Slender grain aromatic Kataribhog rice, yields fluffy and delicious everyday meals.",
    stock: 100,
    rating: 4.8,
    reviewCount: 38,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 23,
    order: 23
  },
  {
    id: "gro_24",
    nameBn: "জিরাশাইল বিরিয়ানির চাউল",
    nameEn: "Jirashail Biryani Rice",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 75,
    originalPrice: 85,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "চাল ও খাদ্যশস্য",
    subcategoryId: "sub_groceries_1_rice___grains",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "চিকন ঝরঝরে দেশি জিরাশাইল চাল। স্বাস্থ্যসম্মত ও পুষ্টিকর ভাত এবং সাশ্রয়ী বিরিয়ানির জন্য সেরা।",
    descriptionEn: "Traditional long-grain Jirashail rice, known for easy digestion and non-sticky cooking.",
    stock: 100,
    rating: 4.7,
    reviewCount: 25,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 24,
    order: 24
  },
  {
    id: "gro_25",
    nameBn: "আতপ চাউল",
    nameEn: "Atop Rice",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 160,
    originalPrice: 175,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "চাল ও খাদ্যশস্য",
    subcategoryId: "sub_groceries_1_rice___grains",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "খাঁটি দেশি সুগন্ধি আতপ চাল। খিচুড়ি, ক্ষীর, পায়েস ও পিঠা তৈরির জন্য অত্যন্ত উপযোগী।",
    descriptionEn: "Authentic non-parboiled white Atop rice, ideal for festive rice puddings and rice cakes.",
    stock: 100,
    rating: 4.8,
    reviewCount: 22,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 25,
    order: 25
  },
  {
    id: "gro_26",
    nameBn: "বাসমতী চাউল (বিরিয়ানির)",
    nameEn: "Basmati Biryani Rice",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 280,
    originalPrice: 300,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "চাল ও খাদ্যশস্য",
    subcategoryId: "sub_groceries_1_rice___grains",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "এক্সট্রা লং গ্রেইন আসল বাসমতী চাউল। রান্নায় দ্বিগুণ লম্বা হয় এবং এনে দেয় দারুণ সুবাস।",
    descriptionEn: "Extra long grain royal basmati rice, cooks to perfection for regal dum biryanis.",
    stock: 100,
    rating: 4.9,
    reviewCount: 39,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 26,
    order: 26
  },
  {
    id: "gro_27",
    nameBn: "বিরিয়ানির চাউল",
    nameEn: "Special Biryani Rice",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 150,
    originalPrice: 165,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "চাল ও খাদ্যশস্য",
    subcategoryId: "sub_groceries_1_rice___grains",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "বাছাইকৃত ঝরঝরে সুগন্ধি বিরিয়ানির চাউল। যেকোনো ঘরোয়া বা অতিথি আপ্যায়নে নিখুঁত বিরিয়ানির নিশ্চয়তা।",
    descriptionEn: "Selected fragrant Biryani rice, ensures separate grains and mouthwatering aroma.",
    stock: 100,
    rating: 4.8,
    reviewCount: 31,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 27,
    order: 27
  },
  {
    id: "gro_28",
    nameBn: "মসুর ডাউল (মোটা)",
    nameEn: "Red Lentil (Bold / Mota Masoor Dal)",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 90,
    originalPrice: 100,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    subcategoryId: "sub_groceries_2_lentils___pulse",
    image: "https://images.unsplash.com/photo-1585994192700-eb86d63d6b88?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1585994192700-eb86d63d6b88?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "পরিষ্কার খাঁটি মোটা দানার মসুর ডাল। দ্রুত সিদ্ধ হয় ও ঘিয়ে ফোড়ন দিলে চমৎকার স্বাদ মেলে।",
    descriptionEn: "High-protein bold red lentils, cooks quickly into a thick comforting daily dal.",
    stock: 100,
    rating: 4.8,
    reviewCount: 41,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 28,
    order: 28
  },
  {
    id: "gro_29",
    nameBn: "মসুর ডাউল (চিকন)",
    nameEn: "Red Lentil (Fine / Chikon Masoor Dal)",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 150,
    originalPrice: 165,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    subcategoryId: "sub_groceries_2_lentils___pulse",
    image: "https://images.unsplash.com/photo-1585994192700-eb86d63d6b88?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1585994192700-eb86d63d6b88?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "প্রিমিয়াম দেশি চিকন দানার লাল মসুর ডাল। অতুলনীয় স্বাদ ও দ্রুত গলে ঘন মোলায়েম ডাল তৈরি হয়।",
    descriptionEn: "Fine local red lentils, celebrated for rich consistency and unmatched authentic taste.",
    stock: 100,
    rating: 4.9,
    reviewCount: 36,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 29,
    order: 29
  },
  {
    id: "gro_30",
    nameBn: "মুগ ডাউল",
    nameEn: "Moong Dal",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 160,
    originalPrice: 175,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    subcategoryId: "sub_groceries_2_lentils___pulse",
    image: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "সোনালী ভাজা মুগ ডাল। মাছের মাথা দিয়ে মুড়িঘন্ট কিংবা ভুনা খিচুড়ির জন্য সেরা উপাদান।",
    descriptionEn: "Clean golden split yellow moong lentils, essential for festive bhuna khichuri.",
    stock: 100,
    rating: 4.9,
    reviewCount: 32,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 30,
    order: 30
  },
  {
    id: "gro_31",
    nameBn: "ছোলার ডাউল",
    nameEn: "Chana Dal (Cholar Dal)",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 120,
    originalPrice: 135,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    subcategoryId: "sub_groceries_2_lentils___pulse",
    image: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "হলুদ তাজা পরিষ্কার ছোলার ডাল। লুচি ও পরোটার সাথে সুস্বাদু নারিকেল দেওয়া ডালের সেরা পছন্দ।",
    descriptionEn: "Polished nutritious split Bengal gram (Chana Dal), ideal for sweet and spicy preparations.",
    stock: 100,
    rating: 4.8,
    reviewCount: 28,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 31,
    order: 31
  },
  {
    id: "gro_32",
    nameBn: "মাসকালাই ডাউল",
    nameEn: "Mashkalai Dal",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 150,
    originalPrice: 165,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    subcategoryId: "sub_groceries_2_lentils___pulse",
    image: "https://images.unsplash.com/photo-1585994192700-eb86d63d6b88?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1585994192700-eb86d63d6b88?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "পুষ্টিকর দেশি সাদা মাসকালাই ডাল। ঐতিহ্যবাহী মাসকালাই রুটি, বড়া ও সুস্বাদু পাতলা ডাল রান্নায় অতুলনীয়।",
    descriptionEn: "Nutritious peeled black gram (Mashkalai Dal), perfect for traditional flatbreads and comforting broth.",
    stock: 100,
    rating: 4.8,
    reviewCount: 21,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 32,
    order: 32
  },
  {
    id: "gro_33",
    nameBn: "বুটের ডাউল",
    nameEn: "Booter Dal",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 120,
    originalPrice: 135,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    subcategoryId: "sub_groceries_2_lentils___pulse",
    image: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "দানাদার পরিষ্কার বুটের ডাল। মাংস দিয়ে ভুনা কিংবা হালুয়া তৈরিতে অসাধারণ সুস্বাদু।",
    descriptionEn: "Hearty split chickpea lentils, excellent when cooked with meat curries or halwa.",
    stock: 100,
    rating: 4.8,
    reviewCount: 26,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 33,
    order: 33
  },
  {
    id: "gro_34",
    nameBn: "খেসারি ডাউল",
    nameEn: "Khesari Dal",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 90,
    originalPrice: 100,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    subcategoryId: "sub_groceries_2_lentils___pulse",
    image: "https://images.unsplash.com/photo-1585994192700-eb86d63d6b88?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1585994192700-eb86d63d6b88?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "মুচমুচে পিয়াজু ও তেলেভাজার জন্য অপরিহার্য দেশি খেসারি ডাল। খাঁটি ও পরিষ্কার।",
    descriptionEn: "Traditional deshi Khesari lentils, widely loved for making crispy fritters and piaju.",
    stock: 100,
    rating: 4.7,
    reviewCount: 30,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 34,
    order: 34
  },
  {
    id: "gro_35",
    nameBn: "মটর ডাউল",
    nameEn: "Motor Dal",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 140,
    originalPrice: 155,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    subcategoryId: "sub_groceries_2_lentils___pulse",
    image: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "গোল দানাদার হলুদ মটর ডাল। সুস্বাদু ঘুগনি, চাট ও বড়া তৈরিতে ব্যবহৃত হয়।",
    descriptionEn: "Yellow split pea Motor dal, ideal for street-style ghugni, chaat, and savory cakes.",
    stock: 100,
    rating: 4.8,
    reviewCount: 24,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 35,
    order: 35
  },
  {
    id: "gro_36",
    nameBn: "মাসকালাই ভাঙা ডাল",
    nameEn: "Split Mashkalai Dal",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 180,
    originalPrice: 200,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    subcategoryId: "sub_groceries_2_lentils___pulse",
    image: "https://images.unsplash.com/photo-1585994192700-eb86d63d6b88?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1585994192700-eb86d63d6b88?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "খাঁটি ভাঙা মাসকালাই ডাল। ঐতিহ্যবাহী ডাল রান্না ও বড়ি তৈরির প্রধান উপাদান।",
    descriptionEn: "High-grade split urad/mashkalai lentils, rich in earthy flavors and fiber.",
    stock: 100,
    rating: 4.8,
    reviewCount: 19,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 36,
    order: 36
  },
  {
    id: "gro_37",
    nameBn: "সোনামুগ ডাউল",
    nameEn: "Sonamoong Dal",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 150,
    originalPrice: 165,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    subcategoryId: "sub_groceries_2_lentils___pulse",
    image: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "উচ্চমানের বাছাইকৃত ছোট দানার খাঁটি সোনামুগ ডাল। হালকা ভেজে রান্না করলে মিষ্টি সুবাস বের হয়।",
    descriptionEn: "Small-grain aromatic premium Sonamoong dal, prized for its golden color and delicate aroma.",
    stock: 100,
    rating: 4.9,
    reviewCount: 34,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 37,
    order: 37
  },
  {
    id: "gro_38",
    nameBn: "প্যাকেট লবণ",
    nameEn: "Packet Salt",
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    price: 40,
    originalPrice: 45,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    subcategoryId: "sub_groceries_3_oil__sugar__sal",
    image: "https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "ভ্যাকুয়াম বাষ্পীভূত পরিশোধিত প্যাকেটজাত ১০০% আয়োডিনযুক্ত খাবার লবণ।",
    descriptionEn: "Vacuum evaporated refined packaged edible iodized table salt.",
    stock: 100,
    rating: 4.8,
    reviewCount: 40,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 38,
    order: 38
  },
  {
    id: "gro_39",
    nameBn: "লাচ্ছা সেমাই (প্যাকেট)",
    nameEn: "Lachha Semai (Packet)",
    unitBn: "১ প্যাকেট",
    unitEn: "1 pack",
    price: 50,
    originalPrice: 60,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "আটা, ময়দা ও সুজি",
    subcategoryId: "sub_groceries_4_flour__maida___",
    image: "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "স্বাস্থ্যসম্মত প্যাকেটজাত ক্রিস্পি লাচ্ছা সেমাই। মুহূর্তেই দুধের সাথে মিশিয়ে পরিবেশনযোগ্য।",
    descriptionEn: "Hygienically packed crunchy lachha semai pack, ready to serve with warm sweet milk.",
    stock: 100,
    rating: 4.8,
    reviewCount: 27,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 39,
    order: 39
  },
  {
    id: "gro_40",
    nameBn: "বিরিয়ানির চাউল (প্যাকেট)",
    nameEn: "Biryani Rice (Packet)",
    unitBn: "১ প্যাকেট",
    unitEn: "1 pack",
    price: 220,
    originalPrice: 240,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "চাল ও খাদ্যশস্য",
    subcategoryId: "sub_groceries_1_rice___grains",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "প্রিমিয়াম প্যাকেটজাত ১ কেজি সুগন্ধি চিনিগুঁড়া বা বাসমতি বিরিয়ানির চাউল।",
    descriptionEn: "Premium packaged 1 kg aromatic rice specially sorted for restaurant-style biryani.",
    stock: 100,
    rating: 4.9,
    reviewCount: 35,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 40,
    order: 40
  },
  {
    id: "gro_41",
    nameBn: "রাঁধুনী হলুদের গুঁড়ো",
    nameEn: "Radhuni Turmeric Powder",
    unitBn: "১ প্যাকেট",
    unitEn: "1 pack",
    price: 70,
    originalPrice: 80,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং আইটেম",
    subcategoryId: "sub_groceries_6_ready_mix___bak",
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80",
    brand: "রাঁধুনী",
    descriptionBn: "খাঁটি বাছাইকৃত হলুদ থেকে প্রস্তুত রাঁধুনী প্যাকেট হলুদ গুঁড়ো। রান্নায় আনে আকর্ষণীয় সোনালী বর্ণ।",
    descriptionEn: "Authentic fine-ground Radhuni turmeric powder, brings vibrant natural color to your cuisine.",
    stock: 100,
    rating: 4.9,
    reviewCount: 46,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 41,
    order: 41
  },
  {
    id: "gro_42",
    nameBn: "রাঁধুনী মাংসের মসলা",
    nameEn: "Radhuni Meat Curry Masala",
    unitBn: "১ প্যাকেট",
    unitEn: "1 pack",
    price: 90,
    originalPrice: 100,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং আইটেম",
    subcategoryId: "sub_groceries_6_ready_mix___bak",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80",
    brand: "রাঁধুনী",
    descriptionBn: "গরু, খাসি ও মুরগির মাংস রান্নার নিখুঁত রেডি মসলা মিক্স। স্বাদ ও সুবাসে অনন্য।",
    descriptionEn: "Perfect ready-mix spice blend by Radhuni for authentic beef, mutton, and chicken curries.",
    stock: 100,
    rating: 4.9,
    reviewCount: 42,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 42,
    order: 42
  },
  {
    id: "gro_43",
    nameBn: "রাঁধুনী মাছের মসলা",
    nameEn: "Radhuni Fish Curry Masala",
    unitBn: "১ প্যাকেট",
    unitEn: "1 pack",
    price: 80,
    originalPrice: 90,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং আইটেম",
    subcategoryId: "sub_groceries_6_ready_mix___bak",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80",
    brand: "রাঁধুনী",
    descriptionBn: "যেকোনো তাজা নদী ও সামুদ্রিক মাছের ঝোল বা ভুনা রান্নার জন্য বিশেষ রাঁধুনী মসলা প্যাক।",
    descriptionEn: "Special fish seasoning blend from Radhuni for mouthwatering fish curries and gravy.",
    stock: 100,
    rating: 4.8,
    reviewCount: 37,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 43,
    order: 43
  },
  {
    id: "gro_44",
    nameBn: "রাঁধুনী হালিম মিক্স",
    nameEn: "Radhuni Haleem Mix",
    unitBn: "১ প্যাকেট",
    unitEn: "1 pack",
    price: 80,
    originalPrice: 90,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং আইটেম",
    subcategoryId: "sub_groceries_6_ready_mix___bak",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    brand: "রাঁধুনী",
    descriptionBn: "শস্য ও সুগন্ধি মসলার সমৃদ্ধ মিশ্রণে তৈরি রাঁধুনী হালিম মিক্স। সহজে ঘরে তৈরি করুন মজাদার হালিম।",
    descriptionEn: "Complete grain and spice mix by Radhuni for rich, slow-cooked royal haleem.",
    stock: 100,
    rating: 4.9,
    reviewCount: 48,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 44,
    order: 44
  },
  {
    id: "gro_45",
    nameBn: "ফিরনী মিক্স",
    nameEn: "Radhuni Firni Mix",
    unitBn: "১ প্যাকেট",
    unitEn: "1 pack",
    price: 80,
    originalPrice: 90,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং আইটেম",
    subcategoryId: "sub_groceries_6_ready_mix___bak",
    image: "https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=600&q=80",
    brand: "রাঁধুনী",
    descriptionBn: "সুগন্ধি চাল, বাদাম ও এলাচের সুষম সংমিশ্রণে তৈরি সুস্বাদু ফিরনী ডেজার্ট মিক্স।",
    descriptionEn: "Classic rice pudding dessert mix with fragrant cardamom and crushed nuts.",
    stock: 100,
    rating: 4.8,
    reviewCount: 29,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 45,
    order: 45
  },
  {
    id: "gro_46",
    nameBn: "বিরিয়ানী মসলা",
    nameEn: "Radhuni Biryani Masala",
    unitBn: "১ প্যাকেট",
    unitEn: "1 pack",
    price: 60,
    originalPrice: 70,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং আইটেম",
    subcategoryId: "sub_groceries_6_ready_mix___bak",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80",
    brand: "রাঁধুনী",
    descriptionBn: "শাহজাদী বিরিয়ানি ও কাচ্চির আসল স্বাদ ও সুবাস ফোটাতে বিশেষ বিরিয়ানী মসলা।",
    descriptionEn: "Authentic biryani masala seasoning for restaurant-quality chicken and mutton biryani.",
    stock: 100,
    rating: 4.9,
    reviewCount: 52,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 46,
    order: 46
  },
  {
    id: "gro_47",
    nameBn: "মরিচের গুঁড়ো মসলা",
    nameEn: "Chilli Powder (Moricher Guro)",
    unitBn: "১ প্যাকেট",
    unitEn: "1 pack",
    price: 70,
    originalPrice: 80,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subcategoryId: "sub_groceries_5_spices___herbs",
    image: "https://images.unsplash.com/photo-1599490659213-e2b9527b0876?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1599490659213-e2b9527b0876?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "খাঁটি লাল মরিচের ঝাঁঝালো সুবাসযুক্ত গুঁড়ো মসলা। তরকারির রঙ ও ঝাল স্বাদের নিশ্চয়তা।",
    descriptionEn: "Pure fiery red chilli powder, delivers natural red color and sharp heat to every dish.",
    stock: 100,
    rating: 4.8,
    reviewCount: 33,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 47,
    order: 47
  },
  {
    id: "gro_48",
    nameBn: "কাস্টার্ড পাউডার",
    nameEn: "Custard Powder",
    unitBn: "১ প্যাকেট",
    unitEn: "1 pack",
    price: 40,
    originalPrice: 50,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং আইটেম",
    subcategoryId: "sub_groceries_6_ready_mix___bak",
    image: "https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "ভ্যানিলা ফ্লেভারের প্রিমিয়াম কাস্টার্ড পাউডার। ফ্রুট কাস্টার্ড ও মিষ্টি ডেজার্টের চমৎকার উপকরণ।",
    descriptionEn: "Velvety smooth vanilla custard powder for delicious fruit salads, puddings and sweets.",
    stock: 100,
    rating: 4.7,
    reviewCount: 19,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 48,
    order: 48
  },
  {
    id: "gro_49",
    nameBn: "ধনের গুঁড়ো মসলা",
    nameEn: "Coriander Powder (Dhoner Guro)",
    unitBn: "১ প্যাকেট",
    unitEn: "1 pack",
    price: 60,
    originalPrice: 70,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    subcategoryId: "sub_groceries_5_spices___herbs",
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80",
    brand: "কাচা বাজার",
    descriptionBn: "রোদে শুকানো খাঁটি ধনে থেকে তৈরি সুবাসিত ধনে গুঁড়ো মসলা। গ্রেভি ঘন ও সুস্বাদু করে।",
    descriptionEn: "Pure aromatic coriander powder, adds mild earthy flavor and thickens gravies.",
    stock: 100,
    rating: 4.8,
    reviewCount: 26,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 49,
    order: 49
  },
  {
    id: "gro_50",
    nameBn: "রাঁধুনী জিরার গুঁড়ো মসলা",
    nameEn: "Radhuni Cumin Powder (Jirar Guro)",
    unitBn: "১ প্যাকেট",
    unitEn: "1 pack",
    price: 180,
    originalPrice: 200,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং আইটেম",
    subcategoryId: "sub_groceries_6_ready_mix___bak",
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80",
    brand: "রাঁধুনী",
    descriptionBn: "বাছাইকৃত খাঁটি রোস্টেড জিরার সুগন্ধি গুঁড়ো মসলা। রান্নার শেষ সময়ে ছড়িয়ে দিলে মোহনীয় ঘ্রাণ ছড়ায়।",
    descriptionEn: "Freshly roasted fine cumin powder from Radhuni, imparts rich warm aroma to cooked curries.",
    stock: 100,
    rating: 4.9,
    reviewCount: 38,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 50,
    order: 50
  },
  {
    id: "gro_51",
    nameBn: "রাঁধুনী গরম মসলা",
    nameEn: "Radhuni Garam Masala (Packet)",
    unitBn: "১ প্যাকেট",
    unitEn: "1 pack",
    price: 35,
    originalPrice: 40,
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং আইটেম",
    subcategoryId: "sub_groceries_6_ready_mix___bak",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80",
    brand: "রাঁধুনী",
    descriptionBn: "এলাচ, দারুচিনি, জায়ফল সহ সব রাজকীয় মসলার ব্লেন্ড করা রাঁধুনী গরম মসলা প্যাকেট।",
    descriptionEn: "Finely ground packaged Radhuni Garam Masala, instant aroma and royal taste for everyday dishes.",
    stock: 100,
    rating: 4.9,
    reviewCount: 44,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    displayOrder: 51,
    order: 51
  }
];

export const PRODUCTS: Product[] = [...GROCERY_PRODUCTS_REPLACEMENT];
export const ALL_PRODUCTS: Product[] = [...GROCERY_PRODUCTS_REPLACEMENT];
export const RESTAURANT_MENU_SECTIONS: string[] = [];
export const GROCERY_SECTIONS: string[] = [
  "চাল ও খাদ্যশস্য",
  "ডাল ও ছোলা",
  "তেল, চিনি, লবণ ও গুড়",
  "আটা, ময়দা ও সুজি",
  "মসলাপাতি — আস্ত ও গুঁড়ো",
  "রেডি মসলা ও বেকিং আইটেম",
  "মসলা ও রান্নার তেল"
];
export const isRiceOrGrainProduct = (_prod?: any): boolean => false;
export const isDalOrPulseProduct = (_prod?: any): boolean => false;
export const getResolvedGrocerySubcategory = (
  _id?: string, 
  nameBn?: string, 
  nameEn?: string, 
  subcategory?: string, 
  _category?: string
): string => {
  if (subcategory && subcategory.trim() && subcategory !== "General" && subcategory !== "all") {
    return subcategory.trim();
  }
  const bn = (nameBn || "").toLowerCase();
  const en = (nameEn || "").toLowerCase();
  if (bn.includes("চাল") || en.includes("rice") || bn.includes("পোলাও") || bn.includes("খাদ্যশস্য") || bn.includes("গম") || bn.includes("ভুট্টা")) {
    return "চাল ও খাদ্যশস্য";
  }
  if (bn.includes("ডাল") || en.includes("dal") || en.includes("lentil") || bn.includes("ছোলা") || bn.includes("মটর")) {
    return "ডাল ও ছোলা";
  }
  if (bn.includes("তেল") || en.includes("oil") || bn.includes("চিনি") || bn.includes("লবণ") || bn.includes("গুড়") || en.includes("sugar") || en.includes("salt")) {
    return "তেল, চিনি, লবণ ও গুড়";
  }
  if (bn.includes("আটা") || bn.includes("ময়দা") || bn.includes("সুজি") || en.includes("flour") || en.includes("maida") || en.includes("suji")) {
    return "আটা, ময়দা ও সুজি";
  }
  if (bn.includes("মসলা") || en.includes("spice") || bn.includes("মরিচ") || bn.includes("হলুদ") || bn.includes("জিরা") || bn.includes("ধনিয়া") || bn.includes("দারুচিনি") || bn.includes("এলাচ") || bn.includes("লবঙ্গ") || bn.includes("গোলমরিচ") || bn.includes("তেজপাতা")) {
    return "মসলাপাতি — আস্ত ও গুঁড়ো";
  }
  if (bn.includes("মিক্স") || bn.includes("বেকিং") || en.includes("baking") || en.includes("mix") || bn.includes("কোকো") || bn.includes("ভ্যানিলা")) {
    return "রেডি মসলা ও বেকিং আইটেম";
  }
  return subcategory || "মসলা ও রান্নার তেল";
};
export const getResolvedGroceryDisplayOrder = (_id?: string, _nameBn?: string, _nameEn?: string, _sub?: string, order?: number): number | undefined => order;
export const GROCERY_SUBCATEGORY_MAP: Record<string, string> = {};
export const GROCERY_ORDER_MAP: Record<string, number> = {};
export const DRY_FOOD_RAW: any[] = [];
export const PHARMACY_PRODUCTS_RAW: any[] = [];

export const PROMO_BANNERS: PromoBanner[] = [
  {
    id: "b1",
    titleBn: "সরাসরি মাঠ থেকে আপনার রান্নাঘরে",
    titleEn: "Directly from Farms to Your Kitchen",
    subtitleBn: "১০-১৫ মিনিটে দ্রুত ডেলিভারি, একদম সতেজ এবং খাঁটি গ্যারান্টি",
    subtitleEn: "15-minute express delivery of fresh organic produce",
    tagBn: "ফ্ল্যাশ ক্যাম্পেইন",
    tagEn: "FLASH CAMPAIGN",
    discountBn: "২৫% পর্যন্ত মেগা ছাড়",
    discountEn: "UP TO 25% MEGA SAVINGS",
    bgGradient: "from-emerald-700 via-teal-600 to-green-700",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "b2",
    titleBn: "পদ্মার রূপালী ইলিশ উৎসব চলছে!",
    titleEn: "Padma River Hilsha Festival!",
    subtitleBn: "নদী থেকে ধৃত সরাসরি ইলিশ, স্বাদে ও আকৃতিতে শতভাগ খাঁটি",
    subtitleEn: "Authentic river-caught Silver Hilsha with unmatched flavor",
    tagBn: "সরাসরি সোর্স",
    tagEn: "DIRECTLY SOURCED",
    discountBn: "ফ্ল্যাট ১২% সরাসরি ছাড়",
    discountEn: "FLAT 12% INSTANT DISCOUNT",
    bgGradient: "from-indigo-700 via-blue-600 to-cyan-700",
    image: "https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "b3",
    titleBn: "রাজশাহীর মিষ্টি হিমসাগর আমমেলা",
    titleEn: "Sweet & Luscious Himsagar Mango Fest",
    subtitleBn: "১০০% ফরমালিন ও রাসায়নিক মুক্ত গাছের পাকা আম",
    subtitleEn: "100% chemicals-free naturally tree-ripened sweet mangoes",
    tagBn: "আমের মৌসুম",
    tagEn: "MANGO MANIA",
    discountBn: "১৮% সরাসরি মূল্যছাড়",
    discountEn: "UP TO 18% DIRECT CUT",
    bgGradient: "from-orange-600 via-amber-500 to-yellow-600",
    image: "https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "b4",
    titleBn: "উইকেন্ড ফ্যামিলি গ্রোসারি মেলা",
    titleEn: "Weekend Family Grocery Fair",
    subtitleBn: "চাল, ডাল, তেল ও ডিমের বাজারে বিশেষ ছাড়",
    subtitleEn: "Massive savings on everyday staple household essentials",
    tagBn: "সাপ্তাহিক বাজার",
    tagEn: "WEEKLY BAZAR",
    discountBn: "সর্বোচ্চ ৩০০ টাকা ক্যাশব্যাক",
    discountEn: "UP TO BDT 300 CASHBACK",
    bgGradient: "from-rose-700 via-red-600 to-pink-700",
    image: "https://images.unsplash.com/photo-1506617498319-3310023a1a01?auto=format&fit=crop&w=800&q=80"
  }
];

export const RECIPES: Recipe[] = [
  {
    id: "r1",
    nameBn: "ঐতিহ্যবাহী সরিষা ইলিশ",
    nameEn: "Traditional Shorshe Ilish",
    prepTimeBn: "২৫ মিনিট",
    prepTimeEn: "25 Mins",
    difficultyBn: "সহজ",
    difficultyEn: "Easy",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    ingredients: [
      { productId: "fi1", nameBn: "পদ্মার ইলিশ মাছ", nameEn: "Padma Hilsha Fish", amountBn: "৫০০ গ্রাম", amountEn: "500g" },
      { productId: "sp2", nameBn: "খাঁটি সয়াবিন/সরিষার তেল", nameEn: "Pure Oil", amountBn: "৪ টেবিল চামচ", amountEn: "4 tbsp" },
      { productId: "sp11", nameBn: "ঝাল কাঁচা মরিচ", nameEn: "Green Chilli", amountBn: "৬-৭ টি", amountEn: "6-7 pcs" }
    ],
    instructionsBn: [
      "প্রথমে ইলিশের টুকরোগুলো ধুয়ে সামান্য হলুদ ও লবণ মেখে রাখুন।",
      "সরিষা দানা, কাঁচা মরিচ এবং এক চিমটি লবণ একসাথে পিষে পেস্ট বানিয়ে নিন।",
      "একটি কড়াইতে সরিষার তেল গরম করে তাতে কালোজিরা ও কাঁচা মরিচের ফোড়ন দিন।",
      "এবার সরিষা পেস্ট এবং সামান্য পানি দিয়ে কষিয়ে মাছের টুকরোগুলো ছাড়ুন।",
      "হালকা আঁচে ১০ মিনিট ঢাকা দিয়ে রান্না করুন। উপরে কাঁচা তেল ও মরিচ ছড়িয়ে নামান।"
    ],
    instructionsEn: [
      "Wash Hilsha steaks and marinate with a pinch of turmeric powder and salt.",
      "Blend mustard seeds, green chillies, and a pinch of salt with water into a smooth paste.",
      "Heat pure mustard oil in a pan, add nigella seeds and green chillies.",
      "Add the mustard paste and a bit of water, then gently place the fish steaks.",
      "Cover and simmer on low-medium heat for 10 minutes. Drizzle fresh oil on top and serve hot."
    ]
  }
];

export const REVIEWS: Review[] = [
  {
    id: "v1",
    userName: "তানজিম আহমেদ",
    rating: 5,
    commentBn: "মাত্র ১২ মিনিটে ধানমন্ডি এলাকায় সতেজ টমেটো ও ইলিশ পেয়েছি! প্যাকেজিং ও ডেলিভারি বয় খুব আন্তরিক ছিল। ৫ স্টারের দাবিদার।",
    commentEn: "Received fresh tomatoes and Hilsha in Dhanmondi in just 12 mins! Superb packaging and extremely courteous rider. 5-stars!",
    date: "July 10, 2026"
  },
  {
    id: "v2",
    userName: "ফারজানা শারমিন",
    rating: 5,
    commentBn: "কাচা বাজার অ্যাপের সরিষা ইলিশ রেসিপির সব উপকরণ এক ক্লিকে অর্ডার করেছি এবং তা দিয়ে চমৎকার রান্না করেছি। এই ফিচারটা খুবই দারুণ!",
    commentEn: "Ordered all Shorshe Ilish ingredients with a single click via their recipe corner. Feature is incredibly convenient and smart!",
    date: "July 11, 2026"
  },
  {
    id: "v3",
    userName: "মাহমুদ হাসান",
    rating: 4,
    commentBn: "হিমসাগর আমগুলো আসলেই মিষ্টি এবং ফরমালিন মুক্ত। তবে ব্রেডের স্টক শেষ হয়ে গিয়েছিল। আশা করি অতি দ্রুত স্টক বৃদ্ধি করা হবে।",
    commentEn: "Mangoes are genuinely sweet and fresh. Highly recommended. Out of stock for brown bread once, but customer support was very helpful.",
    date: "July 12, 2026"
  }
];
