import { Category, Product, PromoBanner, Recipe, Review } from "./types";
import { COSMETICS_PRODUCTS_RAW } from "./lib/cosmeticsData";
import { NEW_GROCERY_PRODUCTS_RAW } from "./lib/newGroceryProducts";

export const CATEGORIES: Category[] = [
  { id: "all", nameBn: "সকল পণ্য", nameEn: "All Products", iconName: "LayoutGrid", colorClass: "from-emerald-500 to-teal-600", borderColor: "border-emerald-200", displayOrder: 0 },
  { id: "vegetables", nameBn: "শাকসবজি ও ফল", nameEn: "Vegetables & Fruits", iconName: "Salad", colorClass: "bg-emerald-50 text-emerald-800", borderColor: "border-emerald-100", displayOrder: 1 },
  { id: "groceries", nameBn: "মুদি পণ্য", nameEn: "Groceries", iconName: "ShoppingBag", colorClass: "bg-amber-50 text-amber-800", borderColor: "border-amber-100", displayOrder: 2 },
  { id: "bakery-sweets", nameBn: "রেস্টুরেন্ট", nameEn: "Restaurant", iconName: "Utensils", colorClass: "bg-orange-50 text-orange-800", borderColor: "border-orange-100", displayOrder: 3 },
  { id: "fish", nameBn: "তাজা মাছ", nameEn: "Fresh Fish", iconName: "Fish", colorClass: "bg-cyan-50 text-cyan-800", borderColor: "border-cyan-100", displayOrder: 4 },
  { id: "snacks-biscuits", nameBn: "কনফেকশনারি", nameEn: "Confectionery", iconName: "Cookie", colorClass: "bg-yellow-50 text-yellow-800", borderColor: "border-yellow-100", displayOrder: 5 },
  { id: "meat", nameBn: "মাংস ও ডিম", nameEn: "Meat & Eggs", iconName: "Beef", colorClass: "bg-rose-50 text-rose-800", borderColor: "border-rose-100", displayOrder: 6 },
  { id: "fruits", nameBn: "তাজা ফলমূল", nameEn: "Fresh Fruits", iconName: "Apple", colorClass: "bg-red-50 text-red-800", borderColor: "border-red-100", displayOrder: 7 },
  { id: "dairy-eggs", nameBn: "দুধ ও দুগ্ধজাত", nameEn: "Dairy & Eggs", iconName: "Milk", colorClass: "bg-blue-50 text-blue-800", borderColor: "border-blue-100", displayOrder: 8 },
  { id: "frozen", nameBn: "ড্রাই ফুড", nameEn: "Dry Food", iconName: "Package", colorClass: "bg-amber-50 text-amber-700", borderColor: "border-amber-100", displayOrder: 9 },
  { id: "cosmetics", nameBn: "কসমেটিকস ও বিউটি কর্নার", nameEn: "Cosmetics & Beauty Corner", iconName: "Sparkles", colorClass: "bg-pink-50 text-pink-700", borderColor: "border-pink-100", displayOrder: 10 },
  { id: "pharmacy", nameBn: "ফার্মেসি", nameEn: "Pharmacy", iconName: "Pill", colorClass: "bg-teal-50 text-teal-800", borderColor: "border-teal-100", displayOrder: 12 },
  { id: "offers", nameBn: "অফার ও ডিল", nameEn: "Offers & Deals", iconName: "Tag", colorClass: "bg-purple-50 text-purple-800", borderColor: "border-purple-100", displayOrder: 13 },
  { id: "pet-food-care", nameBn: "ইভেন্ট ম্যানেজমেন্ট", nameEn: "Event Management", iconName: "Sparkles", colorClass: "bg-orange-50 text-orange-700", borderColor: "border-orange-100", displayOrder: 16, image: "https://res.cloudinary.com/upvkzb3p/image/upload/v1790502262/Gemini_Generated_Image_56vcn756vcn756vc_gq1xfi.jpg", imageUrl: "https://res.cloudinary.com/upvkzb3p/image/upload/v1790502262/Gemini_Generated_Image_56vcn756vcn756vc_gq1xfi.jpg" }
];

export const GROCERY_PRODUCTS_RAW: Product[] = [
  {
    id: "gr1",
    nameBn: "সয়াবিন তেল",
    nameEn: "Soybean Oil",
    price: 210,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.8,
    reviewCount: 24,
    brand: "কাচা বাজার",
    descriptionBn: "বিশুদ্ধ ও পুষ্টিকর ১০০% খাঁটি পরিশোধিত সয়াবিন তেল।",
    descriptionEn: "100% pure refined soybean cooking oil for healthy daily cooking.",
    displayOrder: 1
  },
  {
    id: "gr2",
    nameBn: "সরিষার তেল",
    nameEn: "Mustard Oil",
    price: 200,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    image: "https://images.unsplash.com/photo-1620706857370-e1b9770e8bb1?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.9,
    reviewCount: 30,
    brand: "কাচা বাজার",
    descriptionBn: "ঘানিভাঙা খাঁটি দেশি সরিষার ঝাঁঝালো তেল।",
    descriptionEn: "Authentic cold-pressed pure pungent mustard oil.",
    displayOrder: 2
  },
  {
    id: "gr3",
    nameBn: "পাম তেল",
    nameEn: "Palm Oil",
    price: 190,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    image: "https://images.unsplash.com/photo-1589785244583-a496f8c7b855?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.7,
    reviewCount: 16,
    brand: "কাচা বাজার",
    descriptionBn: "উন্নত মানের পরিশোধিত পাম সুপার রান্নার তেল।",
    descriptionEn: "High-grade refined super palm cooking oil.",
    displayOrder: 3
  },
  {
    id: "gr4",
    nameBn: "গরম মসলা",
    nameEn: "Garam Masala",
    price: 1200,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.9,
    reviewCount: 22,
    brand: "কাচা বাজার",
    descriptionBn: "সুগন্ধি এলাচ, দারচিনি, লবঙ্গ ও গোলমরিচের স্পেশাল ব্লেন্ড গরম মসলা।",
    descriptionEn: "Premium whole aromatic blend of traditional garam masala.",
    displayOrder: 4
  },
  {
    id: "gr5",
    nameBn: "লবণ",
    nameEn: "Salt",
    price: 22,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    image: "https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.8,
    reviewCount: 40,
    brand: "কাচা বাজার",
    descriptionBn: "পরিষ্কার ও আয়োডিনযুক্ত সাদা দানাদার লবণ।",
    descriptionEn: "Pure refined iodized granulated crystal salt.",
    displayOrder: 5
  },
  {
    id: "gr6",
    nameBn: "চিনি",
    nameEn: "Sugar",
    price: 110,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    image: "https://images.unsplash.com/photo-1581441363689-1f3c3c414635?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.8,
    reviewCount: 35,
    brand: "কাচা বাজার",
    descriptionBn: "সাদা চকচকে খাঁটি আখের চিনি।",
    descriptionEn: "Premium pure refined white cane sugar.",
    displayOrder: 6
  },
  {
    id: "gr7",
    nameBn: "লাচ্ছা সেমাই",
    nameEn: "Lachha Semai",
    price: 160,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "আটা, ময়দা ও সুজি",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.9,
    reviewCount: 28,
    brand: "কাচা বাজার",
    descriptionBn: "ঘিয়ে ভাজা মুচমুচে প্রিমিয়াম কোয়ালিটি লাচ্ছা সেমাই।",
    descriptionEn: "Ghee roasted premium crispy lachha semai vermicelli.",
    displayOrder: 7
  },
  {
    id: "gr8",
    nameBn: "মোটা সুজি",
    nameEn: "Coarse Suji (Semolina)",
    price: 90,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "আটা, ময়দা ও সুজি",
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.7,
    reviewCount: 15,
    brand: "কাচা বাজার",
    descriptionBn: "খাঁটি দানাদার মোটা সুজি, হালুয়া ও নাস্তার জন্য উপযুক্ত।",
    descriptionEn: "Coarse grain pure wheat semolina for halwa and snacks.",
    displayOrder: 8
  },
  {
    id: "gr9",
    nameBn: "চিকন সুজি",
    nameEn: "Fine Suji (Semolina)",
    price: 90,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "আটা, ময়দা ও সুজি",
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.7,
    reviewCount: 18,
    brand: "কাচা বাজার",
    descriptionBn: "চিকন দানাদার খাঁটি গমের সুজি।",
    descriptionEn: "Fine grain pure wheat semolina for delicious desserts.",
    displayOrder: 9
  },
  {
    id: "gr10",
    nameBn: "সাদা ফল",
    nameEn: "White Cardamom (Safed Elaichi)",
    price: 5200,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 5.0,
    reviewCount: 12,
    brand: "কাচা বাজার",
    descriptionBn: "সর্বোচ্চ সুগন্ধযুক্ত প্রিমিয়াম সাদা এলাচ (সাদা ফল)।",
    descriptionEn: "Premium grade fragrant white cardamom pods.",
    displayOrder: 10
  },
  {
    id: "gr11",
    nameBn: "আস্ত দেশি মেথি",
    nameEn: "Whole Deshi Fenugreek Seeds (Methi)",
    price: 200,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.8,
    reviewCount: 14,
    brand: "কাচা বাজার",
    descriptionBn: "দেশি খাঁটি আস্ত মেথি দানা, ঔষধি গুণসম্পন্ন।",
    descriptionEn: "Pure whole local fenugreek seeds with medicinal benefits.",
    displayOrder: 11
  },
  {
    id: "gr12",
    nameBn: "গুঁড়ো মেথি",
    nameEn: "Fenugreek Powder (Guro Methi)",
    price: 300,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.8,
    reviewCount: 11,
    brand: "কাচা বাজার",
    descriptionBn: "বাছাইকৃত মেথি থেকে প্রস্তুত শতভাগ খাঁটি গুঁড়ো মেথি।",
    descriptionEn: "Purely ground fresh aromatic fenugreek powder.",
    displayOrder: 12
  },
  {
    id: "gr13",
    nameBn: "তেজপাতা",
    nameEn: "Bay Leaves (Tejpata)",
    price: 200,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.8,
    reviewCount: 20,
    brand: "কাচা বাজার",
    descriptionBn: "প্রাকৃতিক সুবাসযুক্ত শুকনা বড় পাতার তেজপাতা।",
    descriptionEn: "Aromatic dried organic whole bay leaves.",
    displayOrder: 13
  },
  {
    id: "gr14",
    nameBn: "পাঁচফোড়ন মসলা",
    nameEn: "Panch Phoron Spices",
    price: 300,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://images.unsplash.com/photo-1596040033288-72425d3b9965?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.9,
    reviewCount: 23,
    brand: "কাচা বাজার",
    descriptionBn: "পাঁচটি সুগন্ধি মসলার ঐতিহ্যবাহী মিশ্রণ পাঁচফোড়ন।",
    descriptionEn: "Traditional Bengali five-spice whole seasoning blend.",
    displayOrder: 14
  },
  {
    id: "gr15",
    nameBn: "আস্ত তারক মৌরি",
    nameEn: "Whole Star Anise / Fennel",
    price: 300,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.8,
    reviewCount: 17,
    brand: "কাচা বাজার",
    descriptionBn: "মিষ্টি সুবাসযুক্ত খাঁটি আস্ত তারক মৌরি মসলা।",
    descriptionEn: "Whole star anise & sweet aromatic fennel seeds.",
    displayOrder: 15
  },
  {
    id: "gr16",
    nameBn: "জয়ফল",
    nameEn: "Nutmeg (Jaiphal)",
    price: 10,
    unitBn: "১ পিস",
    unitEn: "1 pc",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.9,
    reviewCount: 25,
    brand: "কাচা বাজার",
    descriptionBn: "ঘিয়ে বা মাংসে অসাধারণ গন্ধ সৃষ্টিকারী আস্ত জয়ফল।",
    descriptionEn: "Whole premium aromatic nutmeg piece.",
    displayOrder: 16
  },
  {
    id: "gr17",
    nameBn: "আস্ত জয়ত্রী",
    nameEn: "Whole Mace (Javitri)",
    price: 3600,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 5.0,
    reviewCount: 9,
    brand: "কাচা বাজার",
    descriptionBn: "রয়েল শাহি রান্নার জন্য স্পেশাল সুবাসিত আস্ত জয়ত্রী।",
    descriptionEn: "Finest quality whole fragrant mace (javitri) petals.",
    displayOrder: 17
  },
  {
    id: "gr18",
    nameBn: "বড় এলাচ",
    nameEn: "Black Cardamom (Boro Elach)",
    price: 2800,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.9,
    reviewCount: 16,
    brand: "কাচা বাজার",
    descriptionBn: "ধোঁয়াটে সুবাসযুক্ত আস্ত বড় কালো এলাচ।",
    descriptionEn: "Bold smoky flavored whole black cardamom pods.",
    displayOrder: 18
  },
  {
    id: "gr19",
    nameBn: "দারচিনি",
    nameEn: "Cinnamon (Darchini)",
    price: 600,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.8,
    reviewCount: 31,
    brand: "কাচা বাজার",
    descriptionBn: "মিষ্টি ও ঝাঁঝালো সুগন্ধি খাঁটি দারচিনি ছাল।",
    descriptionEn: "Pure aromatic whole cinnamon bark rolls.",
    displayOrder: 19
  },
  {
    id: "gr20",
    nameBn: "লবঙ্গ",
    nameEn: "Cloves (Lobongo)",
    price: 1600,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://images.unsplash.com/photo-1596040033288-72425d3b9965?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.9,
    reviewCount: 22,
    brand: "কাচা বাজার",
    descriptionBn: "মাথাসহ আস্ত ঝাল ও সুগন্ধি তাজা লবঙ্গ।",
    descriptionEn: "Whole aromatic cloves with intact heads.",
    displayOrder: 20
  },
  {
    id: "gr21",
    nameBn: "গোল মরিচ",
    nameEn: "Black Pepper (Gol Morich)",
    price: 1400,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.8,
    reviewCount: 26,
    brand: "কাচা বাজার",
    descriptionBn: "তীব্র ঝাঁঝ ও অতুলনীয় ফ্লেভারের আস্ত কালো গোলমরিচ।",
    descriptionEn: "Premium bold pungent whole black peppercorns.",
    displayOrder: 21
  },
  {
    id: "gr22",
    nameBn: "চিনিগুঁড়া বিরিয়ানির চাউল",
    nameEn: "Chinigura Biryani Rice",
    price: 150,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "চাল ও খাদ্যশস্য",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.9,
    reviewCount: 42,
    brand: "কাচা বাজার",
    descriptionBn: "সুগন্ধি ও সাদা ছোট দানার ঐতিহ্যবাহী চিনিগুঁড়া পোলাও ও বিরিয়ানির চাল।",
    descriptionEn: "Aromatic small-grain premium Chinigura rice for biryani and polao.",
    displayOrder: 22
  },
  {
    id: "gr23",
    nameBn: "কাটারি ভোগ চাউল",
    nameEn: "Kataribhog Rice",
    price: 110,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "চাল ও খাদ্যশস্য",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.8,
    reviewCount: 29,
    brand: "কাচা বাজার",
    descriptionBn: "দিনাজপুরের বিখ্যাত চিকন ও ঝরঝরে কাটারিভোগ চাল।",
    descriptionEn: "Famous Dinajpur slender Kataribhog rice.",
    displayOrder: 23
  },
  {
    id: "gr24",
    nameBn: "জিরাশাইল বিরিয়ানির চাউল",
    nameEn: "Jirashail Biryani Rice",
    price: 75,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "চাল ও খাদ্যশস্য",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.7,
    reviewCount: 25,
    brand: "কাচা বাজার",
    descriptionBn: "চিকন দানার পুষ্টিকর ও সুস্বাদু জিরাশাইল বিরিয়ানির চাল।",
    descriptionEn: "Nutritious slender Jirashail rice for daily meal and biryani.",
    displayOrder: 24
  },
  {
    id: "gr25",
    nameBn: "আতপ চাউল",
    nameEn: "Atap Rice",
    price: 160,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "চাল ও খাদ্যশস্য",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.8,
    reviewCount: 21,
    brand: "কাচা বাজার",
    descriptionBn: "পায়েস, খিচুড়ি ও পিঠার জন্য আদর্শ সুস্বাদু আতপ চাল।",
    descriptionEn: "Premium unboiled white Atap rice for desserts and pitha.",
    displayOrder: 25
  },
  {
    id: "gr26",
    nameBn: "বাসমতী চাউল (বিরিয়ানির)",
    nameEn: "Basmati Biryani Rice",
    price: 280,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "চাল ও খাদ্যশস্য",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.9,
    reviewCount: 38,
    brand: "কাচা বাজার",
    descriptionBn: "এক্সট্রা লং গ্রেইন সুগন্ধি বাসমতী বিরিয়ানির চাল।",
    descriptionEn: "Extra long grain royal aromatic Basmati biryani rice.",
    displayOrder: 26
  },
  {
    id: "gr27",
    nameBn: "বিরিয়ানির চাউল",
    nameEn: "Biryani Rice",
    price: 150,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "চাল ও খাদ্যশস্য",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.8,
    reviewCount: 33,
    brand: "কাচা বাজার",
    descriptionBn: "ঝরঝরে পোলাও ও সুস্বাদু বিরিয়ানির সেরা চাল।",
    descriptionEn: "Quality aromatic rice for authentic dum biryani.",
    displayOrder: 27
  },
  {
    id: "gr28",
    nameBn: "মসুর ডাউল (মোটা)",
    nameEn: "Red Lentils Coarse (Mosur Daul)",
    price: 90,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    image: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.7,
    reviewCount: 30,
    brand: "কাচা বাজার",
    descriptionBn: "ঘন ডালের জন্য উপযোগী খাঁটি মোটা দানার মসুর ডাল।",
    descriptionEn: "Pure coarse red lentils for thick tasty dal curry.",
    displayOrder: 28
  },
  {
    id: "gr29",
    nameBn: "মসুর ডাউল (চিকন)",
    nameEn: "Red Lentils Fine (Mosur Daul)",
    price: 150,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    image: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.9,
    reviewCount: 35,
    brand: "কাচা বাজার",
    descriptionBn: "দেশি চিকন দানার দ্রুত সিদ্ধ হওয়া প্রিমিয়াম মসুর ডাল।",
    descriptionEn: "Fine grain quick-cooking premium red lentils.",
    displayOrder: 29
  },
  {
    id: "gr30",
    nameBn: "মুগ ডাউল",
    nameEn: "Mung Dal",
    price: 160,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    image: "https://images.unsplash.com/photo-1585994192701-f1a505c817ea?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.8,
    reviewCount: 27,
    brand: "কাচা বাজার",
    descriptionBn: "ভাজা মুগ ডাল, সুস্বাদু ভুনা ও খিচুড়ির জন্য সেরা।",
    descriptionEn: "Yellow split mung dal for rich bhuna and khichuri.",
    displayOrder: 30
  },
  {
    id: "gr31",
    nameBn: "ছোলার ডাউল",
    nameEn: "Chana Dal (Chholar Daul)",
    price: 120,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    image: "https://images.unsplash.com/photo-1585994192701-f1a505c817ea?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.8,
    reviewCount: 24,
    brand: "কাচা বাজার",
    descriptionBn: "নরম ও মিষ্টি স্বাদের সেরা মানের ছোলার ডাল।",
    descriptionEn: "Bengal gram split yellow chana dal.",
    displayOrder: 31
  },
  {
    id: "gr32",
    nameBn: "মাসকালাই ডাউল",
    nameEn: "Mashkalai Dal",
    price: 150,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    image: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.8,
    reviewCount: 22,
    brand: "কাচা বাজার",
    descriptionBn: "ঐতিহ্যবাহী সুস্বাদু ঘন মাসকালাই ডাল।",
    descriptionEn: "Authentic whole/split mashkalai (black gram) dal.",
    displayOrder: 32
  },
  {
    id: "gr33",
    nameBn: "বুটের ডাউল",
    nameEn: "Booter Dal",
    price: 120,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    image: "https://images.unsplash.com/photo-1585994192701-f1a505c817ea?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.7,
    reviewCount: 19,
    brand: "কাচা বাজার",
    descriptionBn: "পরোটা ও রুটির সাথে খাওয়ার জন্য সেরা বুটের ডাল।",
    descriptionEn: "High quality split yellow chickpea boot dal.",
    displayOrder: 33
  },
  {
    id: "gr34",
    nameBn: "খেসারি ডাউল",
    nameEn: "Khesari Dal",
    price: 90,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    image: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.7,
    reviewCount: 20,
    brand: "কাচা বাজার",
    descriptionBn: "মুচমুচে পেঁয়াজু ও ডাল বড়ার জন্য খাঁটি খেসারি ডাল।",
    descriptionEn: "Traditional khesari dal for crispy piyaju and fritters.",
    displayOrder: 34
  },
  {
    id: "gr35",
    nameBn: "মটর ডাউল",
    nameEn: "Motor Dal (Pea Dal)",
    price: 140,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    image: "https://images.unsplash.com/photo-1585994192701-f1a505c817ea?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.8,
    reviewCount: 18,
    brand: "কাচা বাজার",
    descriptionBn: "দেশি পুষ্টিকর তাজা দানার শুকনা মটর ডাল।",
    descriptionEn: "Nutritious dried green/yellow split pea dal.",
    displayOrder: 35
  },
  {
    id: "gr36",
    nameBn: "মাসকালাই ভাঙা ডাল",
    nameEn: "Split Mashkalai Dal",
    price: 180,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    image: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.9,
    reviewCount: 16,
    brand: "কাচা বাজার",
    descriptionBn: "খোসা ছাড়ানো পরিষ্কার ভাঙা মাসকালাই ডাল।",
    descriptionEn: "Husked split white mashkalai dal.",
    displayOrder: 36
  },
  {
    id: "gr37",
    nameBn: "সোনামুগ ডাউল",
    nameEn: "Sonamung Dal",
    price: 150,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "ডাল ও ছোলা",
    image: "https://images.unsplash.com/photo-1585994192701-f1a505c817ea?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.9,
    reviewCount: 26,
    brand: "কাচা বাজার",
    descriptionBn: "সোনালী চকচকে সুবাসিত প্রিমিয়াম সোনামুগ ডাল।",
    descriptionEn: "Golden aromatic supreme quality Sonamung dal.",
    displayOrder: 37
  },
  {
    id: "gr38",
    nameBn: "প্যাকেট লবণ",
    nameEn: "Packet Salt",
    price: 40,
    unitBn: "১ কেজি",
    unitEn: "1 kg",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "তেল, চিনি, লবণ ও গুড়",
    image: "https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.9,
    reviewCount: 38,
    brand: "কাচা বাজার",
    descriptionBn: "১০০% ভ্যাকুয়াম ইভাপোরেটেড আয়োডিনযুক্ত প্যাকেট লবণ।",
    descriptionEn: "100% vacuum evaporated iodized packet table salt.",
    displayOrder: 38
  },
  {
    id: "gr39",
    nameBn: "লাচ্ছা সেমাই (প্যাকেট)",
    nameEn: "Lachha Semai (Packet)",
    price: 50,
    unitBn: "১ প্যাকেট",
    unitEn: "1 packet",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "আটা, ময়দা ও সুজি",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.8,
    reviewCount: 24,
    brand: "কাচা বাজার",
    descriptionBn: "ঘিয়ে ভাজা সুস্বাদু লাচ্ছা সেমাইয়ের সিলড প্যাক।",
    descriptionEn: "Ghee fried crispy packet lachha semai.",
    displayOrder: 39
  },
  {
    id: "gr40",
    nameBn: "বিরিয়ানির চাউল (প্যাকেট)",
    nameEn: "Biryani Rice (Packet)",
    price: 220,
    unitBn: "১ প্যাকেট",
    unitEn: "1 packet",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "চাল ও খাদ্যশস্য",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.9,
    reviewCount: 31,
    brand: "কাচা বাজার",
    descriptionBn: "ব্র্যান্ডেড প্রিমিয়াম সিল করা বিরিয়ানির চাউলের প্যাকেট।",
    descriptionEn: "Branded premium sealed packet aromatic biryani rice.",
    displayOrder: 40
  },
  {
    id: "gr41",
    nameBn: "রাঁধুনী হলুদের গুঁড়ো",
    nameEn: "Radhuni Turmeric Powder",
    price: 70,
    unitBn: "১ প্যাকেট",
    unitEn: "1 packet",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.9,
    reviewCount: 33,
    brand: "রাঁধুনী",
    descriptionBn: "খাঁটি দেশি হলুদ থেকে তৈরি রাঁধুনী হলুদের গুঁড়ো।",
    descriptionEn: "Radhuni pure authentic turmeric powder packet.",
    displayOrder: 41
  },
  {
    id: "gr42",
    nameBn: "রাঁধুনী মাংসের মসলা",
    nameEn: "Radhuni Meat Masala",
    price: 90,
    unitBn: "১ প্যাকেট",
    unitEn: "1 packet",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.9,
    reviewCount: 40,
    brand: "রাঁধুনী",
    descriptionBn: "গরু ও খাসির মাংসের অতুলনীয় স্বাদের জন্য রাঁধুনী মাংসের মসলা।",
    descriptionEn: "Radhuni meat curry spice mix packet.",
    displayOrder: 42
  },
  {
    id: "gr43",
    nameBn: "রাঁধুনী মাছের মসলা",
    nameEn: "Radhuni Fish Masala",
    price: 80,
    unitBn: "১ প্যাকেট",
    unitEn: "1 packet",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://images.unsplash.com/photo-1596040033288-72425d3b9965?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.8,
    reviewCount: 27,
    brand: "রাঁধুনী",
    descriptionBn: "তাজা মাছের ঝোল ও ভুনা রান্নায় বিশেষ ফ্লেভারের মাছের মসলা।",
    descriptionEn: "Radhuni delicious fish curry spice mix packet.",
    displayOrder: 43
  },
  {
    id: "gr44",
    nameBn: "রাঁধুনী হালিম মিক্স",
    nameEn: "Radhuni Haleem Mix",
    price: 80,
    unitBn: "১ প্যাকেট",
    unitEn: "1 packet",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং উপাদান",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.9,
    reviewCount: 36,
    brand: "রাঁধুনী",
    descriptionBn: "ঘরে বসেই শাহী হালিম তৈরির সম্পূর্ণ রাঁধুনী হালিম মিক্স।",
    descriptionEn: "Radhuni special Shahi haleem instant mix packet.",
    displayOrder: 44
  },
  {
    id: "gr45",
    nameBn: "ফিরনী মিক্স",
    nameEn: "Firni Mix",
    price: 80,
    unitBn: "১ প্যাকেট",
    unitEn: "1 packet",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং উপাদান",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.8,
    reviewCount: 22,
    brand: "কাচা বাজার",
    descriptionBn: "সুস্বাদু ও মিষ্টি শাহী ফিরনী তৈরির রেডি মিক্স।",
    descriptionEn: "Delicious royal fragrant firni dessert instant mix.",
    displayOrder: 45
  },
  {
    id: "gr46",
    nameBn: "বিরিয়ানী মসলা",
    nameEn: "Biryani Masala",
    price: 60,
    unitBn: "১ প্যাকেট",
    unitEn: "1 packet",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং উপাদান",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.9,
    reviewCount: 45,
    brand: "কাচা বাজার",
    descriptionBn: "খাঁটি মসলার সমন্বয়ে তৈরি স্পেশাল শাহী বিরিয়ানি মসলা।",
    descriptionEn: "Special Shahi biryani aromatic spice mix packet.",
    displayOrder: 46
  },
  {
    id: "gr47",
    nameBn: "মরিচের গুঁড়ো মসলা",
    nameEn: "Chili Powder Masala",
    price: 70,
    unitBn: "১ প্যাকেট",
    unitEn: "1 packet",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://images.unsplash.com/photo-1596040033288-72425d3b9965?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.8,
    reviewCount: 34,
    brand: "কাচা বাজার",
    descriptionBn: "ঝাল ও আকর্ষণীয় রঙের খাঁটি লাল মরিচের গুঁড়ো।",
    descriptionEn: "Pure spicy vibrant red chili powder packet.",
    displayOrder: 47
  },
  {
    id: "gr48",
    nameBn: "কাস্টার্ড পাউডার",
    nameEn: "Custard Powder",
    price: 40,
    unitBn: "১ প্যাকেট",
    unitEn: "1 packet",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "রেডি মসলা ও বেকিং উপাদান",
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.7,
    reviewCount: 19,
    brand: "কাচা বাজার",
    descriptionBn: "ভ্যানিলা ফ্লেভারের মসৃণ ডেজার্ট ও ফ্রুট সালাদের কাস্টার্ড পাউডার।",
    descriptionEn: "Vanilla flavored smooth custard powder for puddings.",
    displayOrder: 48
  },
  {
    id: "gr49",
    nameBn: "ধনের গুঁড়ো মসলা",
    nameEn: "Coriander Powder Masala",
    price: 60,
    unitBn: "১ প্যাকেট",
    unitEn: "1 packet",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://images.unsplash.com/photo-1596040033288-72425d3b9965?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.8,
    reviewCount: 23,
    brand: "কাচা বাজার",
    descriptionBn: "তাজা ধনিয়া দানা থেকে তৈরি সুগন্ধি ধনের গুঁড়ো মসলা।",
    descriptionEn: "Freshly ground aromatic coriander powder packet.",
    displayOrder: 49
  },
  {
    id: "gr50",
    nameBn: "রাঁধুনী জিরার গুঁড়ো মসলা",
    nameEn: "Radhuni Cumin Powder",
    price: 180,
    unitBn: "১ প্যাকেট",
    unitEn: "1 packet",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.9,
    reviewCount: 42,
    brand: "রাঁধুনী",
    descriptionBn: "বাছাইকৃত খাঁটি রোস্টেড জিরার চমৎকার স্বাদের রাঁধুনী জিরার গুঁড়ো।",
    descriptionEn: "Radhuni pure roasted cumin powder packet.",
    displayOrder: 50
  },
  {
    id: "gr51",
    nameBn: "রাঁধুনী গরম মসলা",
    nameEn: "Radhuni Garam Masala (Packet)",
    price: 35,
    unitBn: "১ প্যাকেট",
    unitEn: "1 packet",
    category: "groceries",
    categoryId: "groceries",
    subcategory: "মসলাপাতি — আস্ত ও গুঁড়ো",
    image: "https://images.unsplash.com/photo-1596040033288-72425d3b9965?auto=format&fit=crop&w=500&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    rating: 4.9,
    reviewCount: 39,
    brand: "রাঁধুনী",
    descriptionBn: "শাহী রান্নার স্বাদ বাড়াতে রাঁধুনী গরম মসলার স্পেশাল প্যাক।",
    descriptionEn: "Radhuni garam masala aromatic ground spices packet.",
    displayOrder: 51
  },
  ...NEW_GROCERY_PRODUCTS_RAW
];

export const RESTAURANT_PRODUCTS_RAW: Product[] = [
  {
    id: "rest_item_shahi_morog_polao_egg",
    nameBn: "শাহী মোরগ পোলাও (ডিমসহ)",
    nameEn: "Shahi Morog Polao (with Egg)",
    price: 160,
    originalPrice: 160,
    unitBn: "০১ প্লেট",
    unitEn: "1 Plate",
    category: "bakery-sweets",
    categoryId: "bakery-sweets",
    subcategoryId: "biryani-rice",
    subcategory: "বিরিয়ানি, পোলাও ও রাইস",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.9,
    reviewCount: 38,
    brand: "কাচা বাজার রেস্টুরেন্ট",
    descriptionBn: "ঘিয়ে ভাজা সুগন্ধি চিনিগুঁড়া চালের পোলাও, সুস্বাদু রোস্ট করা দেশি মুরগির টুকরো এবং সিদ্ধ ডিম।",
    descriptionEn: "Aromatic ghee-cooked Chinigura polao served with spiced tender chicken roast and boiled egg.",
    displayOrder: 101,
    order: 101
  },
  {
    id: "rest_item_basmati_mutton_kacchi_egg",
    nameBn: "বাসমতি খাসির কাচ্চি (ডিমসহ)",
    nameEn: "Basmati Mutton Kacchi (with Egg)",
    price: 220,
    originalPrice: 220,
    unitBn: "০১ প্লেট",
    unitEn: "1 Plate",
    category: "bakery-sweets",
    categoryId: "bakery-sweets",
    subcategoryId: "biryani-rice",
    subcategory: "বিরিয়ানি, পোলাও ও রাইস",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.9,
    reviewCount: 45,
    brand: "কাচা বাজার রেস্টুরেন্ট",
    descriptionBn: "দীর্ঘ দানার খাঁটি বাসমতি চালে দম দেয়া নরম তুলতুলে খাসির মাংস, শাহী আলু ও ডিমের ঐতিহ্যবাহী কাচ্চি বিরিয়ানি।",
    descriptionEn: "Authentic dum cooked long-grain Basmati rice with succulent mutton chunks, spiced potato, and egg.",
    displayOrder: 102,
    order: 102
  },
  {
    id: "rest_item_chicken_biryani_half",
    nameBn: "মুরগির বিরিয়ানী (হাফ)",
    nameEn: "Chicken Biryani (Half)",
    price: 100,
    originalPrice: 100,
    unitBn: "হাফ প্লেট",
    unitEn: "Half Plate",
    category: "bakery-sweets",
    categoryId: "bakery-sweets",
    subcategoryId: "biryani-rice",
    subcategory: "বিরিয়ানি, পোলাও ও রাইস",
    image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 29,
    brand: "কাচা বাজার রেস্টুরেন্ট",
    descriptionBn: "সুস্বাদু ও ঝরঝরে মোরগ বিরিয়ানি (হাফ প্লেট সাইজ), এক জনের তৃপ্তিদায়ক খাবারের জন্য পারফেক্ট।",
    descriptionEn: "Flavorful and aromatic chicken biryani (half portion), perfect single serving.",
    displayOrder: 103,
    order: 103
  },
  {
    id: "rest_item_chicken_biryani_full",
    nameBn: "মুরগির বিরিয়ানী (ফুল)",
    nameEn: "Chicken Biryani (Full)",
    price: 200,
    originalPrice: 200,
    unitBn: "ফুল প্লেট",
    unitEn: "Full Plate",
    category: "bakery-sweets",
    categoryId: "bakery-sweets",
    subcategoryId: "biryani-rice",
    subcategory: "বিরিয়ানি, পোলাও ও রাইস",
    image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.9,
    reviewCount: 42,
    brand: "কাচা বাজার রেস্টুরেন্ট",
    descriptionBn: "পরিপূর্ণ মসলাযুক্ত সুস্বাদু মুরগির বিরিয়ানি (ফুল প্লেট), বড় টুকরো মুরগি ও ডিমসহ পরিবেশন।",
    descriptionEn: "Rich spiced traditional chicken biryani (full portion) served with large succulent chicken piece.",
    displayOrder: 104,
    order: 104
  },
  {
    id: "rest_item_basmati_chicken_dum_biryani",
    nameBn: "চিকেন দম বিরিয়ানী (বাসমতি)",
    nameEn: "Basmati Chicken Dum Biryani",
    price: 180,
    originalPrice: 180,
    unitBn: "ফুল প্লেট",
    unitEn: "Full Plate",
    category: "bakery-sweets",
    categoryId: "bakery-sweets",
    subcategoryId: "biryani-rice",
    subcategory: "বিরিয়ানি, পোলাও ও রাইস",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.9,
    reviewCount: 36,
    brand: "কাচা বাজার রেস্টুরেন্ট",
    descriptionBn: "হালকা আঁচে দমে রান্না করা প্রিমিয়াম বাসমতি চালের স্পেশাল হায়দ্রাবাদি স্টাইল চিকেন দম বিরিয়ানি।",
    descriptionEn: "Slow dum-cooked premium Basmati long-grain rice layered with marinated tender chicken and fresh herbs.",
    displayOrder: 105,
    order: 105
  },
  {
    id: "rest_item_mutton_tehari_full",
    nameBn: "খাসির তেহেরী (ফুল)",
    nameEn: "Mutton Tehari (Full)",
    price: 240,
    originalPrice: 240,
    unitBn: "ফুল প্লেট",
    unitEn: "Full Plate",
    category: "bakery-sweets",
    categoryId: "bakery-sweets",
    subcategoryId: "biryani-rice",
    subcategory: "বিরিয়ানি, পোলাও ও রাইস",
    image: "https://images.unsplash.com/photo-1642821373181-696a54913e93?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1642821373181-696a54913e93?auto=format&fit=crop&w=600&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.9,
    reviewCount: 39,
    brand: "কাচা বাজার রেস্টুরেন্ট",
    descriptionBn: "পুরান ঢাকার খাঁটি রেসিপিতে খাঁটি সরিষার তেলে রান্না করা ঝাল সুগন্ধি খাসির মাংসের তেহেরী (ফুল প্লেট)।",
    descriptionEn: "Authentic Old Dhaka style mustard oil infused aromatic Mutton Tehari with whole green chilies (full plate).",
    displayOrder: 106,
    order: 106
  },
  {
    id: "rest_item_mutton_tehari_half",
    nameBn: "খাসির তেহেরী (হাফ)",
    nameEn: "Mutton Tehari (Half)",
    price: 130,
    originalPrice: 130,
    unitBn: "হাফ প্লেট",
    unitEn: "Half Plate",
    category: "bakery-sweets",
    categoryId: "bakery-sweets",
    subcategoryId: "biryani-rice",
    subcategory: "বিরিয়ানি, পোলাও ও রাইস",
    image: "https://images.unsplash.com/photo-1642821373181-696a54913e93?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1642821373181-696a54913e93?auto=format&fit=crop&w=600&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 27,
    brand: "কাচা বাজার রেস্টুরেন্ট",
    descriptionBn: "খাঁটি সরিষার তেলে রান্না করা নরম খাসির মাংসের সুস্বাদু তেহেরী (হাফ প্লেট)।",
    descriptionEn: "Authentic Old Dhaka style mustard oil cooked flavorful Mutton Tehari (half plate).",
    displayOrder: 107,
    order: 107
  },
  {
    id: "rest_item_egg_polao_half",
    nameBn: "ডিম পোলাও (হাফ)",
    nameEn: "Egg Polao (Half)",
    price: 60,
    originalPrice: 60,
    unitBn: "হাফ প্লেট",
    unitEn: "Half Plate",
    category: "bakery-sweets",
    categoryId: "bakery-sweets",
    subcategoryId: "biryani-rice",
    subcategory: "বিরিয়ানি, পোলাও ও রাইস",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.7,
    reviewCount: 22,
    brand: "কাচা বাজার রেস্টুরেন্ট",
    descriptionBn: "ঘিয়ে ভাজা সুগন্ধি পোলাও চালের সাথে সোনালী ভাজা সিদ্ধ ডিম (হাফ প্লেট)।",
    descriptionEn: "Aromatic ghee-fried fragrant polao served with golden fried egg (half plate portion).",
    displayOrder: 108,
    order: 108
  },
  {
    id: "rest_item_egg_polao_full",
    nameBn: "ডিম পোলাও (ফুল)",
    nameEn: "Egg Polao (Full)",
    price: 120,
    originalPrice: 120,
    unitBn: "ফুল প্লেট",
    unitEn: "Full Plate",
    category: "bakery-sweets",
    categoryId: "bakery-sweets",
    subcategoryId: "biryani-rice",
    subcategory: "বিরিয়ানি, পোলাও ও রাইস",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 31,
    brand: "কাচা বাজার রেস্টুরেন্ট",
    descriptionBn: "ঘিয়ে ভাজা সুগন্ধি পোলাও চালের সাথে জোড়া সোনালী ভাজা সিদ্ধ ডিম ও সালাদ (ফুল প্লেট)।",
    descriptionEn: "Rich fragrant ghee-cooked polao rice served with golden fried eggs and fresh salad (full plate).",
    displayOrder: 109,
    order: 109
  },
  {
    id: "rest_item_bhuna_khichuri_half_egg",
    nameBn: "ভুনা খিচুড়ি (ডিম হাফ)",
    nameEn: "Bhuna Khichuri (with Half Egg)",
    price: 60,
    originalPrice: 60,
    unitBn: "০১ প্লেট",
    unitEn: "1 Plate",
    category: "bakery-sweets",
    categoryId: "bakery-sweets",
    subcategoryId: "biryani-rice",
    subcategory: "বিরিয়ানি, পোলাও ও রাইস",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 25,
    brand: "কাচা বাজার রেস্টুরেন্ট",
    descriptionBn: "ভাজা মুগ ডাল ও সুগন্ধি চালের ঝরঝরে সোনালী ভুনা খিচুড়ি সাথে সিদ্ধ ডিমের অর্ধাংশ।",
    descriptionEn: "Traditional golden roasted moong dal and aromatic rice bhuna khichuri served with half egg.",
    displayOrder: 110,
    order: 110
  },
  {
    id: "rest_item_borhani_1_liter",
    nameBn: "বোরহানী (১ লিটার)",
    nameEn: "Borhani (1 Liter)",
    price: 160,
    originalPrice: 160,
    unitBn: "১ লিটার",
    unitEn: "1 Liter",
    category: "bakery-sweets",
    categoryId: "bakery-sweets",
    subcategoryId: "drinks-coffee",
    subcategory: "পানীয়, জুস ও কফি",
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.9,
    reviewCount: 44,
    brand: "কাচা বাজার রেস্টুরেন্ট",
    descriptionBn: "খাঁটি টক দই, পুদিনা পাতা, ধনেপাতা, বিট লবণ ও শাহী মসলার ঐতিহ্যবাহী ঢাকাই বোরহানী (১ লিটার ফ্যামিলি বোতল)।",
    descriptionEn: "Traditional spiced Dhaka-style chilled yogurt beverage Borhani with mint, coriander, and black salt (1 Liter Bottle).",
    displayOrder: 111,
    order: 111
  },
  {
    id: "rest_item_borhani_500ml",
    nameBn: "বোরহানী (হাফ লিটার)",
    nameEn: "Borhani (500ml)",
    price: 80,
    originalPrice: 80,
    unitBn: "৫০০ মিলি",
    unitEn: "500ml",
    category: "bakery-sweets",
    categoryId: "bakery-sweets",
    subcategoryId: "drinks-coffee",
    subcategory: "পানীয়, জুস ও কফি",
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.8,
    reviewCount: 33,
    brand: "কাচা বাজার রেস্টুরেন্ট",
    descriptionBn: "ঐতিহ্যবাহী স্বাদের ঠান্ডা ও স্বাস্থ্যকর পুদিনা-টকদের ঢাকাই বোরহানী (৫০০ মিলি বোতল)।",
    descriptionEn: "Chilled traditional spiced yogurt drink Borhani with mint and digestives (500ml bottle).",
    displayOrder: 112,
    order: 112
  },
  {
    id: "rest_item_borhani_glass",
    nameBn: "বোরহানী (গ্লাস)",
    nameEn: "Borhani (Per Glass)",
    price: 40,
    originalPrice: 40,
    unitBn: "প্রতি গ্লাস",
    unitEn: "Per Glass",
    category: "bakery-sweets",
    categoryId: "bakery-sweets",
    subcategoryId: "drinks-coffee",
    subcategory: "পানীয়, জুস ও কফি",
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80",
    imageUrl: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80",
    inStock: true,
    stock: 100,
    isAvailable: true,
    isDeleted: false,
    status: "active",
    rating: 4.9,
    reviewCount: 50,
    brand: "কাচা বাজার রেস্টুরেন্ট",
    descriptionBn: "এক গ্লাস তাজা ও ঠান্ডা হজমিকারক সুস্বাদু শাহী বোরহানী।",
    descriptionEn: "Single chilled glass of authentic zesty digestif Shahi Borhani.",
    displayOrder: 113,
    order: 113
  }
];

export { COSMETICS_PRODUCTS_RAW } from "./lib/cosmeticsData";
export { CONFECTIONERY_PRODUCTS_RAW, CONFECTIONERY_SNACKS_RAW } from "./lib/confectioneryData";
export { MOBILE_ZONE_PRODUCTS_RAW } from "./lib/mobileProductsData";
export { PHARMACY_PRODUCTS_RAW, OFFICIAL_MEDICINE_PRICES } from "./lib/pharmacyData";

import { CONFECTIONERY_PRODUCTS_RAW } from "./lib/confectioneryData";
import { MOBILE_ZONE_PRODUCTS_RAW } from "./lib/mobileProductsData";
import { PHARMACY_PRODUCTS_RAW } from "./lib/pharmacyData";

export const PRODUCTS: Product[] = [...GROCERY_PRODUCTS_RAW, ...COSMETICS_PRODUCTS_RAW, ...RESTAURANT_PRODUCTS_RAW, ...CONFECTIONERY_PRODUCTS_RAW, ...MOBILE_ZONE_PRODUCTS_RAW, ...PHARMACY_PRODUCTS_RAW];
export const ALL_PRODUCTS: Product[] = [...GROCERY_PRODUCTS_RAW, ...COSMETICS_PRODUCTS_RAW, ...RESTAURANT_PRODUCTS_RAW, ...CONFECTIONERY_PRODUCTS_RAW, ...MOBILE_ZONE_PRODUCTS_RAW, ...PHARMACY_PRODUCTS_RAW];
export const RESTAURANT_MENU_SECTIONS: string[] = [
  "বিরিয়ানি, পোলাও ও রাইস",
  "বার্গার, স্যান্ডউইচ ও শাওয়ার্মা",
  "পিজ্জা, পাস্তা ও চাউমিন",
  "চিকেন ফ্রাই, উইংস ও ললিপপ",
  "গ্রিল, সিজলিং ও কাবাব",
  "অ্যাপেটাইজার, ফাস্ট ফুড ও স্যুপ",
  "দেশি তরকারি ও চাইনিজ ডিশ",
  "নান, রুটি, পরোটা ও হালিম",
  "পানীয়, জুস ও মিষ্টি"
];
export const GROCERY_SECTIONS: string[] = [
  "চাল ও খাদ্যশস্য",
  "ডাল ও ছোলা",
  "তেল, চিনি, লবণ ও গুড়",
  "আটা, ময়দা ও সুজি",
  "মসলাপাতি — আস্ত ও গুঁড়ো",
  "রেডি মসলা ও বেকিং উপাদান",
  "মসলা ও রান্নার তেল"
];
export const isRiceOrGrainProduct = (_prod?: any): boolean => false;
export const isDalOrPulseProduct = (_prod?: any): boolean => false;
export const getResolvedGrocerySubcategory = (
  _id?: string, 
  nameBn?: string, 
  nameEn?: string, 
  subcategory?: string, 
  _category?: string
): string => {
  if (subcategory && subcategory.trim() && subcategory !== "General" && subcategory !== "all") {
    const s = subcategory.trim();
    if (s === "রেডি মসলা ও বেকিং আইটেম" || s === "রেডি মসলা ও বেকিং উপাদান") {
      return "রেডি মসলা ও বেকিং উপাদান";
    }
    return s;
  }
  const bn = (nameBn || "").toLowerCase();
  const en = (nameEn || "").toLowerCase();
  if (bn.includes("চাল") || bn.includes("চাউল") || en.includes("rice") || bn.includes("পোলাও") || bn.includes("খাদ্যশস্য") || bn.includes("গম") || bn.includes("ভুট্টা")) {
    return "চাল ও খাদ্যশস্য";
  }
  if (bn.includes("ডাল") || bn.includes("ডাউল") || en.includes("dal") || en.includes("lentil") || bn.includes("ছোলা") || bn.includes("মটর")) {
    return "ডাল ও ছোলা";
  }
  if (bn.includes("তেল") || en.includes("oil") || bn.includes("চিনি") || bn.includes("লবণ") || bn.includes("গুড়") || en.includes("sugar") || en.includes("salt")) {
    return "তেল, চিনি, লবণ ও গুড়";
  }
  if (bn.includes("আটা") || bn.includes("ময়দা") || bn.includes("সুজি") || bn.includes("সেমাই") || en.includes("flour") || en.includes("maida") || en.includes("suji") || en.includes("semai")) {
    return "আটা, ময়দা ও সুজি";
  }
  if (bn.includes("মিক্স") || bn.includes("বেকিং") || en.includes("baking") || en.includes("mix") || bn.includes("কোকো") || bn.includes("ভ্যানিলা") || bn.includes("কাস্টার্ড") || bn.includes("ঘি") || bn.includes("বাটার") || bn.includes("ডালডা") || bn.includes("ভিনেগার") || bn.includes("ইস্ট") || bn.includes("কর্নফ্লাওয়ার")) {
    return "রেডি মসলা ও বেকিং উপাদান";
  }
  if (bn.includes("মসলা") || en.includes("spice") || bn.includes("মরিচ") || bn.includes("হলুদ") || bn.includes("জিরা") || bn.includes("ধনিয়া") || bn.includes("দারুচিনি") || bn.includes("দারচিনি") || bn.includes("এলাচ") || bn.includes("লবঙ্গ") || bn.includes("গোলমরিচ") || bn.includes("গোল মরিচ") || bn.includes("তেজপাতা") || bn.includes("মেথি") || bn.includes("মৌরি") || bn.includes("জয়ফল") || bn.includes("জয়ত্রী") || bn.includes("সাদা ফল")) {
    return "মসলাপাতি — আস্ত ও গুঁড়ো";
  }
  return subcategory || "তেল, চিনি, লবণ ও গুড়";
};
export const getResolvedGroceryDisplayOrder = (
  id?: string, 
  _nameBn?: string, 
  _nameEn?: string, 
  _sub?: string, 
  order?: number
): number | undefined => {
  if (id && /^gr\d+$/.test(id)) {
    const num = parseInt(id.replace("gr", ""), 10);
    if (!isNaN(num)) return num;
  }
  return order;
};
export const GROCERY_SUBCATEGORY_MAP: Record<string, string> = {};
export const GROCERY_ORDER_MAP: Record<string, number> = {};
export const DRY_FOOD_RAW: any[] = [];

export const PROMO_BANNERS: PromoBanner[] = [
  {
    id: "b1",
    titleBn: "সরাসরি মাঠ থেকে আপনার রান্নাঘরে",
    titleEn: "Directly from Farms to Your Kitchen",
    subtitleBn: "১০-১৫ মিনিটে দ্রুত ডেলিভারি, একদম সতেজ এবং খাঁটি গ্যারান্টি",
    subtitleEn: "15-minute express delivery of fresh organic produce",
    tagBn: "ফ্ল্যাশ ক্যাম্পেইন",
    tagEn: "FLASH CAMPAIGN",
    discountBn: "২৫% পর্যন্ত মেগা ছাড়",
    discountEn: "UP TO 25% MEGA SAVINGS",
    bgGradient: "from-emerald-700 via-teal-600 to-green-700",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "b2",
    titleBn: "পদ্মার রূপালী ইলিশ উৎসব চলছে!",
    titleEn: "Padma River Hilsha Festival!",
    subtitleBn: "নদী থেকে ধৃত সরাসরি ইলিশ, স্বাদে ও আকৃতিতে শতভাগ খাঁটি",
    subtitleEn: "Authentic river-caught Silver Hilsha with unmatched flavor",
    tagBn: "সরাসরি সোর্স",
    tagEn: "DIRECTLY SOURCED",
    discountBn: "ফ্ল্যাট ১২% সরাসরি ছাড়",
    discountEn: "FLAT 12% INSTANT DISCOUNT",
    bgGradient: "from-indigo-700 via-blue-600 to-cyan-700",
    image: "https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "b3",
    titleBn: "রাজশাহীর মিষ্টি হিমসাগর আমমেলা",
    titleEn: "Sweet & Luscious Himsagar Mango Fest",
    subtitleBn: "১০০% ফরমালিন ও রাসায়নিক মুক্ত গাছের পাকা আম",
    subtitleEn: "100% chemicals-free naturally tree-ripened sweet mangoes",
    tagBn: "আমের মৌসুম",
    tagEn: "MANGO MANIA",
    discountBn: "১৮% সরাসরি মূল্যছাড়",
    discountEn: "UP TO 18% DIRECT CUT",
    bgGradient: "from-orange-600 via-amber-500 to-yellow-600",
    image: "https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "b4",
    titleBn: "উইকেন্ড ফ্যামিলি গ্রোসারি মেলা",
    titleEn: "Weekend Family Grocery Fair",
    subtitleBn: "চাল, ডাল, তেল ও ডিমের বাজারে বিশেষ ছাড়",
    subtitleEn: "Massive savings on everyday staple household essentials",
    tagBn: "সাপ্তাহিক বাজার",
    tagEn: "WEEKLY BAZAR",
    discountBn: "সর্বোচ্চ ৩০০ টাকা ক্যাশব্যাক",
    discountEn: "UP TO BDT 300 CASHBACK",
    bgGradient: "from-rose-700 via-red-600 to-pink-700",
    image: "https://images.unsplash.com/photo-1506617498319-3310023a1a01?auto=format&fit=crop&w=800&q=80"
  }
];

export const RECIPES: Recipe[] = [
  {
    id: "r1",
    nameBn: "ঐতিহ্যবাহী সরিষা ইলিশ",
    nameEn: "Traditional Shorshe Ilish",
    prepTimeBn: "২৫ মিনিট",
    prepTimeEn: "25 Mins",
    difficultyBn: "সহজ",
    difficultyEn: "Easy",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    ingredients: [
      { productId: "fi1", nameBn: "পদ্মার ইলিশ মাছ", nameEn: "Padma Hilsha Fish", amountBn: "৫০০ গ্রাম", amountEn: "500g" },
      { productId: "sp2", nameBn: "খাঁটি সয়াবিন/সরিষার তেল", nameEn: "Pure Oil", amountBn: "৪ টেবিল চামচ", amountEn: "4 tbsp" },
      { productId: "sp11", nameBn: "ঝাল কাঁচা মরিচ", nameEn: "Green Chilli", amountBn: "৬-৭ টি", amountEn: "6-7 pcs" }
    ],
    instructionsBn: [
      "প্রথমে ইলিশের টুকরোগুলো ধুয়ে সামান্য হলুদ ও লবণ মেখে রাখুন।",
      "সরিষা দানা, কাঁচা মরিচ এবং এক চিমটি লবণ একসাথে পিষে পেস্ট বানিয়ে নিন।",
      "একটি কড়াইতে সরিষার তেল গরম করে তাতে কালোজিরা ও কাঁচা মরিচের ফোড়ন দিন।",
      "এবার সরিষা পেস্ট এবং সামান্য পানি দিয়ে কষিয়ে মাছের টুকরোগুলো ছাড়ুন।",
      "হালকা আঁচে ১০ মিনিট ঢাকা দিয়ে রান্না করুন। উপরে কাঁচা তেল ও মরিচ ছড়িয়ে নামান।"
    ],
    instructionsEn: [
      "Wash Hilsha steaks and marinate with a pinch of turmeric powder and salt.",
      "Blend mustard seeds, green chillies, and a pinch of salt with water into a smooth paste.",
      "Heat pure mustard oil in a pan, add nigella seeds and green chillies.",
      "Add the mustard paste and a bit of water, then gently place the fish steaks.",
      "Cover and simmer on low-medium heat for 10 minutes. Drizzle fresh oil on top and serve hot."
    ]
  }
];

export const REVIEWS: Review[] = [
  {
    id: "v1",
    userName: "তানজিম আহমেদ",
    rating: 5,
    commentBn: "মাত্র ১২ মিনিটে ধানমন্ডি এলাকায় সতেজ টমেটো ও ইলিশ পেয়েছি! প্যাকেজিং ও ডেলিভারি বয় খুব আন্তরিক ছিল। ৫ স্টারের দাবিদার।",
    commentEn: "Received fresh tomatoes and Hilsha in Dhanmondi in just 12 mins! Superb packaging and extremely courteous rider. 5-stars!",
    date: "July 10, 2026"
  },
  {
    id: "v2",
    userName: "ফারজানা শারমিন",
    rating: 5,
    commentBn: "কাচা বাজার অ্যাপের সরিষা ইলিশ রেসিপির সব উপকরণ এক ক্লিকে অর্ডার করেছি এবং তা দিয়ে চমৎকার রান্না করেছি। এই ফিচারটা খুবই দারুণ!",
    commentEn: "Ordered all Shorshe Ilish ingredients with a single click via their recipe corner. Feature is incredibly convenient and smart!",
    date: "July 11, 2026"
  },
  {
    id: "v3",
    userName: "মাহমুদ হাসান",
    rating: 4,
    commentBn: "হিমসাগর আমগুলো আসলেই মিষ্টি এবং ফরমালিন মুক্ত। তবে ব্রেডের স্টক শেষ হয়ে গিয়েছিল। আশা করি অতি দ্রুত স্টক বৃদ্ধি করা হবে।",
    commentEn: "Mangoes are genuinely sweet and fresh. Highly recommended. Out of stock for brown bread once, but customer support was very helpful.",
    date: "July 12, 2026"
  }
];
